<?php

declare(strict_types=1);

/**
 * Default entrance-music playlist for Website(default) / 长安汉服
 * (`websites/default/default/store-music`). Not Global — other websites
 * (e.g. DaoCharms) must configure their own website-scoped playlist.
 *
 * @return list<array{url:string,title:string,intro:array<string,string>}>
 */
return array (
  0 => 
  array (
    'url' => '/media/websites/default/default/store-music/HITA-赤伶.mp3',
    'title' => 'HITA-赤伶',
    'intro' => 
    array (
      'zh_Hans_CN' => '戏腔古风现象级爆款。昆曲念白与戏腔高潮刷屏全网，短视频时代最出圈的古风代表之一。',
      'zh_Hant_TW' => '戲腔古風現象級爆款。崑曲唸白與戲腔高潮刷屏全網，短視頻時代最出圈的古風代表之一。',
      'en_US' => 'Phenomenon opera-crossover 古风 hit. Kunqu narration and theatrical climax — a short-video era landmark.',
      'ja_JP' => '戯腔クロスオーバーの古風大ヒット。崑曲の台詞と高潮部が短動画時代の象徴的な一曲。',
      'ko_KR' => '희강 크로스오버 고풍 현상급 히트. 쿤취 내레이션과 클라이맥스 — 숏폼 시대 대표곡.',
      'fr_FR' => 'Hit 古风 croisé opéra. Narration kunqu et climax théâtral — un repère de l’ère short video.',
      'de_DE' => 'Phänomenaler Opern-Crossover-古风-Hit. Kunqu-Erzählung und theatralischer Höhepunkt — Short-Video-Ikone.',
      'es_ES' => 'Éxito 古风 de cruce con ópera. Narración kunqu y clímax teatral: icono de la era del vídeo corto.',
      'pt_BR' => 'Hit 古风 de crossover com ópera. Narração kunqu e clímax teatral — marco da era do short video.',
      'ru_RU' => 'Феноменальный 古风-хит с оперным кроссовером. Рассказ куньцюй и театральный пик — икона коротких видео.',
      'ar_SA' => 'أغنية غوفنغ ظاهرة بمزج الأوبرا. سرد كونتشي وذروة مسرحية — أيقونة عصر الفيديو القصير.',
      'th_TH' => 'เพลงกู่เฟิงฮิตระดับปรากฏการณ์ผสมเสียงงิ้ว การเล่าแบบคุนชวีและไคลแมกซ์ — สัญลักษณ์ยุควิดีโอสั้น',
      'vi_VN' => 'Hit cổ phong hiện tượng pha hí khang. Độc bạch Côn Khúc và cao trào — biểu tượng thời short video.',
      'id_ID' => 'Hit 古风 fenomena crossover opera. Narasi kunqu dan klimaks teatrikal — ikon era short video.',
      'hi_IN' => 'ऑपेरा-क्रॉसओवर गुफ़ेंग हिट। कुनच्यू कथन और नाटकीय चरम — शॉर्ट-वीडियो युग की मिसाल।',
      'bn_BD' => 'অপেরা-ক্রসওভার গুফেং হিট। কুনচু বর্ণনা ও নাটকীয় চূড়ান্ত — শর্ট-ভিডিও যুগের আইকন।',
      'ur_PK' => 'اوپرا کراس اوور قدیم چینی ہٹ۔ کنچو بیانیہ اور ڈرامائی عروج — شارٹ ویڈیو دور کی علامت۔',
      'default' => 'Phenomenon opera-crossover 古风 hit. Kunqu narration and theatrical climax — a short-video era landmark.',
    ),
  ),
  1 => 
  array (
    'url' => '/media/websites/default/default/store-music/林海-琵琶语.mp3',
    'title' => '林海-琵琶语',
    'intro' => 
    array (
      'zh_Hans_CN' => '林海经典琵琶器乐。清雅空灵，长期作为古风氛围与影视/店铺BGM的现象级代表。',
      'zh_Hant_TW' => '林海經典琵琶器樂。清雅空靈，長期作為古風氛圍與影視／店舖BGM的現象級代表。',
      'en_US' => 'Lin Hai’s iconic pipa piece. Clear and ethereal — a phenomenon-level 古风 ambience classic for film and storefront BGM.',
      'ja_JP' => 'リン・ハイの代表的な琵琶曲。清らかで幻想的。古風な雰囲気や映像・店舗BGMの定番。',
      'ko_KR' => '린하이의 대표 비파곡. 맑고 몽환적이며, 고풍 분위기·영상·매장 BGM의 현상급 명곡.',
      'fr_FR' => 'Pièce de pipa emblématique de Lin Hai. Claire et éthérée — un classique d’ambiance 古风 pour films et boutiques.',
      'de_DE' => 'Lin Hais ikonisches Pipa-Stück. Klar und ätherisch — ein Phänomen-Klassiker für 古风-Atmosphäre, Film und Laden-BGM.',
      'es_ES' => 'Pieza icónica de pipa de Lin Hai. Clara y etérea: un clásico fenomenal de ambiente 古风 para cine y tiendas.',
      'pt_BR' => 'Peça icônica de pipa de Lin Hai. Clara e etérea — um clássico fenomenal de clima 古风 para filmes e lojas.',
      'ru_RU' => 'Знаковая пьеса для пипы Линь Хая. Чистая и воздушная — феноменальная 古风-атмосфера для кино и магазинов.',
      'ar_SA' => 'مقطوعة بيبا أيقونية للين هاي. صافية وأثيرية — كلاسيكية أجواء صينية قديمة ذات شعبية هائلة للأفلام والمتاجر.',
      'th_TH' => 'บทพิณปี่ปาขึ้นชื่อของหลินไห่ ใสและลอยละล่อง เป็นเพลงบรรยากาศกู่เฟิงระดับปรากฏการณ์สำหรับภาพยนตร์และร้านค้า',
      'vi_VN' => 'Khúc tỳ bà kinh điển của Lâm Hải. Trong trẻo, hư ảo — đại diện hiện tượng cho không khí cổ phong, phim và BGM cửa hàng.',
      'id_ID' => 'Karya pipa ikonik Lin Hai. Jernih dan eterik — klasik suasana 古风 berskala fenomena untuk film dan BGM toko.',
      'hi_IN' => 'लिन हाई की प्रसिद्ध पीपा रचना। निर्मल और स्वप्निल — फ़िल्म व दुकान BGM के लिए घटना-स्तर की गुफ़ेंग क्लासिक।',
      'bn_BD' => 'লিন হাই-এর আইকনিক পিপা সঙ্গীত। স্বচ্ছ ও স্বপ্নময় — চলচ্চিত্র ও দোকানের BGM-এর জন্য ঘটনা-স্তরের গুফেং ক্লাসিক।',
      'ur_PK' => 'لن ہائی کا مشہور پیپا ٹکڑا۔ صاف اور خوابیدہ — فلم اور دکان BGM کے لیے رجحان ساز قدیم چینی ماحول کی کلاسک۔',
      'default' => 'Lin Hai’s iconic pipa piece. Clear and ethereal — a phenomenon-level 古风 ambience classic for film and storefront BGM.',
    ),
  ),
  2 => 
  array (
    'url' => '/media/websites/default/default/store-music/音阙诗听赵方婧-芒种.mp3',
    'title' => '音阙诗听赵方婧-芒种',
    'intro' => 
    array (
      'zh_Hans_CN' => '二十四节气古风爆款。赵方婧声线空灵，短视频时代最出圈的节气主题曲之一。',
      'zh_Hant_TW' => '二十四節氣古風爆款。趙方婧聲線空靈，短視頻時代最出圈的節氣主題曲之一。',
      'en_US' => 'Viral solar-term 古风 hit. Zhao Fangjing’s ethereal voice — a short-video era anthem of the Grain in Ear season.',
      'ja_JP' => '二十四節気モチーフの古風大ヒット。趙方婧の透き通る歌声が短動画時代の代表曲に。',
      'ko_KR' => '이십사절기 고풍 히트. 자오팡징의 몽환 보이스 — 숏폼 시대 망종 테마 대표곡.',
      'fr_FR' => 'Hit 古风 des 24 termes solaires. Voix éthérée de Zhao Fangjing — hymne short video de la saison Mangzhong.',
      'de_DE' => 'Viraler 古风-Hit zu den 24 Solarterminen. Zhao Fangjings ätherische Stimme — Short-Video-Hymne zu Mangzhong.',
      'es_ES' => 'Éxito 古风 de los 24 términos solares. Voz etérea de Zhao Fangjing: himno short video de Mangzhong.',
      'pt_BR' => 'Hit 古风 dos 24 termos solares. Voz etérea de Zhao Fangjing — hino short video de Mangzhong.',
      'ru_RU' => 'Вирусный 古风-хит о 24 сезонах. Небесный голос Чжао Фанцзин — гимн коротких видео о Манчжуне.',
      'ar_SA' => 'أغنية غوفنغ فيروسية عن المواسم الأربعة والعشرين. صوت تشاو فانغجينغ الأثيري — نشيد فيديو قصير لموسم مانغجونغ.',
      'th_TH' => 'เพลงกู่เฟิงฮิตธีม 24 ฤดูกาล เสียงใสของจ้าวฟางจิง — เพลงประจำยุควิดีโอสั้นเรื่องมังจง',
      'vi_VN' => 'Hit cổ phong chủ đề 24 tiết khí. Giọng hư ảo của Triệu Phương Tịnh — bài hát biểu tượng short video về Mang Chủng.',
      'id_ID' => 'Hit 古风 tema 24 istilah surya. Suara eterik Zhao Fangjing — himne short video musim Mangzhong.',
      'hi_IN' => 'चौबीस सौर-अवधि गुफ़ेंग हिट। झाओ फांगजिंग की स्वप्निल आवाज़ — मैंगझोंग का शॉर्ट-वीडियो गान।',
      'bn_BD' => '২৪ সৌর-পর্বের গুফেং হিট। ঝাও ফাংজিং-এর স্বপ্নময় কণ্ঠ — ম্যাংঝং-এর শর্ট-ভিডিও অ্যানথেম।',
      'ur_PK' => 'چوبیس شمسی موسموں کا قدیم چینی ہٹ۔ ژاؤ فانگ جِنگ کی خوابیدہ آواز — مانگ ژونگ کا شارٹ ویڈیو ترانہ۔',
      'default' => 'Viral solar-term 古风 hit. Zhao Fangjing’s ethereal voice — a short-video era anthem of the Grain in Ear season.',
    ),
  ),
  3 => 
  array (
    'url' => '/media/websites/default/default/store-music/花粥马雨阳-盗将行.mp3',
    'title' => '花粥马雨阳-盗将行',
    'intro' => 
    array (
      'zh_Hans_CN' => '花粥×马雨阳。侠气对唱、故事感极强，长期霸榜古风热歌与二创BGM。',
      'zh_Hant_TW' => '花粥×馬雨陽。俠氣對唱、故事感極強，長期霸榜古風熱歌與二創BGM。',
      'en_US' => 'Hua Zhou × Ma Yuyang. Knightly duet with strong storytelling — a long-running 古风 chart and fan-edit BGM staple.',
      'ja_JP' => '花粥×馬雨陽。侠気のデュエットと強い物語性。古風チャートと二次創作BGMの定番。',
      'ko_KR' => '화저우×마위양. 협기 듀엣과 강한 스토리 — 고풍 차트·2차 창작 BGM 단골.',
      'fr_FR' => 'Hua Zhou × Ma Yuyang. Duo chevaleresque très narratif — classique des charts 古风 et BGM de fan-edits.',
      'de_DE' => 'Hua Zhou × Ma Yuyang. Ritterliches Duett mit starker Story — Dauerbrenner in 古风-Charts und Fan-Edit-BGM.',
      'es_ES' => 'Hua Zhou × Ma Yuyang. Dúo caballeresco muy narrativo: fijo en charts 古风 y BGM de fan-edits.',
      'pt_BR' => 'Hua Zhou × Ma Yuyang. Dueto cavaleiresco e narrativo — clássico de charts 古风 e BGM de fan-edits.',
      'ru_RU' => 'Хуа Чжоу × Ма Юйян. Рыцарский дуэт с сильной историей — долгожитель чартов 古风 и BGM фан-монтажей.',
      'ar_SA' => 'هوا تشو × ما يويانغ. ثنائي فروسي برواية قوية — ثابت في قوائم الغوفنغ وموسيقى إعادة المونتاج.',
      'th_TH' => 'ฮัวโจว×ม้าอวี่หยาง ดูเอต์แนวจอมยุทธ์เล่าเรื่องเข้ม — ประจำชาร์ตกู่เฟิงและ BGM คลิปแฟนเมด',
      'vi_VN' => 'Hoa Chúc × Mã Vũ Dương. Song ca hiệp khí, giàu cốt truyện — trụ cột chart cổ phong và BGM fan-edit.',
      'id_ID' => 'Hua Zhou × Ma Yuyang. Duet kesatria bernarasi kuat — andalan chart 古风 dan BGM fan-edit.',
      'hi_IN' => 'हुआ झोउ × मा युयांग। योद्धा दुएट, मजबूत कहानी — गुफ़ेंग चार्ट और फैन-एडिट BGM का स्थायी।',
      'bn_BD' => 'হুয়া ঝোউ × মা ইউইয়াং। নাইটলি ডুয়েট, শক্তিশালী গল্প — গুফেং চার্ট ও ফ্যান-এডিট BGM-এর স্থায়ী।',
      'ur_PK' => 'ہوا ژو × ما یو یانگ۔ شہسواری ڈوئٹ، مضبوط کہانی — قدیم چینی چارٹ اور فین ایڈٹ BGM کا مستقل۔',
      'default' => 'Hua Zhou × Ma Yuyang. Knightly duet with strong storytelling — a long-running 古风 chart and fan-edit BGM staple.',
    ),
  ),
  4 => 
  array (
    'url' => '/media/websites/default/default/store-music/等什么君-辞九门回想.mp3',
    'title' => '等什么君-辞九门回想',
    'intro' => 
    array (
      'zh_Hans_CN' => '抖音古风伤感顶流之一。九门辞别意象洗脑，短视频情绪向BGM常客。',
      'zh_Hant_TW' => '抖音古風傷感頂流之一。九門辭別意象洗腦，短視頻情緒向BGM常客。',
      'en_US' => 'Top melancholic 古风 on Douyin. Farewell-at-the-nine-gates imagery — a short-video emotion BGM staple.',
      'ja_JP' => '抖音で人気の感傷的な古風。九門での別れのイメージが印象的。短動画の情緒BGM定番。',
      'ko_KR' => '더우인 감성 고풍 탑 티어. 구문 이별 이미지 — 숏폼 감정 BGM 단골.',
      'fr_FR' => 'Top 古风 mélancolique sur Douyin. Image d’adieu aux neuf portes — BGM émotionnel short video.',
      'de_DE' => 'Top-melancholischer 古风 auf Douyin. Abschied an den neun Toren — Short-Video-Emotions-BGM.',
      'es_ES' => 'Top 古风 melancólico en Douyin. Imagen de despedida en las nueve puertas: BGM emocional short video.',
      'pt_BR' => 'Top 古风 melancólico no Douyin. Imagem de despedida nas nove portas — BGM emocional short video.',
      'ru_RU' => 'Топ меланхоличного 古风 на Douyin. Прощание у девяти врат — эмоциональный BGM коротких видео.',
      'ar_SA' => 'من أبرز أغاني الغوفنغ الحزينة على دويين. صورة وداع الأبواب التسعة — موسيقى خلفية عاطفية للفيديو القصير.',
      'th_TH' => 'เพลงกู่เฟิงเศร้าติดท็อป Douyin ภาพลาจากเก้าประตู — BGM อารมณ์ประจำคลิปสั้น',
      'vi_VN' => 'Top cổ phong buồn trên Douyin. Hình ảnh từ biệt Cửu Môn — BGM cảm xúc short video quen thuộc.',
      'id_ID' => 'Top 古风 melankolis di Douyin. Citra perpisahan di sembilan gerbang — BGM emosi short video.',
      'hi_IN' => 'डॉयिन पर शीर्ष उदास गुफ़ेंग। नौ द्वार पर विदाई — शॉर्ट-वीडियो इमोशन BGM।',
      'bn_BD' => 'ডউইনে শীর্ষ বিষণ্ণ গুফেং। নয় দরজায় বিদায় — শর্ট-ভিডিও ইমোশন BGM।',
      'ur_PK' => 'ڈوئین پر اعلیٰ اداس قدیم چینی گانا۔ نو دروازوں پر الوداع — شارٹ ویڈیو جذباتی BGM۔',
      'default' => 'Top melancholic 古风 on Douyin. Farewell-at-the-nine-gates imagery — a short-video emotion BGM staple.',
    ),
  ),
  5 => 
  array (
    'url' => '/media/websites/default/default/store-music/洛先生-孤城.mp3',
    'title' => '洛先生-孤城',
    'intro' => 
    array (
      'zh_Hans_CN' => '洛先生古风流行曲。孤城意象与烟火气编曲，店面古风氛围里很耐听。',
      'zh_Hant_TW' => '洛先生古風流行曲。孤城意象與煙火氣編曲，店舖古風氛圍裡很耐聽。',
      'en_US' => 'Luo Xiansheng’s popular 古风 song. Lonely-city imagery with warm, lived-in production — easy listening for store ambience.',
      'ja_JP' => '洛先生の古風ポップ。孤城のイメージと生活感ある編曲。店舗の古風な雰囲気に合う聞きやすい一曲。',
      'ko_KR' => '뤄셴성 고풍 팝. 외로운 성 이미지와 생활감 있는 편곡. 매장 고풍 분위기에 오래 듣기 좋은 곡.',
      'fr_FR' => 'Hit 古风 de Luo Xiansheng. Image de cité solitaire et arrangement chaleureux — agréable en ambiance boutique.',
      'de_DE' => 'Luo Xianshengs populärer 古风-Song. Bild der einsamen Stadt, warmes Arrangement — angenehm als Ladenatmosphäre.',
      'es_ES' => 'Éxito 古风 de Luo Xiansheng. Imagen de ciudad solitaria y producción cercana — agradable como ambiente de tienda.',
      'pt_BR' => 'Hit 古风 de Luo Xiansheng. Imagem de cidade solitária e produção acolhedora — ótimo como clima de loja.',
      'ru_RU' => 'Популярная 古风-песня Ло Сяньшэна. Образ одинокого города и тёплое звучание — приятно как фон магазина.',
      'ar_SA' => 'أغنية غوفنغ شعبية للو شيانشنغ. صورة مدينة وحيدة وإنتاج دافئ — مريحة كأجواء متجر.',
      'th_TH' => 'เพลงกู่เฟิงฮิตของลั่วเซียนเซิง ภาพเมืองโดดเดี่ยวกับการเรียบเรียงอบอุ่น ฟังยาวๆ ในบรรยากาศร้านได้ดี',
      'vi_VN' => 'Ca khúc cổ phong phổ biến của Lạc Tiên Sinh. Hình ảnh cô thành và phối khí ấm áp — rất dễ nghe làm không khí cửa hàng.',
      'id_ID' => 'Lagu 古风 populer Luo Xiansheng. Citra kota sunyi dengan aransemen hangat — enak didengar untuk suasana toko.',
      'hi_IN' => 'लुओ श्यनशेंग का लोकप्रिय गुफ़ेंग गीत। अकेले शहर की छवि और गर्म प्रोडक्शन — दुकान के माहौल के लिए सुगम श्रवण।',
      'bn_BD' => 'লুও শিয়ানশেং-এর জনপ্রিয় গুফেং গান। নিঃসঙ্গ শহরের চিত্র ও উষ্ণ প্রোডাকশন — দোকানের পরিবেশের জন্য সহজে শোনা যায়।',
      'ur_PK' => 'لؤو شیان شینگ کا مقبول قدیم چینی طرز کا گانا۔ تنہا شہر کی تصویر اور گرم آرکسٹریشن — دکان کے ماحول کے لیے خوشگوار۔',
      'default' => 'Luo Xiansheng’s popular 古风 song. Lonely-city imagery with warm, lived-in production — easy listening for store ambience.',
    ),
  ),
  6 => 
  array (
    'url' => '/media/websites/default/default/store-music/花粥王忻辰-出山.mp3',
    'title' => '花粥王忻辰-出山',
    'intro' => 
    array (
      'zh_Hans_CN' => '花粥×王忻辰。江湖气开场与记忆点副歌，古风热歌榜常客，店面节奏感强。',
      'zh_Hant_TW' => '花粥×王忻辰。江湖氣開場與記憶點副歌，古風熱歌榜常客，店舖節奏感強。',
      'en_US' => 'Hua Zhou × Wang Xinchen. Jianghu-flavored opening and sticky chorus — a 古风 chart regular with strong storefront energy.',
      'ja_JP' => '花粥×王忻辰。江湖感のある入りと耳に残るサビ。古風チャート常連で店舗にも合うリズム。',
      'ko_KR' => '화저우×왕신첸. 강호 오프닝과 중독성 코러스 — 고풍 차트 단골, 매장 리듬감 강함.',
      'fr_FR' => 'Hua Zhou × Wang Xinchen. Ouverture jianghu et refrain accrocheur — régulier des charts 古风, rythme boutique.',
      'de_DE' => 'Hua Zhou × Wang Xinchen. Jianghu-Öffnung und Ohrwurm-Refrain — 古风-Chart-Stammgast mit Laden-Drive.',
      'es_ES' => 'Hua Zhou × Wang Xinchen. Apertura jianghu y estribillo pegajoso: fijo en charts 古风 con ritmo de tienda.',
      'pt_BR' => 'Hua Zhou × Wang Xinchen. Abertura jianghu e refrão grudento — regular de charts 古风 com ritmo de loja.',
      'ru_RU' => 'Хуа Чжоу × Ван Синьчэнь. Открытие в духе цзянху и цепкий припев — частый гость чартов 古风 с драйвом для магазина.',
      'ar_SA' => 'هوا تشو × وانغ شينتشن. افتتاح بطابع الجيانغهو وكورس لاصق — ضيف دائم في قوائم الغوفنغ بطاقة متجر.',
      'th_TH' => 'ฮัวโจว×หวังซินเฉิน เปิดแบบเจียงหูคอรัสติดหู — ประจำชาร์ตกู่เฟิง จังหวะร้านชัด',
      'vi_VN' => 'Hoa Chúc × Vương Hân Thần. Mở đầu giang hồ, điệp khúc bắt tai — khách quen chart cổ phong, nhịp cửa hàng mạnh.',
      'id_ID' => 'Hua Zhou × Wang Xinchen. Pembuka jianghu dan chorus lengket — langganan chart 古风 dengan ritme toko.',
      'hi_IN' => 'हुआ झोउ × वांग शिनचेन। जियांगहू ओपनिंग और चिपकू कोरस — गुफ़ेंग चार्ट नियमित, दुकान की लय।',
      'bn_BD' => 'হুয়া ঝোউ × ওয়াং শিনচেন। জিয়াংহু ওপেনিং ও স্টিকি কোরাস — গুফেং চার্ট নিয়মিত, দোকানের ছন্দ।',
      'ur_PK' => 'ہوا ژو × وانگ شن چن۔ جیانگ ہو اوپننگ اور چسپاں کورس — قدیم چینی چارٹ کا باقاعدہ، دکان کی تال۔',
      'default' => 'Hua Zhou × Wang Xinchen. Jianghu-flavored opening and sticky chorus — a 古风 chart regular with strong storefront energy.',
    ),
  ),
  7 => 
  array (
    'url' => '/media/websites/default/default/store-music/奇然沈谧仁-琵琶行.mp3',
    'title' => '奇然沈谧仁-琵琶行',
    'intro' => 
    array (
      'zh_Hans_CN' => '奇然×沈谧仁。以《琵琶行》诗意为骨的古风流行对唱，意境辽阔，店面古风很有辨识度。',
      'zh_Hant_TW' => '奇然×沈謐仁。以《琵琶行》詩意為骨的古風流行對唱，意境遼闊，店舖古風很有辨識度。',
      'en_US' => 'Qiran × Shen Miren. Popular 古风 duet built on the poem “Pipa Xing” — wide imagery, strong storefront identity.',
      'ja_JP' => '奇然×沈謐仁。『琵琶行』の詩情を軸にした古風デュエット。広い情景で店舗の古風に映える。',
      'ko_KR' => '치란×선미런. 《비파행》 시의를 뼈대로 한 고풍 듀엣 — 넓은 정경, 매장 고풍 존재감.',
      'fr_FR' => 'Qiran × Shen Miren. Duo 古风 sur le poème « Pipa Xing » — imagerie vaste, identité boutique forte.',
      'de_DE' => 'Qiran × Shen Miren. 古风-Duett nach dem Gedicht „Pipa Xing“ — weite Bilder, starke Laden-Identität.',
      'es_ES' => 'Qiran × Shen Miren. Dúo 古风 sobre el poema «Pipa Xing»: imagen amplia, identidad de tienda clara.',
      'pt_BR' => 'Qiran × Shen Miren. Dueto 古风 sobre o poema “Pipa Xing” — imagem ampla, identidade forte na loja.',
      'ru_RU' => 'Цижань × Шэнь Мижэнь. Дуэт 古风 по поэме «Пипа син» — широкий образ, сильная идентичность магазина.',
      'ar_SA' => 'تشيران × شن ميرن. ثنائي غوفنغ مبني على قصيدة «بيبا شينغ» — صور واسعة وهوية متجر واضحة.',
      'th_TH' => 'ฉีหรัน×เสิ่นมี่เหริน ดูเอตกู่เฟิงจากบทกวี《ปี่ปาสิง》 — ภาพกว้าง เอกลักษณ์ร้านชัด',
      'vi_VN' => 'Kỳ Nhiên × Thẩm Mật Nhân. Song ca cổ phong dựa thơ «Tỳ Bà Hành» — cảnh rộng, nhận diện cửa hàng rõ.',
      'id_ID' => 'Qiran × Shen Miren. Duet 古风 berbasis puisi “Pipa Xing” — imaji luas, identitas toko kuat.',
      'hi_IN' => 'चीरान × शेन मीरेन। कविता «पीपा शिंग» पर गुफ़ेंग दुएट — विस्तृत चित्र, दुकान की पहचान।',
      'bn_BD' => 'চিরান × শেন মিরেন। কবিতা «পিপা শিং»-ভিত্তিক গুফেং ডুয়েট — বিস্তৃত চিত্র, দোকানের পরিচয়।',
      'ur_PK' => 'چی ران × شن می رن۔ نظم «پیپا شنگ» پر قدیم چینی ڈوئٹ — وسیع منظر، دکان کی شناخت۔',
      'default' => 'Qiran × Shen Miren. Popular 古风 duet built on the poem “Pipa Xing” — wide imagery, strong storefront identity.',
    ),
  ),
  8 => 
  array (
    'url' => '/media/websites/default/default/store-music/奇然沈谧仁-琵琶行双女声.mp3',
    'title' => '奇然沈谧仁-琵琶行双女声',
    'intro' => 
    array (
      'zh_Hans_CN' => '《琵琶行》双女声版。同曲异编，女声层次更柔、更适合长时间店面氛围循环。',
      'zh_Hant_TW' => '《琵琶行》雙女聲版。同曲異編，女聲層次更柔、更適合長時間店舖氛圍循環。',
      'en_US' => '“Pipa Xing” dual-female-vocal version. Same song, softer layered vocals — better for long storefront ambience loops.',
      'ja_JP' => '『琵琶行』女性デュエット版。同曲の別アレンジ。柔らかい層で店舗の長時間BGMに向き。',
      'ko_KR' => '《비파행》 더블 여성보컬 버전. 같은 곡·다른 편곡 — 부드러운 층감, 긴 매장 루프에 적합.',
      'fr_FR' => 'Version duo féminin de « Pipa Xing ». Même titre, voix plus douces — mieux pour de longues boucles boutique.',
      'de_DE' => 'Doppel-Frauenstimmen-Version von „Pipa Xing“. Gleicher Song, weichere Lagen — gut für lange Laden-Loops.',
      'es_ES' => 'Versión a dos voces femeninas de «Pipa Xing». Misma canción, capas más suaves: ideal para bucles largos de tienda.',
      'pt_BR' => 'Versão com duas vozes femininas de “Pipa Xing”. Mesma música, camadas mais suaves — ótima para loops longos na loja.',
      'ru_RU' => 'Версия «Пипа син» с двумя женскими голосами. Та же песня, более мягкие слои — лучше для длинных петель магазина.',
      'ar_SA' => 'نسخة ثنائية نسائية من «بيبا شينغ». نفس الأغنية بطبقات أنعم — أنسب لتكرار أجواء المتجر طويلاً.',
      'th_TH' => 'เวอร์ชันเสียงหญิงคู่ของ《ปี่ปาสิง》 เพลงเดิมเรียบเรียงใหม่ นุ่มกว่า — เหมาะวนยาวในร้าน',
      'vi_VN' => 'Bản song nữ của «Tỳ Bà Hành». Cùng bài, phối mềm hơn — hợp vòng lặp không khí cửa hàng lâu.',
      'id_ID' => 'Versi dua vokal wanita “Pipa Xing”. Lagu sama, lapisan lebih lembut — cocok loop suasana toko lama.',
      'hi_IN' => '«पीपा शिंग» दोहरे महिला स्वर संस्करण। वही गीत, नरम परतें — लंबे स्टोर लूप के लिए बेहतर।',
      'bn_BD' => '«পিপা শিং» দ্বৈত নারী কণ্ঠ সংস্করণ। একই গান, নরম স্তর — দীর্ঘ দোকান লুপের জন্য ভালো।',
      'ur_PK' => '«پیپا شنگ» دوہری خاتون آواز ورژن۔ وہی گانا، نرم تہیں — طویل دکان لوپ کے لیے بہتر۔',
      'default' => '“Pipa Xing” dual-female-vocal version. Same song, softer layered vocals — better for long storefront ambience loops.',
    ),
  ),
  9 => 
  array (
    'url' => '/media/websites/default/default/store-music/银临-入阵曲.mp3',
    'title' => '银临-入阵曲',
    'intro' => 
    array (
      'zh_Hans_CN' => '银临古风代表作之一。鼓点与战意编曲鲜明，适合店面需要一点“起势”的时段。',
      'zh_Hant_TW' => '銀臨古風代表作之一。鼓點與戰意編曲鮮明，適合店舖需要一點「起勢」的時段。',
      'en_US' => 'One of Yinlin’s signature 古风 tracks. Crisp drums and battle energy — good when the storefront needs a lift.',
      'ja_JP' => '銀臨の代表的な古風曲の一つ。太鼓と戦意の編曲が鮮やか。店舗に勢いが欲しい時間帯向き。',
      'ko_KR' => '은림 고풍 대표작 중 하나. 또렷한 드럼과 전운 편곡 — 매장에 기세가 필요할 때.',
      'fr_FR' => 'Un des titres 古风 signature de Yinlin. Batterie nette et énergie de bataille — quand la boutique veut du relief.',
      'de_DE' => 'Eines von Yinlins 古风-Signature-Tracks. Klare Drums und Kampfenergie — wenn der Laden Auftrieb braucht.',
      'es_ES' => 'Uno de los 古风 firma de Yinlin. Percusión nítida y energía de batalla: cuando la tienda necesita impulso.',
      'pt_BR' => 'Um dos 古风 assinatura de Yinlin. Bateria nítida e energia de batalha — quando a loja precisa de elevação.',
      'ru_RU' => 'Один из фирменных 古风-треков Иньлинь. Чёткие барабаны и боевой драйв — когда магазину нужен подъём.',
      'ar_SA' => 'من أعمال يينلين الغوفنغ المميزة. طبول واضحة وطاقة معركة — حين يحتاج المتجر دفعة.',
      'th_TH' => 'หนึ่งในผลงานกู่เฟิงลายเซ็นของหยินหลิน กลองชัดพลังสงคราม — เวลาที่ร้านต้องการแรงยก',
      'vi_VN' => 'Một trong những ca khúc cổ phong đặc trưng của Ngân Lâm. Trống rõ, khí chiến — khi cửa hàng cần “khởi thế”.',
      'id_ID' => 'Salah satu 古风 signature Yinlin. Drum tajam dan energi perang — saat toko butuh dorongan.',
      'hi_IN' => 'यिनलिन के सिग्नेचर गुफ़ेंग में से एक। साफ़ ड्रम और युद्ध ऊर्जा — जब दुकान को उभार चाहिए।',
      'bn_BD' => 'ইয়িনলিনের সিগনেচার গুফেং-এর একটি। স্পষ্ট ড্রাম ও যুদ্ধশক্তি — যখন দোকানে উত্তোলন দরকার।',
      'ur_PK' => 'ین لِن کے سگنیچر قدیم چینی ٹریکس میں سے ایک۔ واضح ڈرم اور جنگی توانائی — جب دکان کو اٹھان چاہیے۔',
      'default' => 'One of Yinlin’s signature 古风 tracks. Crisp drums and battle energy — good when the storefront needs a lift.',
    ),
  ),
  10 => 
  array (
    'url' => '/media/websites/default/default/store-music/五音Jw-明月天涯.mp3',
    'title' => '五音Jw-明月天涯',
    'intro' => 
    array (
      'zh_Hans_CN' => '五音Jw古风流行。明月与天涯意象清亮，适合店面中段的柔和过渡。',
      'zh_Hant_TW' => '五音Jw古風流行。明月與天涯意象清亮，適合店舖中段的柔和過渡。',
      'en_US' => 'Wuyin Jw popular 古风. Bright moon-and-horizon imagery — a soft mid-set transition for storefront play.',
      'ja_JP' => '五音Jwの古風ポップ。明月と天涯の明るいイメージ。店舗プレイリスト中盤の柔らかいつなぎに。',
      'ko_KR' => '우인Jw 고풍 팝. 밝은 달·천애 이미지 — 매장 중반 부드러운 전환용.',
      'fr_FR' => '古风 pop de Wuyin Jw. Images claires de lune et d’horizon — transition douce en milieu de set boutique.',
      'de_DE' => 'Wuyin-Jw-古风-Pop. Helle Mond-und-Horizont-Bilder — sanfter Mittelteil-Übergang im Laden-Set.',
      'es_ES' => '古风 pop de Wuyin Jw. Imagen clara de luna y horizonte: transición suave a mitad del set de tienda.',
      'pt_BR' => '古风 pop de Wuyin Jw. Imagem clara de lua e horizonte — transição suave no meio do set da loja.',
      'ru_RU' => 'Поп-古风 Уинь Jw. Яркий образ луны и края света — мягкий переход в середине магазинного сета.',
      'ar_SA' => 'بوب غوفنغ من وويين Jw. صورة قمر وأفق ساطعة — انتقال ناعم في منتصف قائمة المتجر.',
      'th_TH' => 'กู่เฟิงป็อปของอู่ยินJw ภาพจันทร์สว่างสุดขอบฟ้า — ช่วงกลางเพลย์ลิสต์ร้านที่นุ่ม',
      'vi_VN' => 'Cổ phong pop của Ngũ Âm Jw. Hình ảnh minh nguyệt–thiên nhai sáng — chuyển cảnh mềm giữa set cửa hàng.',
      'id_ID' => 'Pop 古风 Wuyin Jw. Citra bulan dan cakrawala cerah — transisi lembut di tengah set toko.',
      'hi_IN' => 'वूयिन Jw लोकप्रिय गुफ़ेंग। चंद्र-क्षितिज की उजली छवि — स्टोर सेट के बीच नरम संक्रमण।',
      'bn_BD' => 'উয়িন Jw জনপ্রিয় গুফেং। চাঁদ-দিগন্তের উজ্জ্বল চিত্র — দোকান সেটের মাঝে নরম রূপান্তর।',
      'ur_PK' => 'وو ین Jw مقبول قدیم چینی پاپ۔ چاند اور افق کی روشن تصویر — دکان سیٹ کے بیچ نرم منتقلی۔',
      'default' => 'Wuyin Jw popular 古风. Bright moon-and-horizon imagery — a soft mid-set transition for storefront play.',
    ),
  ),
  11 => 
  array (
    'url' => '/media/websites/default/default/store-music/张玮伽-惊鸿醉.mp3',
    'title' => '张玮伽-惊鸿醉',
    'intro' => 
    array (
      'zh_Hans_CN' => '张玮伽古风代表曲。惊鸿意象与醉意旋律，适合店面需要一点婉转亮点的时候。',
      'zh_Hant_TW' => '張瑋伽古風代表曲。驚鴻意象與醉意旋律，適合店舖需要一點婉轉亮點的時候。',
      'en_US' => 'Zhang Weijia’s signature 古风. Fleeting-swan imagery and tipsy melody — a graceful highlight in the store set.',
      'ja_JP' => '張瑋伽の代表的な古風曲。驚鴻のイメージと酔ったような旋律。店舗セットの優雅なアクセントに。',
      'ko_KR' => '장웨이자 고풍 대표곡. 경홍 이미지와 취기 멜로디 — 매장 세트의 우아한 하이라이트.',
      'fr_FR' => 'Titre 古风 signature de Zhang Weijia. Image du cygne fugace et mélodie ivre — accent gracieux en boutique.',
      'de_DE' => 'Zhang Weijias 古风-Signature. Bild des flüchtigen Schwans und berauschte Melodie — eleganter Akzent im Ladenset.',
      'es_ES' => '古风 firma de Zhang Weijia. Imagen de cisne fugaz y melodía embriagada: acento gracioso en la tienda.',
      'pt_BR' => '古风 assinatura de Zhang Weijia. Imagem de cisne fugaz e melodia embriagada — destaque gracioso na loja.',
      'ru_RU' => 'Фирменный 古风 Чжан Вэйцзя. Образ мимолётного лебедя и хмельная мелодия — изящный акцент в сете магазина.',
      'ar_SA' => 'عمل غوفنغ مميز لتشانغ وييجيا. صورة بجعة عابرة ولحن ثمل — لمسة أنيقة في قائمة المتجر.',
      'th_TH' => 'เพลงกู่เฟิงลายเซ็นของจางเวยเจีย ภาพหงส์วูบและทำนองเมา — จุดเด่นละมุนในเพลย์ลิสต์ร้าน',
      'vi_VN' => 'Ca khúc cổ phong đặc trưng của Trương Vỹ Già. Hình ảnh kinh hồng và giai điệu say — điểm nhấn dịu trên cửa hàng.',
      'id_ID' => '古风 signature Zhang Weijia. Citra angsa sekejap dan melodi mabuk — aksen anggun di set toko.',
      'hi_IN' => 'झांग वेइजिया का सिग्नेचर गुफ़ेंग। क्षणभंगुर हंस छवि और मदमस्त धुन — स्टोर सेट में सुंदर हाईलाइट।',
      'bn_BD' => 'ঝাং ওয়েইজিয়ার সিগনেচার গুফেং। ক্ষণস্থায়ী রাজহাঁসের চিত্র ও মাতাল সুর — দোকান সেটে কোমল হাইলাইট।',
      'ur_PK' => 'ژانگ وی جیا کا سگنیچر قدیم چینی گانا۔ پل بھر قو کی تصویر اور مست نغمہ — دکان سیٹ میں خوبصورت نمایاں۔',
      'default' => 'Zhang Weijia’s signature 古风. Fleeting-swan imagery and tipsy melody — a graceful highlight in the store set.',
    ),
  ),
  12 => 
  array (
    'url' => '/media/websites/default/default/store-music/戏腔-下个渡口等你.mp3',
    'title' => '戏腔-下个渡口等你',
    'intro' => 
    array (
      'zh_Hans_CN' => '戏腔风古风流行。渡口相约意象与戏腔色彩，店面需要“戏味”时很出彩。',
      'zh_Hant_TW' => '戲腔風古風流行。渡口相約意象與戲腔色彩，店舖需要「戲味」時很出彩。',
      'en_US' => 'Opera-crossover 古风 pop. Ferry-crossing rendezvous imagery with theatrical colour — pops when the store wants “戏味”.',
      'ja_JP' => '戯腔風の古風ポップ。渡し場で待つイメージと戯腔の色。店舗に「芝居味」が欲しいとき映える。',
      'ko_KR' => '희강풍 고풍 팝. 나루터 약속 이미지와 희강 색채 — 매장에 ‘희미’가 필요할 때 빛남.',
      'fr_FR' => 'Pop 古风 croisé opéra. Image de rendez-vous au bac, couleur théâtrale — brille quand la boutique veut du « 戏味 ».',
      'de_DE' => 'Opern-Crossover-古风-Pop. Fähr-Rendezvous und theatralische Farbe — stark, wenn der Laden „戏味“ will.',
      'es_ES' => 'Pop 古风 de cruce con ópera. Cita en el embarcadero y color teatral: brilla cuando la tienda quiere «戏味».',
      'pt_BR' => 'Pop 古风 crossover com ópera. Encontro no cais e cor teatral — brilha quando a loja quer “戏味”.',
      'ru_RU' => 'Поп-古风 с оперным кроссовером. Встреча у переправы и театральный колорит — ярко, когда магазину нужен «戏味».',
      'ar_SA' => 'بوب غوفنغ بمزج الأوبرا. صورة موعد عند المعبر ولون مسرحي — يبرز حين يريد المتجر طابع المسرح.',
      'th_TH' => 'กู่เฟิงป็อปแนวเสียงงิ้ว นัดพบที่ท่าข้ามและสีละคร — เด่นเมื่อร้านต้องการกลิ่นละคร',
      'vi_VN' => 'Cổ phong pop phong hí khang. Hẹn ở bến đò và sắc hí khang — nổi bật khi cửa hàng cần “hí vị”.',
      'id_ID' => 'Pop 古风 crossover opera. Citra janji di pelabuhan penyeberangan dan warna teatrikal — menonjol saat toko butuh “戏味”.',
      'hi_IN' => 'ऑपेरा-क्रॉसओवर गुफ़ेंग पॉप। घाट पर मिलन और नाटकीय रंग — जब दुकान को «戏味» चाहिए।',
      'bn_BD' => 'অপেরা-ক্রসওভার গুফেং পপ। ঘাটে সাক্ষাৎ ও নাটকীয় রং — যখন দোকানে «戏味» দরকার।',
      'ur_PK' => 'اوپرا کراس اوور قدیم چینی پاپ۔ گھاٹ پر ملاقات اور ڈرامائی رنگ — جب دکان کو «戏味» چاہیے۔',
      'default' => 'Opera-crossover 古风 pop. Ferry-crossing rendezvous imagery with theatrical colour — pops when the store wants “戏味”.',
    ),
  ),
  13 => 
  array (
    'url' => '/media/websites/default/default/store-music/周深-大鱼Piano.mp3',
    'title' => '周深-大鱼Piano',
    'intro' => 
    array (
      'zh_Hans_CN' => '《大鱼》钢琴器乐版。保留主题旋律的空灵感，无歌词，更适合长时间店面背景循环。',
      'zh_Hant_TW' => '《大魚》鋼琴器樂版。保留主題旋律的空靈感，無歌詞，更適合長時間店舖背景循環。',
      'en_US' => 'Piano instrumental of “Big Fish”. Keeps the ethereal theme without lyrics — better for long storefront background loops.',
      'ja_JP' => '『大魚』ピアノ器楽版。主題の透明感を残し歌詞なし。長時間の店舗BGMに向き。',
      'ko_KR' => '《대어》 피아노 기악 버전. 몽환 테마를 가사 없이 유지 — 긴 매장 배경 루프에 적합.',
      'fr_FR' => 'Version piano instrumentale de « Big Fish ». Thème éthéré sans paroles — mieux pour de longues boucles boutique.',
      'de_DE' => 'Piano-Instrumental von „Big Fish“. Ätherisches Thema ohne Text — gut für lange Laden-Hintergrund-Loops.',
      'es_ES' => 'Versión piano instrumental de «Big Fish». Tema etéreo sin letra: ideal para bucles largos de fondo en tienda.',
      'pt_BR' => 'Versão piano instrumental de “Big Fish”. Tema etéreo sem letra — ótima para loops longos de fundo na loja.',
      'ru_RU' => 'Фортепианная инструментальная версия «Большой рыбы». Эфирная тема без слов — лучше для длинных фоновых петель магазина.',
      'ar_SA' => 'نسخة بيانو آلية من «السمكة الكبيرة». موضوع أثيري بلا كلمات — أنسب لتكرار خلفية المتجر طويلاً.',
      'th_TH' => 'เวอร์ชันเปียโนอินสตรูเมนทัลของ《ต้าอวี๋》 คงธีมใสไม่มีเนื้อร้อง — เหมาะวนยาวเป็น BGM ร้าน',
      'vi_VN' => 'Bản piano không lời của «Đại Ngư». Giữ giai điệu hư ảo — hợp vòng lặp nền cửa hàng lâu.',
      'id_ID' => 'Versi piano instrumental “Big Fish”. Tema eterik tanpa lirik — cocok loop latar toko lama.',
      'hi_IN' => '«बिग फिश» का पियानो इंस्ट्रूमेंटल। बिना बोलों के स्वप्निल थीम — लंबे स्टोर बैकग्राउंड लूप के लिए बेहतर।',
      'bn_BD' => '«বিগ ফিশ»-এর পিয়ানো ইনস্ট্রুমেন্টাল। গীতহীন স্বপ্নময় থিম — দীর্ঘ দোকান ব্যাকগ্রাউন্ড লুপের জন্য ভালো।',
      'ur_PK' => '«بگ فش» کا پیانو انسٹرومنٹل۔ بغیر بول کے خوابیدہ تھیم — طویل دکان بیک گراؤنڈ لوپ کے لیے بہتر۔',
      'default' => 'Piano instrumental of “Big Fish”. Keeps the ethereal theme without lyrics — better for long storefront background loops.',
    ),
  ),
  14 => 
  array (
    'url' => '/media/websites/default/default/store-music/古风-戏子唱罢.mp3',
    'title' => '古风-戏子唱罢',
    'intro' => 
    array (
      'zh_Hans_CN' => '戏子意象古风曲。唱罢落幕的余韵感强，适合店面收尾或偏叙事的时段。',
      'zh_Hant_TW' => '戲子意象古風曲。唱罷落幕的餘韻感強，適合店舖收尾或偏敘事的時段。',
      'en_US' => '古风 track with performer imagery. Strong aftertaste of curtain-fall — good for closing or story-leaning store moments.',
      'ja_JP' => '役者イメージの古風曲。幕が下りた余韻が強い。店舗の締めや物語寄り時間帯に。',
      'ko_KR' => '광대 이미지 고풍곡. 막이 내린 여운이 강함 — 매장 마무리·서사 구간에 적합.',
      'fr_FR' => 'Titre 古风 à l’image du comédien. Fort arrière-goût de rideau — bon pour clôturer ou moments narratifs boutique.',
      'de_DE' => '古风-Track mit Schauspieler-Bild. Starker Nachklang des Vorhangs — gut zum Abschluss oder narrativen Ladenmomenten.',
      'es_ES' => 'Pista 古风 con imagen de actor. Fuerte posgusto de telón: buena para cierre o momentos narrativos de tienda.',
      'pt_BR' => 'Faixa 古风 com imagem de ator. Forte ressaibo de cortina — boa para fechamento ou momentos narrativos na loja.',
      'ru_RU' => '古风-трек с образом актёра. Сильный привкус опущенного занавеса — хорош для финала или сюжетных моментов магазина.',
      'ar_SA' => 'مقطوعة غوفنغ بصورة الممثل. مذاق قوي لنهاية الستار — مناسبة للإغلاق أو اللحظات السردية في المتجر.',
      'th_TH' => 'เพลงกู่เฟิงภาพนักแสดง รสท้ายหลังม่านปิดเข้ม — เหมาะปิดเซ็ตหรือช่วงเล่าเรื่องในร้าน',
      'vi_VN' => 'Ca khúc cổ phong hình ảnh hí tử. Dư vị hạ màn mạnh — hợp kết set hoặc khung giờ nghiêng kể chuyện.',
      'id_ID' => 'Trek 古风 dengan citra pemain. Aftertaste tirai turun kuat — cocok penutup atau momen naratif toko.',
      'hi_IN' => 'कलाकार छवि वाला गुफ़ेंग ट्रैक। पर्दा गिरने का गहरा असर — स्टोर समापन या कथा-क्षणों के लिए।',
      'bn_BD' => 'অভিনেতা চিত্রের গুফেং ট্র্যাক। পর্দা নামার গভীর আফটারটেস্ট — দোকান সমাপ্তি বা কাহিনি মুহূর্তে।',
      'ur_PK' => 'اداکار کی تصویر والا قدیم چینی ٹریک۔ پردہ گرنے کا گہرا اثر — دکان بند یا بیانی لمحوں کے لیے۔',
      'default' => '古风 track with performer imagery. Strong aftertaste of curtain-fall — good for closing or story-leaning store moments.',
    ),
  ),
  15 => 
  array (
    'url' => '/media/websites/default/default/store-music/古风-花亦山.mp3',
    'title' => '古风-花亦山',
    'intro' => 
    array (
      'zh_Hans_CN' => '山花意象古风曲。清新延绵，适合店面需要柔和国风底噪而不抢话的时候。',
      'zh_Hant_TW' => '山花意象古風曲。清新延綿，適合店舖需要柔和國風底噪而不搶話的時候。',
      'en_US' => '古风 track with mountain-flower imagery. Fresh and lingering — soft guofeng bed that won’t overpower talk in-store.',
      'ja_JP' => '山花イメージの古風曲。爽やかで余韻がある。店舗で話し声を邪魔しない柔らかい国風ベッドに。',
      'ko_KR' => '산화 이미지 고풍곡. 상쾌하고 여운 있음 — 매장 대화를 덮지 않는 부드러운 국풍 베드.',
      'fr_FR' => 'Titre 古风 à l’image des fleurs de montagne. Frais et durable — lit guofeng doux qui n’écrase pas la conversation.',
      'de_DE' => '古风-Track mit Bergblumen-Bild. Frisch und nachhaltig — weiches Guofeng-Bett, das Gespräche nicht überdeckt.',
      'es_ES' => 'Pista 古风 con imagen de flores de montaña. Fresca y duradera: cama guofeng suave que no tapa la conversación.',
      'pt_BR' => 'Faixa 古风 com imagem de flores de montanha. Fresca e persistente — cama guofeng suave que não cobre a conversa.',
      'ru_RU' => '古风-трек с образом горных цветов. Свежий и протяжный — мягкий гуофэн-фон, не перекрывающий разговор.',
      'ar_SA' => 'مقطوعة غوفنغ بصورة زهور الجبل. منعشة ومتدة — طبقة غوفنغ ناعمة لا تطغى على الحديث في المتجر.',
      'th_TH' => 'เพลงกู่เฟิงภาพดอกเขา สดชื่นยาว — เบดกั๋วเฟิงนุ่มไม่กลบเสียงคุยในร้าน',
      'vi_VN' => 'Ca khúc cổ phong hình ảnh hoa núi. Trong trẻo, kéo dài — lớp quốc phong mềm không át lời trong cửa hàng.',
      'id_ID' => 'Trek 古风 dengan citra bunga gunung. Segar dan bertahan — bed guofeng lembut yang tidak menenggelamkan percakapan.',
      'hi_IN' => 'पहाड़ी फूल छवि वाला गुफ़ेंग ट्रैक। ताज़ा और लंबा — नरम गुओफेंग बेड जो बातचीत को न दबे।',
      'bn_BD' => 'পাহাড়ি ফুল চিত্রের গুফেং ট্র্যাক। সতেজ ও দীর্ঘস্থায়ী — নরম গুওফেং বেড যা কথোপকথন ঢাকে না।',
      'ur_PK' => 'پہاڑی پھول کی تصویر والا قدیم چینی ٹریک۔ تازہ اور دیرپا — نرم گوؤفینگ بیڈ جو بات چیت نہ دبائے۔',
      'default' => '古风 track with mountain-flower imagery. Fresh and lingering — soft guofeng bed that won’t overpower talk in-store.',
    ),
  ),
  16 => 
  array (
    'url' => '/media/websites/default/default/store-music/古风-不染长安.mp3',
    'title' => '古风-不染长安',
    'intro' => 
    array (
      'zh_Hans_CN' => '长安意象古风曲。不染尘嚣的清冷气质，适合店面需要一点“古都空镜”感的时候。',
      'zh_Hant_TW' => '長安意象古風曲。不染塵囂的清冷氣質，適合店舖需要一點「古都空鏡」感的時候。',
      'en_US' => '古风 track with Chang’an imagery. Untainted, cool clarity — for moments when the store wants an “ancient capital empty shot” feel.',
      'ja_JP' => '長安イメージの古風曲。俗塵に染まらない清涼さ。店舗に「古都の空撮」感が欲しいときに。',
      'ko_KR' => '장안 이미지 고풍곡. 세속에 물들지 않은 청량함 — 매장에 ‘고도 공경’ 느낌이 필요할 때.',
      'fr_FR' => 'Titre 古风 à l’image de Chang’an. Fraîcheur immaculée — quand la boutique veut un plan vide de capitale antique.',
      'de_DE' => '古风-Track mit Chang’an-Bild. Unberührt und kühl klar — wenn der Laden „Leeraufnahme der alten Hauptstadt“ will.',
      'es_ES' => 'Pista 古风 con imagen de Chang’an. Claridad intacta: cuando la tienda quiere un plano vacío de capital antigua.',
      'pt_BR' => 'Faixa 古风 com imagem de Chang’an. Clareza intocada — quando a loja quer um “plano vazio de capital antiga”.',
      'ru_RU' => '古风-трек с образом Чанъаня. Незапятнанная прохлада — когда магазину нужен «пустой кадр древней столицы».',
      'ar_SA' => 'مقطوعة غوفنغ بصورة تشانغآن. صفاء لم يتلطخ — حين يريد المتجر إحساس لقطة فارغة لعاصمة قديمة.',
      'th_TH' => 'เพลงกู่เฟิงภาพฉางอัน เย็นใสไม่ปนฝุ่น — เวลาที่ร้านต้องการฟีล “ช็อตว่างนครโบราณ”',
      'vi_VN' => 'Ca khúc cổ phong hình ảnh Trường An. Trong lạnh không nhiễm trần — khi cửa hàng cần cảm giác “cảnh trống cố đô”.',
      'id_ID' => 'Trek 古风 dengan citra Chang’an. Jernih tak ternoda — saat toko ingin rasa “shot kosong ibu kota kuno”.',
      'hi_IN' => 'चांगआन छवि वाला गुफ़ेंग ट्रैक। अछूती ठंडी स्पष्टता — जब दुकान को «प्राचीन राजधानी खाली शॉट» चाहिए।',
      'bn_BD' => 'চাংআন চিত্রের গুফেং ট্র্যাক। অকলুষিত শীতল স্বচ্ছতা — যখন দোকানে «প্রাচীন রাজধানীর খালি শট» দরকার।',
      'ur_PK' => 'چانگ آن کی تصویر والا قدیم چینی ٹریک۔ بے داغ ٹھنڈی صفائی — جب دکان کو «قدیم دارالحکومت کا خالی شاٹ» چاہیے۔',
      'default' => '古风 track with Chang’an imagery. Untainted, cool clarity — for moments when the store wants an “ancient capital empty shot” feel.',
    ),
  ),
  17 => 
  array (
    'url' => '/media/websites/default/default/store-music/温柔的人-孤城雨.mp3',
    'title' => '温柔的人-孤城雨',
    'intro' => 
    array (
      'zh_Hans_CN' => '温柔的人《孤城雨》。孤城遇雨的柔情编曲，与洛先生《孤城》同题异曲，适合偏安静的店面时段。',
      'zh_Hant_TW' => '溫柔的人《孤城雨》。孤城遇雨的柔情編曲，與洛先生《孤城》同題異曲，適合偏安靜的店舖時段。',
      'en_US' => 'Wenrou De Ren “Gu Cheng Yu”. Soft rain-over-lonely-city production — same theme family as Luo’s “Gu Cheng”, quieter store slots.',
      'ja_JP' => '温柔的人『孤城雨』。孤城に雨の柔らかい編曲。洛先生『孤城』と同題異曲。静かな店舗時間帯向き。',
      'ko_KR' => '원러우더런 《고성우》. 외로운 성에 비 내리는 편곡 — 뤄 《고성》과 동제 이곡, 조용한 매장 구간용.',
      'fr_FR' => 'Wenrou De Ren « Gu Cheng Yu ». Pluie douce sur cité solitaire — même thème que « Gu Cheng » de Luo, créneaux plus calmes.',
      'de_DE' => 'Wenrou De Ren „Gu Cheng Yu“. Sanfter Regen über einsamer Stadt — gleiches Themenfeld wie Luos „Gu Cheng“, ruhigere Ladenzeiten.',
      'es_ES' => 'Wenrou De Ren «Gu Cheng Yu». Lluvia suave sobre ciudad solitaria: misma familia temática que «Gu Cheng» de Luo, tramos más quietos.',
      'pt_BR' => 'Wenrou De Ren “Gu Cheng Yu”. Chuva suave sobre cidade solitária — mesma família temática de “Gu Cheng” de Luo, horários mais quietos.',
      'ru_RU' => 'Вэньжоу Дэ Жэнь «Гу Чэн Юй». Мягкий дождь над одиноким городом — та же тема, что у Ло «Гу Чэн», более тихие слоты магазина.',
      'ar_SA' => 'ونرو دي رن «غو تشنغ يو». مطر ناعم على مدينة وحيدة — نفس عائلة موضوع «غو تشنغ» للو، لأوقات المتجر الأكثر هدوءًا.',
      'th_TH' => 'เหวินโหรวเตอเหริน《孤城雨》 ฝนอ่อนเหนือเมืองโดดเดี่ยว — ธีมเดียวกับ《孤城》ของลั่ว แต่เงียบกว่าสำหรับร้าน',
      'vi_VN' => 'Ôn Nhu Đích Nhân «Cô Thành Vũ». Mưa mềm trên cô thành — cùng đề khác khúc với «Cô Thành» của Lạc, khung giờ yên hơn.',
      'id_ID' => 'Wenrou De Ren “Gu Cheng Yu”. Hujan lembut di atas kota sunyi — keluarga tema sama dengan “Gu Cheng” Luo, slot toko lebih tenang.',
      'hi_IN' => 'वेनरोउ दे रेन «गू चेंग यू»। अकेले शहर पर नरम बारिश — लुओ के «गू चेंग» जैसा विषय, शांत स्टोर स्लॉट।',
      'bn_BD' => 'ওয়েনরোউ দে রেন «গু চেং ইউ»। নিঃসঙ্গ শহরে নরম বৃষ্টি — লুও-এর «গু চেং»-এর একই থিম পরিবার, শান্ত দোকান স্লট।',
      'ur_PK' => 'وین رو دے رن «گو چینگ یو»۔ تنہا شہر پر نرم بارش — لؤو کے «گو چینگ» جیسا موضوع، پرسکون دکان سلاٹ۔',
      'default' => 'Wenrou De Ren “Gu Cheng Yu”. Soft rain-over-lonely-city production — same theme family as Luo’s “Gu Cheng”, quieter store slots.',
    ),
  ),
  18 => 
  array (
    'url' => '/media/websites/default/default/store-music/二胡版-葬花吟.mp3',
    'title' => '二胡版-葬花吟',
    'intro' => 
    array (
      'zh_Hans_CN' => '《红楼梦》名篇《葬花吟》二胡演绎。黛玉葬花的悲悯空灵，适合店面偏静谧、文人气的古风氛围。',
      'zh_Hant_TW' => '《紅樓夢》名篇《葬花吟》二胡演繹。黛玉葬花的悲憫空靈，適合店舖偏靜謐、文人氣的古風氛圍。',
      'en_US' => 'Erhu rendering of Dream of the Red Chamber’s “Song of Burying Flowers”. Daiyu’s mournful, ethereal tone — quiet literati 古风 for calmer store moments.',
      'ja_JP' => '『紅楼夢』の名篇「葬花吟」の二胡演奏。黛玉の花葬の哀しみと空霊さ。静かな文人気の古風な店舗雰囲気に。',
      'ko_KR' => '『홍루몽』 명편 《장화음》 얼후 연주. 대옥의 꽃 묻기 애잔함과 몽환감 — 고요한 문인풍 고풍 매장 분위기용.',
      'fr_FR' => 'Version erhu du « Chant d’enterrer les fleurs » du Rêve du pavillon rouge. Douleur éthérée de Daiyu — 古风 lettré pour moments plus calmes en boutique.',
      'de_DE' => 'Erhu-Fassung von „Lied vom Blumenbegraben“ aus dem Traum der Roten Kammer. Daiyus schwermütige Ätherik — literatisches 古风 für ruhigere Ladenzeiten.',
      'es_ES' => 'Versión de erhu de la «Canción de enterrar flores» del Sueño del pabellón rojo. Lamento etéreo de Daiyu: 古风 literario para tramos más quietos.',
      'pt_BR' => 'Versão de erhu da “Canção de enterrar flores” do Sonho do Pavilhão Vermelho. Lamento etéreo de Daiyu — 古风 literário para horários mais quietos.',
      'ru_RU' => 'Эрху-версия «Песни о погребении цветов» из Сна в красном тереме. Скорбная воздушная тональность Дайюй — литературный 古风 для более тихих часов магазина.',
      'ar_SA' => 'نسخة إرهو من «أنشودة دفن الزهور» من حلم الجناح الأحمر. حزن داييو الأثيري — أجواء غوفنغ أدبية لأوقات المتجر الأكثر هدوءًا.',
      'th_TH' => 'เวอร์ชันเอ้อหูจาก《葬花吟》ในความฝันในหอแดง ความโศกและโปร่งใสของไต้ยู่ — กู่เฟิงแนววรรณกรรมสำหรับช่วงร้านที่เงียบกว่า',
      'vi_VN' => 'Bản nhị hồ «Táng Hoa Ngâm» từ Hồng Lâu Mộng. Bi thương hư ảo của Đại Ngọc — cổ phong văn nhân cho khung giờ yên hơn.',
      'id_ID' => 'Versi erhu “Nyanyian Mengubur Bunga” dari Mimpi Paviliun Merah. Kesedihan eterik Daiyu — 古风 literati untuk slot toko lebih tenang.',
      'hi_IN' => 'लाल मंडप के स्वप्न की «फूल दफ़नाने की कविता» का एरहू संस्करण। दायू का शोकपूर्ण स्वप्निल स्वर — शांत स्टोर के लिए साहित्यिक गुफ़ेंग।',
      'bn_BD' => 'লাল মণ্ডপের স্বপ্নের «ফুল পোতার গান»-এর এরহু রূপ। দাইয়ুর শোকাবহ স্বপ্নময় সুর — শান্ত দোকানের জন্য সাহিত্যিক গুফেং।',
      'ur_PK' => 'سرخ ایوان کے خواب کی «پھول دفن کرنے کی نظم» کا ایرہو ورژن۔ دائی یو کی غمگین خوابیدہ لہجہ — پرسکون دکان کے لیے ادبی قدیم چینی ماحول۔',
      'default' => 'Erhu rendering of Dream of the Red Chamber’s “Song of Burying Flowers”. Daiyu’s mournful, ethereal tone — quiet literati 古风 for calmer store moments.',
    ),
  ),
);
