<?php

return [
    'Weline_Seo::domain::subject_created' => [
        'name' => __('SEO subject created'),
        'description' => __('Dispatched when an SEO subject is created.'),
        'doc' => 'domain/subject_created.md',
        'version' => '1.0.0',
        'type' => 'domain',
        'data_contract' => [
            'subject_id' => ['type' => 'integer', 'required' => true, 'description' => 'SEO subject ID'],
            'subject_type' => ['type' => 'string', 'required' => true, 'description' => 'Subject type'],
            'subject_entity_id' => ['type' => 'integer', 'required' => true, 'description' => 'Subject entity ID'],
            'url' => ['type' => 'string', 'required' => false, 'description' => 'URL'],
            'title' => ['type' => 'string', 'required' => false, 'description' => 'Title'],
            'description' => ['type' => 'string', 'required' => false, 'description' => 'Description'],
        ],
    ],
    'Weline_Seo::domain::subject_updated' => [
        'name' => __('SEO subject updated'),
        'description' => __('Dispatched when SEO subject data is updated.'),
        'doc' => 'domain/subject_updated.md',
        'version' => '1.0.0',
        'type' => 'domain',
        'data_contract' => [
            'subject_id' => ['type' => 'integer', 'required' => true, 'description' => 'SEO subject ID'],
            'subject_type' => ['type' => 'string', 'required' => true, 'description' => 'Subject type'],
            'changes' => ['type' => 'array', 'required' => false, 'description' => 'Changed fields'],
        ],
    ],
    'Weline_Seo::domain::keywords_extracted' => [
        'name' => __('SEO keywords extracted'),
        'description' => __('Dispatched when keyword extraction is completed.'),
        'doc' => 'domain/keywords_extracted.md',
        'version' => '1.0.0',
        'type' => 'domain',
        'data_contract' => [
            'subject_id' => ['type' => 'integer', 'required' => true, 'description' => 'SEO subject ID'],
            'keywords' => ['type' => 'array', 'required' => true, 'description' => 'Extracted keywords'],
            'source' => ['type' => 'string', 'required' => true, 'description' => 'Keyword source'],
        ],
    ],
    'Weline_Seo::domain::suggestion_generated' => [
        'name' => __('SEO suggestion generated'),
        'description' => __('Dispatched when AI SEO suggestions are generated.'),
        'doc' => 'domain/suggestion_generated.md',
        'version' => '1.0.0',
        'type' => 'domain',
        'data_contract' => [
            'subject_id' => ['type' => 'integer', 'required' => true, 'description' => 'SEO subject ID'],
            'suggestion_id' => ['type' => 'integer', 'required' => true, 'description' => 'Suggestion ID'],
            'keywords' => ['type' => 'array', 'required' => false, 'description' => 'Suggested keywords'],
            'content' => ['type' => 'array', 'required' => false, 'description' => 'Suggestion content'],
        ],
    ],
    'Weline_Seo::domain::website_account_bind' => [
        'name' => __('Website SEO account bound'),
        'description' => __('Dispatched when a website is bound to an SEO account.'),
        'doc' => 'domain/website_account_bind.md',
        'version' => '1.0.0',
        'type' => 'domain',
        'data_contract' => [
            'website_id' => ['type' => 'integer', 'required' => true, 'description' => 'Website ID'],
            'account_id' => ['type' => 'integer', 'required' => true, 'description' => 'SEO account ID'],
            'is_auto_submit' => ['type' => 'boolean', 'required' => false, 'description' => 'Whether sitemap auto submit is enabled'],
        ],
    ],
    'Weline_Seo::integration::feed_collect' => [
        'name' => __('SEO feed collect'),
        'description' => __('Allows other modules to provide SEO feed data.'),
        'doc' => 'integration/feed_collect.md',
        'version' => '1.0.0',
        'type' => 'integration',
        'data_contract' => [
            'subject_type' => ['type' => 'string', 'required' => true, 'description' => 'Subject type'],
            'subject_id' => ['type' => 'integer', 'required' => true, 'description' => 'Subject ID'],
            'feed_data' => ['type' => 'array', 'required' => true, 'description' => 'Feed data'],
        ],
    ],
    'Weline_Seo::integration::head_context_resolve' => [
        'name' => __('SEO head context resolve'),
        'description' => __('Allows other modules to enrich page-level SEO head context before profile providers merge.'),
        'doc' => 'integration/head_context_resolve.md',
        'version' => '1.0.0',
        'type' => 'integration',
        'data_contract' => [
            'template' => ['type' => 'mixed', 'required' => false, 'description' => 'Current template object'],
            'context' => ['type' => 'array', 'required' => false, 'description' => 'Resolved SEO context so far'],
            'head_context' => ['type' => 'array', 'required' => false, 'description' => 'Additional head context to merge'],
        ],
    ],
    'Weline_Seo::integration::url_submit_request' => [
        'name' => __('SEO URL submit request'),
        'description' => __('Allows modules to enqueue changed public URLs for immediate search engine URL push.'),
        'doc' => 'integration/url_submit_request.md',
        'version' => '1.0.0',
        'type' => 'integration',
        'data_contract' => [
            'url' => ['type' => 'string', 'required' => false, 'description' => 'Single changed public URL'],
            'urls' => ['type' => 'array', 'required' => false, 'description' => 'Changed public URL list'],
            'targets' => ['type' => 'array', 'required' => false, 'description' => 'Website-scoped URL targets: website_id, url, previous_url, url_key'],
            'scope' => ['type' => 'string', 'required' => true, 'description' => 'Business scope, such as product, category, page, blog'],
            'website_id' => ['type' => 'integer', 'required' => false, 'description' => 'Website ID'],
            'website_ids' => ['type' => 'array', 'required' => false, 'description' => 'Website IDs for multi-site URL assets'],
            'module' => ['type' => 'string', 'required' => false, 'description' => 'Source module'],
            'subject_type' => ['type' => 'string', 'required' => false, 'description' => 'Business entity type'],
            'subject_id' => ['type' => 'integer', 'required' => false, 'description' => 'Business entity ID'],
            'action' => ['type' => 'string', 'required' => false, 'description' => 'Change action: upsert, delete, publish, unpublish'],
        ],
    ],
    'Weline_Seo::integration::url_changed' => [
        'name' => __('SEO URL changed'),
        'description' => __('Unified URL change notification before SEO decides sitemap sync and URL push tasks.'),
        'doc' => 'integration/url_changed.md',
        'version' => '1.0.0',
        'type' => 'integration',
        'data_contract' => [
            'targets' => ['type' => 'array', 'required' => false, 'description' => 'Website-scoped URL targets; preferred multi-site payload'],
            'url' => ['type' => 'string', 'required' => false, 'description' => 'Changed public URL when targets are not provided'],
            'previous_url' => ['type' => 'string', 'required' => false, 'description' => 'Previous public URL'],
            'url_key' => ['type' => 'string', 'required' => false, 'description' => 'Stable URL asset key inside website + scope + module'],
            'scope' => ['type' => 'string', 'required' => true, 'description' => 'Business scope'],
            'module' => ['type' => 'string', 'required' => true, 'description' => 'Source module'],
            'website_id' => ['type' => 'integer', 'required' => false, 'description' => 'Website ID'],
            'website_ids' => ['type' => 'array', 'required' => false, 'description' => 'Website IDs when the same business entity belongs to multiple websites'],
            'subject_type' => ['type' => 'string', 'required' => false, 'description' => 'Business entity type'],
            'subject_id' => ['type' => 'integer', 'required' => false, 'description' => 'Business entity ID'],
            'action' => ['type' => 'string', 'required' => true, 'description' => 'upsert, publish, unpublish, delete, draft'],
            'is_local_url' => ['type' => 'boolean', 'required' => false, 'description' => 'Whether URL is local/private/dev host'],
            'local_reason' => ['type' => 'string', 'required' => false, 'description' => 'Local URL reason'],
        ],
    ],
    'Weline_Seo::integration::url_change_processed' => [
        'name' => __('SEO URL change processed'),
        'description' => __('Dispatched after URL change notification has been mapped to sitemap sync and URL push decisions.'),
        'doc' => 'integration/url_change_processed.md',
        'version' => '1.0.0',
        'type' => 'integration',
        'data_contract' => [
            'url' => ['type' => 'string', 'required' => true, 'description' => 'Changed public URL'],
            'action' => ['type' => 'string', 'required' => true, 'description' => 'Change action'],
            'result' => ['type' => 'array', 'required' => true, 'description' => 'Processing result'],
        ],
    ],
    'Weline_Seo::integration::task_enqueued' => [
        'name' => __('SEO task enqueued'),
        'description' => __('Dispatched after an SEO task is enqueued.'),
        'doc' => 'integration/task_enqueued.md',
        'version' => '1.0.0',
        'type' => 'integration',
        'data_contract' => [
            'task_id' => ['type' => 'integer', 'required' => true, 'description' => 'Task ID'],
            'task_type' => ['type' => 'string', 'required' => true, 'description' => 'Task type'],
            'subject_type' => ['type' => 'string', 'required' => true, 'description' => 'Subject type'],
            'subject_id' => ['type' => 'integer', 'required' => true, 'description' => 'Subject ID'],
        ],
    ],
    'Weline_Seo::integration::task_completed' => [
        'name' => __('SEO task completed'),
        'description' => __('Dispatched after an SEO task is completed.'),
        'doc' => 'integration/task_completed.md',
        'version' => '1.0.0',
        'type' => 'integration',
        'data_contract' => [
            'task_id' => ['type' => 'integer', 'required' => true, 'description' => 'Task ID'],
            'task_type' => ['type' => 'string', 'required' => true, 'description' => 'Task type'],
            'status' => ['type' => 'string', 'required' => true, 'description' => 'Task status'],
            'result' => ['type' => 'mixed', 'required' => false, 'description' => 'Task result'],
        ],
    ],
    'Weline_Seo::application::trend_sync_completed' => [
        'name' => __('SEO trend sync completed'),
        'description' => __('Dispatched when trend data sync is completed.'),
        'doc' => 'application/trend_sync_completed.md',
        'version' => '1.0.0',
        'type' => 'application',
        'data_contract' => [
            'platform' => ['type' => 'string', 'required' => true, 'description' => 'Platform code'],
            'keyword_count' => ['type' => 'integer', 'required' => true, 'description' => 'Processed keyword count'],
            'trend_count' => ['type' => 'integer', 'required' => true, 'description' => 'Saved trend count'],
            'error_count' => ['type' => 'integer', 'required' => false, 'description' => 'Error count'],
        ],
    ],
];
