<?php
/**
 * 查看日志数据 - 内容模板
 * @var \Weline\Framework\View\Template $this
 */
?>
<div class="w-grid">
    <template>Weline_Component::message.phtml</template>
</div>

<div class="w-grid">
    <div style="--w-span:12;">
        <div class="w-card">
            <div class="w-card__body">
                <h4 class="w-card__title">
                    <lang>查看数据</lang>
                </h4>
                <p class="w-text" data-tone="muted">
                    <lang>查看日志数据</lang>
                </p>
                <pre class="w-text" data-tone="muted">{{data}}</pre>
            </div>
        </div>
    </div>
</div>
