<?php
/**@var \Weline\Framework\View\Template $this */
?>
<!-- start page title -->
<div class='row'>
    <div class='col-12'>
        <div class='page-title-box d-sm-flex align-items-center justify-content-between'>
            <h4 class='mb-sm-0'>
                <lang>i18n国际化>国家>地区</lang>
            </h4>

            <div class='page-title-right'>
                <ol class='breadcrumb m-0'>
                    <li class='breadcrumb-item'><a href='javascript: void(0);'>
                            <lang>系统配置</lang>
                        </a></li>
                    <li class='breadcrumb-item active'>
                        <lang>i18n国际化</lang>
                    </li>
                    <li class='breadcrumb-item active'>
                        <lang>国家</lang>
                    </li>
                    <li class='breadcrumb-item active'>
                        <lang>地区</lang>
                    </li>
                </ol>
            </div>

        </div>
    </div>
</div>
<!-- end page title -->
<!-- start page message -->
<div class='row'>
    <template>Weline_Component::message.phtml</template>
</div> <!-- end message -->
<div class='row'>
    <div class='col-12'>
        <div class='card'>
            <div class='card-body'>
                <h4 class='card-title'>
                    <lang>i18n国际化国家列表</lang>
                </h4>
                <p class='card-title-desc'>
                    <lang>国际化支持：查看和安装国家.</lang>
                </p>
                <p class="card-title-desc">
                    <lang>展示语言：</lang>
                    {{target_locale.name}}（{{target_locale.code}}）
                </p>
                <p class='card-title-desc'>
                    <lang>操作：</lang>
                    <dd>req</dd>
                    <a href="@backend-url('*/backend/countries/update')?code={{req.params.code}}&country_code={{req.params.country_code}}">
                        <lang>更新</lang>
                    </a>
                    <a href="@backend-url('*/backend/countries')">
                        <lang>已安装</lang>
                    </a>
                    <a href="@backend-url('*/backend/countries')?filter=uninstalled">
                        <lang>安装国家</lang>
                    </a>
                </p>
                <div class='table-rep-plugin'>
                    <!-- search form -->
                    <div class='row'>
                        <div class='col-12'>
                            <block class='Weline\Component\Block\Form\Search'
                                   id='installed-countries-listing-search'
                                   action='*/backend/countries' method='get' keyword='search' value=''
                                   placeholder='请输入国家'></block>
                        </div>
                    </div>
                    <!-- end search form -->
                    <div class='table-responsive mb-0' data-pattern='priority-columns'>
                        <table id='tech-companies-1' class='table table-striped table-bordered'>
                            <thead>
                            <tr>
                                <th data-priority='1'><?= __('排序') ?></th>
                                <th data-priority='1'><?= __('代码') ?></th>
                                <th data-priority='3'><?= __('名称') ?></th>
                                <th data-priority='3'><?= __('国家代码') ?></th>
                                <th data-priority='3'><?= __('国家名称') ?></th>
                                <th data-priority='3'><?= __('旗帜') ?></th>
                                <th data-priority='1'><?= __('激活状态') ?></th>
                                <th data-priority='3'><?= __('是否安装') ?></th>
                                <th data-priority='3'><?= __('操作') ?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <notempty name="locales">
                                <foreach name="locales" item="locale" key="key">
                                    <tr>
                                        <td>{{key}}</td>
                                        <td class='co-name'>{{locale.code}}</td>
                                        <td class='co-name'>{{locale.name}}</td>
                                        <td class='co-name'>{{locale.country_code}}</td>
                                        <td class='co-name'>{{locale.country_name}}</td>
                                        <td class='co-name'>{{locale.flag}}</td>
                                        <td class='co-name'>{{locale.is_active}}</td>
                                        <!--                                                    <td class='co-name'>{{locale.is_install}}</td>-->
                                        <td class='co-name'>
                                            <div class="d-flex gap-2">
                                                <if condition="locale.is_active === 1">
                                                    <a class="btn btn-primary"
                                                       href="@backend-url('*/backend/countries/locales/words')?code={{locale.code}}">
                                                        <lang>词典管理</lang>
                                                    </a>
                                                    <form action="@backend-url('*/backend/countries/locales/disable')"
                                                          method='post'>
                                                        <input type='hidden' name='code'
                                                               value='{{locale.code}}'>
                                                        <input type='submit' class='btn btn-warning'
                                                               value='@lang(禁用)'>
                                                    </form>
                                                    <else/>
                                                    <form action="@backend-url('*/backend/countries/locales/active')"
                                                          method='post'>
                                                        <input type='hidden' name='code'
                                                               value='{{locale.code}}'>
                                                        <input type='submit' class='btn btn-primary'
                                                               value='@lang(启用)'>
                                                    </form>
                                                </if>
                                            </div>
                                        </td>
                                    </tr>
                                </foreach>
                            </notempty>
                            </tbody>
                        </table>
                        <empty name='locales'>
                            <lang>请</lang>
                            <a href="@backend-url('*/backend/countries/locales/install')?country_code={{req.params.country_code}}">
                                <lang>安装</lang>
                            </a>
                            <lang>地区列表</lang>
                        </empty>
                        {{pagination}}
                    </div>

                </div>

            </div>
        </div>
    </div> <!-- end col -->
</div> <!-- end row -->

<!-- jquery.mCustomScrollbar 插件 -->
<link href="@static(Weline_Admin::/libs/jquery.mCustomScrollbar/jquery.mCustomScrollbar.css)" rel="stylesheet"/>
<!-- Responsive Table css -->
<link href='@static(Weline_Admin::assets/libs/admin-resources/rwd-table/rwd-table.min.css)' rel='stylesheet' type='text/css'/>

<!-- Table Editable plugin -->
<script src="@static(Weline_Admin::assets/libs/table-edits/build/table-edits.min.js)"></script>
<script src="@static(Weline_Admin::assets/js/pages/menus/table-editable.init.js)"></script>
<script src='@static(Weline_Admin::/libs/jquery.mCustomScrollbar/jquery.mCustomScrollbar.concat.min.js)'></script>
<!-- Responsive Table js -->
<script src='@static(Weline_Admin::assets/libs/admin-resources/rwd-table/rwd-table.min.js)'></script>

<!-- Init js -->
<script src='@static(Weline_Admin::assets/js/pages/table-responsive.init.js)'></script>
