<?php
declare(strict_types=1);

$root = dirname(__DIR__, 3);
$appCode = $root . '/app/code';
$output = $root . '/dev/ai/docs/module-doc-audit-matrix.md';
$dryRun = in_array('--dry-run', $argv, true);

$modules = glob($appCode . '/*/*', GLOB_ONLYDIR) ?: [];
sort($modules);

$rows = [];
$summary = [
    'modules' => 0,
    'ai_index' => 0,
    'readme_manual' => 0,
    'readme_generated' => 0,
    'extra_docs' => 0,
    'structural_only' => 0,
    'structural_plus_docs' => 0,
];

foreach ($modules as $moduleDir) {
    $summary['modules']++;
    $vendor = basename(dirname($moduleDir));
    $module = basename($moduleDir);
    $moduleCode = $vendor . '_' . $module;

    $aiIndex = $moduleDir . '/doc/AI-INDEX.md';
    $readme = $moduleDir . '/doc/README.md';
    $hasAiIndex = is_file($aiIndex);
    $hasReadme = is_file($readme);
    $readmeGenerated = $hasReadme && str_contains((string)file_get_contents($readme), '<!-- weline:module-readme:auto-generated -->');
    $extraDocs = countDocFiles($moduleDir . '/doc');
    $surfaceCount = countSurfaces($moduleDir);
    $surfaceList = implode(', ', detectSurfaceNames($moduleDir));

    if ($hasAiIndex) {
        $summary['ai_index']++;
    }
    if ($readmeGenerated) {
        $summary['readme_generated']++;
    } elseif ($hasReadme) {
        $summary['readme_manual']++;
    }
    if ($extraDocs > 0) {
        $summary['extra_docs']++;
    }

    $status = 'manual';
    if ($readmeGenerated && $extraDocs === 0) {
        $status = 'structural_only';
        $summary['structural_only']++;
    } elseif ($readmeGenerated) {
        $status = 'structural_plus_docs';
        $summary['structural_plus_docs']++;
    }

    $rows[] = [
        'module' => $moduleCode,
        'status' => $status,
        'ai_index' => $hasAiIndex ? 'yes' : 'no',
        'readme' => $hasReadme ? ($readmeGenerated ? 'generated' : 'manual') : 'missing',
        'extra_docs' => (string)$extraDocs,
        'surfaces' => (string)$surfaceCount,
        'surface_list' => $surfaceList === '' ? '-' : $surfaceList,
    ];
}

$lines = [];
$lines[] = '# Module Doc Audit Matrix';
$lines[] = '';
$lines[] = '> Generated by `dev/ai/scripts/generate-module-doc-audit-report.php` from the current repository tree.';
$lines[] = '';
$lines[] = '## Summary';
$lines[] = '';
$lines[] = '- Modules: `' . $summary['modules'] . '`';
$lines[] = '- AI-INDEX coverage: `' . $summary['ai_index'] . '`';
$lines[] = '- Manual module README: `' . $summary['readme_manual'] . '`';
$lines[] = '- Generated module README: `' . $summary['readme_generated'] . '`';
$lines[] = '- Modules with extra doc assets beyond AI-INDEX/README: `' . $summary['extra_docs'] . '`';
$lines[] = '- Structural-only generated README: `' . $summary['structural_only'] . '`';
$lines[] = '- Structural+docs generated README: `' . $summary['structural_plus_docs'] . '`';
$lines[] = '';
$lines[] = '## Status Meaning';
$lines[] = '';
$lines[] = '- `manual`: module README is hand-written or legacy manual content.';
$lines[] = '- `structural_plus_docs`: module README is generated, but the module already has extra doc assets worth continuing to curate.';
$lines[] = '- `structural_only`: module has AI-INDEX and generated README, but no extra module docs yet.';
$lines[] = '';
$lines[] = '## Matrix';
$lines[] = '';
$lines[] = '| Module | Status | AI-INDEX | README | Extra Docs | Surfaces | Surface Names |';
$lines[] = '|---|---|---|---|---:|---:|---|';
foreach ($rows as $row) {
    $lines[] = '| ' . esc($row['module'])
        . ' | ' . esc($row['status'])
        . ' | ' . esc($row['ai_index'])
        . ' | ' . esc($row['readme'])
        . ' | ' . esc($row['extra_docs'])
        . ' | ' . esc($row['surfaces'])
        . ' | ' . esc($row['surface_list'])
        . ' |';
}
$lines[] = '';

$content = implode("\n", $lines) . "\n";
if ($dryRun) {
    echo $content;
    exit(0);
}

if (file_put_contents($output, $content) === false) {
    fwrite(STDERR, "Cannot write: {$output}\n");
    exit(1);
}

echo "written=" . rel($root, $output) . "\n";

function countDocFiles(string $docDir): int
{
    if (!is_dir($docDir)) {
        return 0;
    }
    $count = 0;
    $iterator = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($docDir, FilesystemIterator::SKIP_DOTS)
    );
    foreach ($iterator as $file) {
        if (!$file instanceof SplFileInfo || !$file->isFile()) {
            continue;
        }
        $base = $file->getBasename();
        if ($base === 'AI-INDEX.md' || $base === 'README.md') {
            continue;
        }
        if (preg_match('/\.(md|txt|json|xml|csv)$/i', $base)) {
            $count++;
        }
    }
    return $count;
}

function countSurfaces(string $moduleDir): int
{
    return count(detectSurfaceNames($moduleDir));
}

function detectSurfaceNames(string $moduleDir): array
{
    $candidates = [
        'Api', 'Block', 'Config', 'Console', 'Controller', 'Dto', 'Helper',
        'Interface', 'Model', 'Observer', 'Plugin', 'Queue', 'Schema', 'Service',
        'Setup', 'Taglib', 'Ui', 'etc', 'extends', 'i18n', 'view/blocks',
        'view/statics', 'view/templates', 'view/theme', 'view/tpl',
    ];
    $surfaces = [];
    foreach ($candidates as $candidate) {
        if (file_exists($moduleDir . '/' . $candidate)) {
            $surfaces[] = $candidate;
        }
    }
    return $surfaces;
}

function rel(string $root, string $path): string
{
    $root = rtrim(str_replace('\\', '/', $root), '/') . '/';
    $path = str_replace('\\', '/', $path);
    return str_starts_with($path, $root) ? substr($path, strlen($root)) : $path;
}

function esc(string $value): string
{
    return str_replace('|', '\\|', $value);
}
