<?php

declare(strict_types=1);

namespace Weline\Seo\Service;

use Weline\Framework\Runtime\RequestContext;
use Weline\Framework\Runtime\ScopeIdentity;

/**
 * Store mode SEO hard gate（TASK-P1D-004-SEO / TEST-P1D-03）。
 *
 * - dev/test：强制 noindex + nositemap；配置无法关闭
 * - normal（及其他）：不硬拦，走版本化/站点配置
 */
final class StoreModeSeoHardGate
{
    public const FORCED_ROBOTS_META = 'noindex,nofollow';

    public function currentStoreMode(): string
    {
        $mode = \strtolower(\trim(RequestContext::getWelineStoreMode()));
        if ($mode !== '') {
            return $mode;
        }

        return ScopeIdentity::MODE_NORMAL;
    }

    public function isHardNoIndexMode(?string $storeMode = null): bool
    {
        $mode = \strtolower(\trim((string)($storeMode ?? $this->currentStoreMode())));
        if ($mode === '') {
            $mode = ScopeIdentity::MODE_NORMAL;
        }

        return $mode === ScopeIdentity::MODE_DEV || $mode === ScopeIdentity::MODE_TEST;
    }

    public function forceRobotsTxt(): string
    {
        return \implode("\n", [
            '# Generated by Weline_Seo',
            '# Store mode hard gate: non-production (dev/test) — indexing disabled',
            'User-agent: *',
            'Disallow: /',
            '',
        ]);
    }

    /**
     * @return array{body:string,status:int}
     */
    public function forceEmptySitemap(): array
    {
        $body = '<?xml version="1.0" encoding="UTF-8"?>' . "\n"
            . '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' . "\n"
            . '<!-- Store mode hard gate: nositemap -->' . "\n"
            . '</urlset>' . "\n";

        return ['body' => $body, 'status' => 200];
    }

    /**
     * @param array<string, mixed> $context
     * @return array<string, mixed>
     */
    public function applyToPageContext(array $context, ?string $storeMode = null): array
    {
        if (!$this->isHardNoIndexMode($storeMode)) {
            return $context;
        }
        $context['robots'] = self::FORCED_ROBOTS_META;
        $context['_robots_hard_gate'] = true;
        $context['_robots_explicit'] = true;

        return $context;
    }
}
