<?php

declare(strict_types=1);

namespace Weline\Bot\Test\Unit\Service;

use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;
use Weline\Ai\Service\AiService;
use Weline\Bot\Service\RoleConfigAssistant;

class RoleConfigAssistantTest extends TestCase
{
    private RoleConfigAssistant $service;

    /** @var AiService&MockObject */
    private AiService $aiService;

    protected function setUp(): void
    {
        parent::setUp();

        $this->aiService = $this->getMockBuilder(AiService::class)
            ->disableOriginalConstructor()
            ->onlyMethods(['generate'])
            ->getMock();

        $this->service = new RoleConfigAssistant($this->aiService);
    }

    public function testBuildSuggestionFallsBackToTemplateWhenNoModel(): void
    {
        $this->aiService
            ->expects($this->never())
            ->method('generate');

        $result = $this->service->buildSuggestion(
            input: [
                'template_code' => 'general_assistant',
                'brief' => 'manage multiple projects with daily reports',
                'project_count' => 3,
            ],
            models: [],
            adapters: [
                ['code' => 'bot_agent', 'name' => 'Bot Agent'],
            ],
            skills: [
                ['code' => 'filesystem.read', 'name' => 'Read', 'category' => 'filesystem', 'is_dangerous' => 0],
                ['code' => 'http.request', 'name' => 'Http', 'category' => 'api', 'is_dangerous' => 0],
            ]
        );

        $this->assertSame('template', $result['source']);
        $this->assertSame(0, $result['draft']['model_id']);
        $this->assertNotEmpty($result['draft']['skills']);
        $this->assertNotEmpty($result['draft']['permissions']);
        $this->assertNotEmpty($result['warnings']);
    }

    public function testBuildSuggestionUsesAiDraftAndSanitizesInvalidValues(): void
    {
        $this->aiService
            ->expects($this->once())
            ->method('generate')
            ->willReturn(json_encode([
                'code' => 'role@bad#code',
                'name' => 'AI role',
                'description' => 'generated by AI',
                'system_prompt' => 'prioritize high value tasks',
                'scenario_adapter_code' => 'invalid_adapter',
                'model_id' => 999,
                'skills' => ['filesystem.read', 'not_exists'],
                'permissions' => ['fs.read:/app/*', ''],
                'model_config' => ['temperature' => 9, 'max_tokens' => -1],
                'status' => 'enabled',
                'icon' => 'mdi-robot-happy',
            ], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES));

        $result = $this->service->buildSuggestion(
            input: [
                'template_code' => 'general_assistant',
                'project_count' => 1,
                'brief' => 'coordinate project tasks',
            ],
            models: [
                ['id' => 1, 'model_code' => 'gpt-4.1-mini', 'name' => 'GPT', 'is_default' => 1],
            ],
            adapters: [
                ['code' => 'bot_agent', 'name' => 'Bot Agent'],
                ['code' => 'bot_it_ops', 'name' => 'IT Ops'],
            ],
            skills: [
                ['code' => 'filesystem.read', 'name' => 'Read', 'category' => 'filesystem', 'is_dangerous' => 0],
                ['code' => 'http.request', 'name' => 'HTTP', 'category' => 'api', 'is_dangerous' => 0],
            ]
        );

        $this->assertSame('ai', $result['source']);
        $this->assertSame('role_bad_code', $result['draft']['code']);
        $this->assertSame('bot_agent', $result['draft']['scenario_adapter_code']);
        $this->assertSame(0, $result['draft']['model_id']);
        $this->assertSame(['filesystem.read'], $result['draft']['skills']);
        $this->assertSame(0.3, $result['draft']['model_config']['temperature']);
        $this->assertSame(6144, $result['draft']['model_config']['max_tokens']);
    }

    public function testBuildSuggestionAppliesProfileWorkflowAndRiskStrategy(): void
    {
        $this->aiService
            ->expects($this->never())
            ->method('generate');

        $result = $this->service->buildSuggestion(
            input: [
                'template_code' => 'general_assistant',
                'brief' => 'operate many departments with strict approvals',
                'target_outcome' => 'daily governance summary',
                'project_count' => 40,
                'workflow_style' => 'careful',
                'risk_level' => 'safe',
                'bot_profile' => 'enterprise',
            ],
            models: [],
            adapters: [
                ['code' => 'bot_agent', 'name' => 'Bot Agent'],
            ],
            skills: [
                ['code' => 'filesystem.read', 'name' => 'Read', 'category' => 'filesystem', 'is_dangerous' => 0],
                ['code' => 'http.request', 'name' => 'Http', 'category' => 'api', 'is_dangerous' => 0],
            ]
        );

        $this->assertSame('template', $result['source']);
        $this->assertStringContainsString('Profile: Enterprise Governance.', $result['draft']['system_prompt']);
        $this->assertStringContainsString('Risk level: safe.', $result['draft']['system_prompt']);
        $this->assertGreaterThanOrEqual(8192, $result['draft']['model_config']['max_tokens']);
        $this->assertLessThanOrEqual(0.30, $result['draft']['model_config']['temperature']);
    }

    public function testTemplatesOnlyExposeAvailableSkills(): void
    {
        $templates = $this->service->getTemplates(['filesystem.read']);

        foreach ($templates as $template) {
            foreach ((array) ($template['skills'] ?? []) as $skillCode) {
                $this->assertSame('filesystem.read', $skillCode);
            }
        }
    }
}
