<?php

declare(strict_types=1);

return [
    'product-info' => [
        'name' => '产品主要信息',
        'description' => '商品详情主信息：图库、标题、SKU、价格、加购与规格详情。',
        'type' => 'product',
        'code' => 'product-info',
        'area' => 'frontend',
        'template' => 'Weline_Product::templates/frontend/widgets/product-info.phtml',
        'page_layouts' => ['product'],
        'position' => ['content'],
        'slot' => 'product-main',
        'supports' => [
            'layout-product-main',
            'product-info',
            'product-gallery',
            'product-detail',
        ],
        'default_injections' => [[
            'layout_type' => 'product',
            'layout_option' => 'default',
            'slot' => 'product-main',
            'area' => 'content',
            'sort_order' => 0,
            'required' => true,
            'reason' => '商品详情默认在产品主内容槽展示产品主要信息',
            'config' => [],
        ]],
        'params' => [],
    ],
    'related-products' => [
        'name' => '相关产品',
        'description' => '商品详情页相关推荐：读取已发布报价，排除当前商品。',
        'type' => 'product',
        'code' => 'related-products',
        'area' => 'frontend',
        'template' => 'Weline_Product::templates/frontend/widgets/related-products.phtml',
        'page_layouts' => ['product'],
        'position' => ['content'],
        'slot' => 'product-related-products',
        'supports' => [
            'layout-product-related-products',
            'related-products',
            'you-may-like',
            'product-carousel',
        ],
        'default_injections' => [[
            'layout_type' => 'product',
            'layout_option' => 'default',
            'slot' => 'product-related-products',
            'area' => 'content',
            'sort_order' => 0,
            'required' => true,
            'reason' => '商品详情默认在相关产品槽展示真实关联推荐',
            'config' => [
                'title' => '相关产品',
                'limit' => 4,
                'columns' => '4',
                'layout' => 'carousel',
            ],
        ]],
        'params' => [
            'title' => [
                'default' => '相关产品',
                'type' => 'string',
                'label' => '标题',
            ],
            'limit' => [
                'default' => 4,
                'type' => 'number',
                'label' => '显示数量',
            ],
            'columns' => [
                'default' => '4',
                'type' => 'select',
                'label' => '每行列数',
                'options' => [
                    '2' => '2列',
                    '3' => '3列',
                    '4' => '4列',
                    '5' => '5列',
                ],
            ],
            'layout' => [
                'default' => 'carousel',
                'type' => 'select',
                'label' => '布局方式',
                'options' => [
                    'grid' => '网格',
                    'carousel' => '轮播',
                ],
            ],
        ],
    ],
    'cross-sell' => [
        'name' => '经常一起购买',
        'description' => '商品详情搭配购买：当前商品 + 真实目录推荐，支持勾选合计。',
        'type' => 'product',
        'code' => 'cross-sell',
        'area' => 'frontend',
        'template' => 'Weline_Product::templates/frontend/widgets/cross-sell.phtml',
        'page_layouts' => ['product', 'cart'],
        'position' => ['content'],
        'slot' => 'product-cross-sell',
        'supports' => [
            'layout-product-cross-sell',
            'layout-cart-recommendations',
            'cross-sell',
            'up-sell',
            'product-carousel',
        ],
        'default_injections' => [
            [
                'layout_type' => 'product',
                'layout_option' => 'default',
                'slot' => 'product-cross-sell',
                'area' => 'content',
                'sort_order' => 3,
                'required' => true,
                'reason' => '商品详情默认在搭配推荐槽展示经常一起买',
                'config' => [
                    'title' => '经常一起购买',
                    'limit' => 3,
                    'show_add_all_button' => true,
                    'show_total_price' => true,
                ],
            ],
            [
                'layout_type' => 'cart',
                'layout_option' => 'default',
                'slot' => 'cart-recommendations',
                'area' => 'content',
                'sort_order' => 0,
                'required' => true,
                'reason' => '购物车默认在推荐槽展示交叉销售（非 Theme 部件，禁止布局内嵌）',
                'config' => [
                    'title' => '经常一起购买',
                    'limit' => 3,
                    'show_add_all_button' => true,
                    'show_total_price' => true,
                ],
            ],
        ],
        'params' => [
            'title' => [
                'default' => '经常一起购买',
                'type' => 'string',
                'label' => '标题',
            ],
            'limit' => [
                'default' => 3,
                'type' => 'number',
                'label' => '搭配商品数量',
            ],
            'show_add_all_button' => [
                'default' => true,
                'type' => 'bool',
                'label' => '显示一键添加按钮',
            ],
        ],
    ],
    'recommended-products' => [
        'name' => '推荐产品',
        'description' => '分类/列表推荐：读取已发布报价，网格或轮播展示。',
        'type' => 'product',
        'code' => 'recommended-products',
        'area' => 'frontend',
        'template' => 'Weline_Product::templates/frontend/widgets/recommended-products.phtml',
        'page_layouts' => ['category', 'product_list'],
        'position' => ['content'],
        'slot' => 'category-recommendations',
        'supports' => [
            'layout-category-recommendations',
            'layout-product-list-recommendations',
            'recommended-products',
            'featured-products',
            'product-carousel',
        ],
        'default_injections' => [
            [
                'layout_type' => 'category',
                'layout_option' => 'default',
                'slot' => 'category-recommendations',
                'area' => 'content',
                'sort_order' => 0,
                'required' => true,
                'reason' => '分类页默认展示真实目录推荐产品',
                'config' => [
                    'title' => '推荐产品',
                    'limit' => 8,
                    'columns' => '4',
                    'layout' => 'grid',
                ],
            ],
            [
                'layout_type' => 'product_list',
                'layout_option' => 'default',
                'slot' => 'list-recommendations',
                'area' => 'content',
                'sort_order' => 0,
                'required' => true,
                'reason' => '产品列表页默认展示真实目录推荐产品',
                'config' => [
                    'title' => '推荐产品',
                    'limit' => 8,
                    'columns' => '4',
                    'layout' => 'grid',
                ],
            ],
        ],
        'params' => [
            'title' => [
                'default' => '推荐产品',
                'type' => 'string',
                'label' => '标题',
            ],
            'limit' => [
                'default' => 8,
                'type' => 'number',
                'label' => '显示数量',
            ],
            'columns' => [
                'default' => '4',
                'type' => 'select',
                'label' => '每行列数',
                'options' => [
                    '2' => '2列',
                    '3' => '3列',
                    '4' => '4列',
                    '5' => '5列',
                ],
            ],
            'layout' => [
                'default' => 'grid',
                'type' => 'select',
                'label' => '布局方式',
                'options' => [
                    'grid' => '网格',
                    'carousel' => '轮播',
                ],
            ],
        ],
    ],
];
