<?php

declare(strict_types=1);

return [
    'product-info' => [
        'name' => '产品主要信息',
        'description' => '商品详情主信息：图库、标题、SKU、价格、购买操作槽与规格详情。',
        'type' => 'product',
        'code' => 'product-info',
        'area' => 'frontend',
        'template' => 'Weline_Product::templates/frontend/widgets/product-info.phtml',
        'page_layouts' => ['product'],
        'position' => ['content'],
        'slot' => 'product-main',
        // placement=layout：product 布局已内嵌 <w:widget name="product-info" />；禁止再写 default_injections。
        'placement' => 'layout',
        'is_container' => true,
        'slots' => [
            'product-purchase-actions' => [
                'name' => '购买操作',
                'accepts' => ['product', 'cart', 'checkout'],
                'slot_type' => 'layout-product-purchase-actions',
                'max' => 6,
            ],
            'product-express-payment' => [
                'name' => '快捷支付',
                'accepts' => ['payment', 'express-checkout', 'express-payment', 'product-express-payment'],
                'slot_type' => 'layout-product-express-payment',
                'max' => 3,
            ],
            'product-selling-mode' => [
                'name' => '售卖模式',
                'accepts' => ['product', 'b2b', 'selling-mode'],
                'slot_type' => 'layout-product-selling-mode',
                'max' => 3,
            ],
        ],
        'supports' => [
            'layout-product-main',
            'product-info',
            'product-gallery',
            'product-detail',
        ],
        'params' => [
            'show_brand' => [
                'default' => true,
                'type' => 'bool',
                'label' => '显示品牌',
            ],
            'show_supplier' => [
                'default' => true,
                'type' => 'bool',
                'label' => '显示供应商',
            ],
        ],
    ],
    'related-products' => [
        'name' => '相关产品',
        'description' => '商品详情页相关推荐：读取已发布报价，排除当前商品。',
        'type' => 'product',
        'code' => 'related-products',
        'area' => 'frontend',
        'template' => 'Weline_Product::templates/frontend/widgets/related-products.phtml',
        'page_layouts' => ['product'],
        'position' => ['content'],
        'slot' => 'product-related-products',
        'placement' => 'injection',
        'supports' => [
            'layout-product-related-products',
            'related-products',
            'product-carousel',
        ],
        'default_injections' => [[
            'layout_type' => 'product',
            'layout_option' => 'default',
            'slot' => 'product-related-products',
            'area' => 'content',
            'sort_order' => 0,
            'required' => true,
            'reason' => '商品详情默认在相关产品槽展示真实关联推荐',
            'config' => [
                'title' => '相关产品',
                'limit' => 4,
                'columns' => '4',
                'layout' => 'carousel',
            ],
        ]],
        'params' => [
            'title' => [
                'default' => '相关产品',
                'type' => 'string',
                'label' => '标题',
            ],
            'limit' => [
                'default' => 4,
                'type' => 'number',
                'label' => '显示数量',
            ],
            'columns' => [
                'default' => '4',
                'type' => 'select',
                'label' => '每行列数',
                'options' => [
                    '2' => '2列',
                    '3' => '3列',
                    '4' => '4列',
                    '5' => '5列',
                ],
            ],
            'layout' => [
                'default' => 'carousel',
                'type' => 'select',
                'label' => '布局方式',
                'options' => [
                    'grid' => '网格',
                    'carousel' => '轮播',
                ],
            ],
        ],
    ],
    'you-may-like' => [
        'name' => '猜你喜欢',
        'description' => '商品详情猜你喜欢：同分类亲合优先，真实目录报价补齐。',
        'type' => 'product',
        'code' => 'you-may-like',
        'area' => 'frontend',
        'template' => 'Weline_Product::templates/frontend/widgets/you-may-like.phtml',
        'page_layouts' => ['product'],
        'position' => ['content'],
        'slot' => 'product-you-may-like',
        'placement' => 'injection',
        'supports' => [
            'layout-product-you-may-like',
            'layout-product-related-products',
            'you-may-like',
            'product-carousel',
        ],
        'default_injections' => [[
            'layout_type' => 'product',
            'layout_option' => 'default',
            'slot' => 'product-you-may-like',
            'area' => 'content',
            'sort_order' => 0,
            'required' => true,
            'reason' => '商品详情默认猜你喜欢槽',
            'config' => [
                'title' => '猜你喜欢',
                'limit' => 8,
                'columns' => '4',
                'layout' => 'grid',
            ],
        ]],
        'params' => [
            'title' => [
                'default' => '猜你喜欢',
                'type' => 'string',
                'label' => '标题',
            ],
            'limit' => [
                'default' => 8,
                'type' => 'number',
                'label' => '显示数量',
            ],
            'columns' => [
                'default' => '4',
                'type' => 'select',
                'label' => '每行列数',
                'options' => [
                    '2' => '2列',
                    '3' => '3列',
                    '4' => '4列',
                    '5' => '5列',
                ],
            ],
            'layout' => [
                'default' => 'grid',
                'type' => 'select',
                'label' => '布局方式',
                'options' => [
                    'grid' => '网格',
                    'carousel' => '轮播',
                ],
            ],
            'show_wishlist' => [
                'default' => true,
                'type' => 'bool',
                'label' => '显示收藏',
            ],
            'show_compare' => [
                'default' => true,
                'type' => 'bool',
                'label' => '显示对比',
            ],
            'show_quickview' => [
                'default' => true,
                'type' => 'bool',
                'label' => '显示快速查看',
            ],
        ],
    ],
    'cross-sell' => [
        'name' => '经常一起购买',
        'description' => '商品详情搭配购买：当前商品 + 真实目录推荐，支持勾选合计。',
        'type' => 'product',
        'code' => 'cross-sell',
        'area' => 'frontend',
        'template' => 'Weline_Product::templates/frontend/widgets/cross-sell.phtml',
        'page_layouts' => ['product', 'cart'],
        'position' => ['content'],
        'slot' => 'product-cross-sell',
        'placement' => 'injection',
        'supports' => [
            'layout-product-cross-sell',
            'layout-cart-recommendations',
            'cross-sell',
            'up-sell',
            'product-carousel',
        ],
        'default_injections' => [
            [
                'layout_type' => 'product',
                'layout_option' => 'default',
                'slot' => 'product-cross-sell',
                'area' => 'content',
                'sort_order' => 3,
                'required' => true,
                'reason' => '商品详情默认在搭配推荐槽展示经常一起买',
                'config' => [
                    'title' => '经常一起购买',
                    'limit' => 3,
                    'show_add_all_button' => true,
                    'show_total_price' => true,
                ],
            ],
            [
                'layout_type' => 'cart',
                'layout_option' => 'default',
                'slot' => 'cart-recommendations',
                'area' => 'content',
                'sort_order' => 0,
                'required' => true,
                'reason' => '购物车默认在推荐槽展示交叉销售（非 Theme 部件，禁止布局内嵌）',
                'config' => [
                    'title' => '经常一起购买',
                    'limit' => 3,
                    'show_add_all_button' => true,
                    'show_total_price' => true,
                ],
            ],
        ],
        'params' => [
            'title' => [
                'default' => '经常一起购买',
                'type' => 'string',
                'label' => '标题',
            ],
            'limit' => [
                'default' => 3,
                'type' => 'number',
                'label' => '搭配商品数量',
            ],
            'show_add_all_button' => [
                'default' => true,
                'type' => 'bool',
                'label' => '显示一键添加按钮',
            ],
        ],
    ],
    'recommended-products' => [
        'name' => '推荐产品',
        'description' => '分类/列表推荐：读取已发布报价，网格或轮播展示。',
        'type' => 'product',
        'code' => 'recommended-products',
        'area' => 'frontend',
        'template' => 'Weline_Product::templates/frontend/widgets/recommended-products.phtml',
        'source' => 'Weline_Product::css/widgets/recommended-products.css',
        'page_layouts' => ['category', 'products', 'not_found'],
        'position' => ['content'],
        // 顶栏 slot 偏好 category；products → list-recommendations；404 → not-found-recommendations。
        'slot' => 'category-recommendations',
        'placement' => 'injection',
        'supports' => [
            'layout-category-recommendations',
            'layout-products-recommendations',
            'layout-not-found-recommendations',
            'recommended-products',
            'featured-products',
            'product-carousel',
        ],
        'default_injections' => [
            [
                'layout_type' => 'category',
                'layout_option' => 'default',
                'slot' => 'category-recommendations',
                'area' => 'content',
                'sort_order' => 0,
                'required' => true,
                'reason' => '分类页默认展示真实目录推荐产品',
                'config' => [
                    'title' => '推荐产品',
                    'limit' => 8,
                    'columns' => '4',
                    'layout' => 'grid',
                ],
            ],
            [
                'layout_type' => 'products',
                'layout_option' => 'default',
                'slot' => 'list-recommendations',
                'area' => 'content',
                'sort_order' => 0,
                'required' => true,
                'reason' => '产品列表页默认展示真实目录推荐产品',
                'config' => [
                    'title' => '推荐产品',
                    'limit' => 8,
                    'columns' => '4',
                    'layout' => 'grid',
                ],
            ],
            [
                'layout_type' => 'not_found',
                'layout_option' => 'default',
                'slot' => 'not-found-recommendations',
                'area' => 'content',
                'sort_order' => 0,
                'required' => true,
                'reason' => '404 静态页默认在推荐槽展示目录产品（生成快照时使用，运行时直读静态 HTML）',
                'config' => [
                    'title' => '推荐产品',
                    'limit' => 8,
                    'columns' => '4',
                    'layout' => 'grid',
                ],
            ],
        ],
        'params' => [
            'title' => [
                'default' => '推荐产品',
                'type' => 'string',
                'label' => '标题',
            ],
            'limit' => [
                'default' => 8,
                'type' => 'number',
                'label' => '显示数量',
            ],
            'columns' => [
                'default' => '4',
                'type' => 'select',
                'label' => '每行列数',
                'options' => [
                    '2' => '2列',
                    '3' => '3列',
                    '4' => '4列',
                    '5' => '5列',
                ],
            ],
            'layout' => [
                'default' => 'grid',
                'type' => 'select',
                'label' => '布局方式',
                'options' => [
                    'grid' => '网格',
                    'carousel' => '轮播',
                ],
            ],
        ],
    ],
    'best-sellers-hero' => [
        'name' => '热销榜页头',
        'description' => '热销榜页深色页头：眉题、标题、导语、件数与背景图均可配置',
        'type' => 'banner',
        'code' => 'best-sellers-hero',
        'area' => 'frontend',
        'template' => 'Weline_Product::templates/frontend/widgets/best-sellers-hero.phtml',
        'page_layouts' => ['best_sellers'],
        'position' => ['content'],
        'slot' => 'best-sellers-hero',
        // placement=layout：best_sellers 布局已内嵌 <w:widget>；禁止再写 default_injections。
        'placement' => 'layout',
        'supports' => [
            'layout-best-sellers-hero',
            'layout-best-sellers-main',
            'layout-best-sellers-content',
            'banner',
            'content',
        ],
        // 默认观感由 best_sellers 布局槽内嵌 <w:widget> 提供（同 homepage-hero）；
        // 禁止再声明 required default_injections，否则无 template_ref 的布局行会与模板壳叠成双页头。
        'params' => [
            'eyebrow' => [
                'default' => '本站人气排行',
                'type' => 'string',
                'label' => '眉题',
            ],
            'title' => [
                'default' => '热销榜',
                'type' => 'string',
                'label' => '标题',
            ],
            'lede' => [
                'default' => '按店面热度排序的热销商品，帮你快速找到大家都在买的好物。',
                'type' => 'textarea',
                'label' => '导语',
            ],
            'count_template' => [
                'default' => '共 %{1} 件热销商品',
                'type' => 'string',
                'label' => '件数文案',
                'description' => '用 %{1} 表示实际件数',
            ],
            'show_count' => [
                'default' => true,
                'type' => 'bool',
                'label' => '显示件数',
            ],
            'background_image' => [
                'default' => '',
                'type' => 'media_image',
                'label' => '背景图片',
                'description' => '推荐 1920×400',
                'media_options' => [
                    'default_directory' => 'banner',
                    'aspect_ratio' => '1920/400',
                    'recommend_width' => '1920',
                    'recommend_height' => '400',
                    'aspect_ratio_tolerance' => '0.15',
                ],
            ],
        ],
    ],
];
