<?php

declare(strict_types=1);

namespace Weline\Server\Service\Security;

/**
 * WLS 面板安全探针用例目录。
 *
 * 每条用例说明测什么、预期状态码；面板用一次性 probe token 代发请求，
 * Worker 仍返回拦截码但不 ban。
 */
final class SecurityProbeCatalog
{
    public const HEADER_NAME = 'X-Weline-Security-Probe-Token';

    /** Browser fetch cannot set User-Agent; panel mirrors UA here under a valid probe token. */
    public const PROBE_UA_HEADER = 'X-Weline-Security-Probe-UA';

    /**
     * 实战封禁测试凭证（非豁免）。
     * 带此头时：不豁免 ban，且本机白名单仍执行 attack_rules 以便验收真实封禁。
     */
    public const LIVE_BAN_HEADER = 'X-Weline-Security-Live-Ban-Test';

    /**
     * @return list<array{
     *   id:string,
     *   group:string,
     *   title:string,
     *   description:string,
     *   method:string,
     *   path:string,
     *   expect_status:list<int>,
     *   severity:string
     * }>
     */
    public static function cases(): array
    {
        return [
            [
                'id' => 'utf8_invalid_path',
                'group' => 'encoding',
                'title' => '非法 UTF-8 路径',
                'description' => '百分号解码后出现非法 UTF-8 字节。应在入口直接拒绝，避免脏数据进入数据库。',
                'method' => 'GET',
                'path' => '/%ef%bc%5f',
                'expect_status' => [400],
                'severity' => 'high',
            ],
            [
                'id' => 'path_traversal_encoded',
                'group' => 'path',
                'title' => '编码路径遍历',
                'description' => '在查询参数里放双重编码穿越载荷（浏览器会规范化路径段，故不用 /%2e%2e 测）。应拦截。',
                'method' => 'GET',
                'path' => '/?file=%252e%252e%252fetc%252fpasswd',
                'expect_status' => [403],
                'severity' => 'high',
            ],
            [
                'id' => 'sqli_union_select',
                'group' => 'sqli',
                'title' => 'UNION SELECT 注入',
                'description' => '经典 SQL 联合查询探针。应匹配恶意特征并拦截。',
                'method' => 'GET',
                'path' => '/?q=UNION%20SELECT%20null,null--',
                'expect_status' => [403],
                'severity' => 'critical',
            ],
            [
                'id' => 'sqli_or_numeric',
                'group' => 'sqli',
                'title' => '数字型 OR 1=1',
                'description' => '布尔盲注常见形态 OR/AND 数字恒真。应拦截。',
                'method' => 'GET',
                'path' => '/?q=1%20OR%201%3D1',
                'expect_status' => [403],
                'severity' => 'critical',
            ],
            [
                'id' => 'sqli_or_quoted',
                'group' => 'sqli',
                'title' => '引号型 OR',
                'description' => "字符串拼接型 ' OR '1'='1。应拦截，避免只覆盖数字型规则。",
                'method' => 'GET',
                'path' => '/?q=%27%20OR%20%271%27%3D%271',
                'expect_status' => [403],
                'severity' => 'critical',
            ],
            [
                'id' => 'sqli_double_encoded',
                'group' => 'sqli',
                'title' => '双重百分号编码 SQLi',
                'description' => '%2527 二次解码成引号后触发注入特征。验证多解码扫描是否生效。',
                'method' => 'GET',
                'path' => '/search?q=%2527%20OR%201%3D1',
                'expect_status' => [403],
                'severity' => 'critical',
            ],
            [
                'id' => 'sqli_sleep',
                'group' => 'sqli',
                'title' => '时间盲注 sleep()',
                'description' => '延时函数探针。应拦截，不应真实卡住请求。',
                'method' => 'GET',
                'path' => '/?q=sleep(5)',
                'expect_status' => [403],
                'severity' => 'critical',
            ],
            [
                'id' => 'xss_script',
                'group' => 'xss',
                'title' => 'script 标签 XSS',
                'description' => '反射型 XSS 基础探针。应在请求入口拦截。',
                'method' => 'GET',
                'path' => '/?q=%3Cscript%3Ealert(1)%3C/script%3E',
                'expect_status' => [403],
                'severity' => 'high',
            ],
            [
                'id' => 'xss_svg_onload',
                'group' => 'xss',
                'title' => 'SVG onload XSS',
                'description' => '绕过简单 script 过滤的事件型 XSS。应拦截。',
                'method' => 'GET',
                'path' => '/?x=%3Csvg%20onload%3Dalert(1)%3E',
                'expect_status' => [403],
                'severity' => 'high',
            ],
            [
                'id' => 'xss_javascript_uri',
                'group' => 'xss',
                'title' => 'javascript: 伪协议',
                'description' => '链接/跳转场景常见的 javascript: 注入。应拦截。',
                'method' => 'GET',
                'path' => '/?x=javascript:alert(1)',
                'expect_status' => [403],
                'severity' => 'high',
            ],
            [
                'id' => 'proto_php_filter',
                'group' => 'protocol',
                'title' => 'PHP 伪协议 php://',
                'description' => '文件包含/过滤器伪协议。应拦截，防止本地文件读取。',
                'method' => 'GET',
                'path' => '/?f=php://filter',
                'expect_status' => [403],
                'severity' => 'critical',
            ],
            [
                'id' => 'proto_php_input_path',
                'group' => 'protocol',
                'title' => '路径中的 php://input',
                'description' => '把伪协议写进路径段。应在策略层拒绝，不得变成 500。',
                'method' => 'GET',
                'path' => '/php://input',
                'expect_status' => [400, 403],
                'severity' => 'critical',
            ],
            [
                'id' => 'proto_data',
                'group' => 'protocol',
                'title' => 'data:// 伪协议',
                'description' => 'data:// 常用于包装恶意 payload。应拦截。',
                'method' => 'GET',
                'path' => '/?u=data://text/plain,test',
                'expect_status' => [403],
                'severity' => 'high',
            ],
            [
                'id' => 'proto_expect',
                'group' => 'protocol',
                'title' => 'expect:// 伪协议',
                'description' => '可执行命令的伪协议探针。应拦截。',
                'method' => 'GET',
                'path' => '/?u=expect://id',
                'expect_status' => [403],
                'severity' => 'critical',
            ],
            [
                'id' => 'cmd_backtick',
                'group' => 'command',
                'title' => '反引号命令注入',
                'description' => 'Shell 反引号执行形态。应匹配「分隔符+常见命令」规则。',
                'method' => 'GET',
                'path' => '/?cmd=%60id%60',
                'expect_status' => [403],
                'severity' => 'critical',
            ],
            [
                'id' => 'cmd_dollar_paren',
                'group' => 'command',
                'title' => '$(whoami) 命令注入',
                'description' => '命令替换形态。应拦截。',
                'method' => 'GET',
                'path' => '/?cmd=%24(whoami)',
                'expect_status' => [403],
                'severity' => 'critical',
            ],
            [
                'id' => 'cmd_semicolon_cat',
                'group' => 'command',
                'title' => ';cat 命令串联',
                'description' => '分号串联读敏感文件。应拦截。',
                'method' => 'GET',
                'path' => '/?cmd=%3Bcat%20/etc/passwd',
                'expect_status' => [403],
                'severity' => 'critical',
            ],
            [
                'id' => 'sensitive_env',
                'group' => 'sensitive',
                'title' => '探测 /.env',
                'description' => '敏感配置文件探测。应拦截（403）；不得返回文件内容。',
                'method' => 'GET',
                'path' => '/.env',
                'expect_status' => [403],
                'severity' => 'high',
            ],
            [
                'id' => 'sensitive_git',
                'group' => 'sensitive',
                'title' => '探测 /.git/config',
                'description' => '源码泄露探测。应拦截（403）；不得返回配置正文。',
                'method' => 'GET',
                'path' => '/.git/config',
                'expect_status' => [403],
                'severity' => 'high',
            ],
            [
                'id' => 'scan_wp_login',
                'group' => 'scan',
                'title' => '扫描 /wp-login.php',
                'description' => 'WordPress 登录页扫描。非 WP 站点应拦截。',
                'method' => 'GET',
                'path' => '/wp-login.php',
                'expect_status' => [403],
                'severity' => 'high',
            ],
            [
                'id' => 'scan_wp_admin',
                'group' => 'scan',
                'title' => '扫描 /wp-admin/',
                'description' => 'WordPress 后台目录扫描。应拦截，不得落到店面首页。',
                'method' => 'GET',
                'path' => '/wp-admin/',
                'expect_status' => [403],
                'severity' => 'high',
            ],
            [
                'id' => 'scan_xmlrpc',
                'group' => 'scan',
                'title' => '扫描 /xmlrpc.php',
                'description' => 'WordPress XML-RPC 爆破入口。应拦截。',
                'method' => 'GET',
                'path' => '/xmlrpc.php',
                'expect_status' => [403],
                'severity' => 'high',
            ],
            [
                'id' => 'scan_phpmyadmin',
                'group' => 'scan',
                'title' => '扫描 /phpmyadmin/',
                'description' => 'phpMyAdmin 管理台扫描。应拦截。',
                'method' => 'GET',
                'path' => '/phpmyadmin/',
                'expect_status' => [403],
                'severity' => 'high',
            ],
            [
                'id' => 'scan_admin_php',
                'group' => 'scan',
                'title' => '扫描 /admin.php',
                'description' => '通用后台入口扫描。应拦截。',
                'method' => 'GET',
                'path' => '/admin.php',
                'expect_status' => [403],
                'severity' => 'medium',
            ],
            [
                'id' => 'scan_config_php',
                'group' => 'scan',
                'title' => '扫描 /config.php',
                'description' => '配置文件直链扫描。应拦截。',
                'method' => 'GET',
                'path' => '/config.php',
                'expect_status' => [403],
                'severity' => 'high',
            ],
            [
                'id' => 'scan_install_php',
                'group' => 'scan',
                'title' => '扫描 /install.php',
                'description' => '安装脚本残留扫描。应拦截。',
                'method' => 'GET',
                'path' => '/install.php',
                'expect_status' => [403],
                'severity' => 'medium',
            ],
            [
                'id' => 'scan_setup_php',
                'group' => 'scan',
                'title' => '扫描 /setup.php',
                'description' => '安装/向导脚本扫描。应拦截。',
                'method' => 'GET',
                'path' => '/setup.php',
                'expect_status' => [403],
                'severity' => 'medium',
            ],
            [
                'id' => 'scan_svn_entries',
                'group' => 'scan',
                'title' => '扫描 /.svn/entries',
                'description' => 'SVN 元数据泄露扫描。应拦截。',
                'method' => 'GET',
                'path' => '/.svn/entries',
                'expect_status' => [403],
                'severity' => 'medium',
            ],
            [
                'id' => 'scan_env_bak',
                'group' => 'scan',
                'title' => '扫描 /.env.bak',
                'description' => '环境变量备份文件扫描。应拦截。',
                'method' => 'GET',
                'path' => '/.env.bak',
                'expect_status' => [403],
                'severity' => 'high',
            ],
            [
                'id' => 'scan_aws_credentials',
                'group' => 'scan',
                'title' => '扫描 /.aws/credentials',
                'description' => '云凭证文件扫描。应拦截。',
                'method' => 'GET',
                'path' => '/.aws/credentials',
                'expect_status' => [403],
                'severity' => 'critical',
            ],
            [
                'id' => 'scan_phpunit_eval',
                'group' => 'scan',
                'title' => '扫描 PHPUnit eval-stdin',
                'description' => 'CVE 风格 PHPUnit 入口扫描。应拦截。',
                'method' => 'GET',
                'path' => '/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php',
                'expect_status' => [403],
                'severity' => 'critical',
            ],
            [
                'id' => 'scan_actuator_env',
                'group' => 'scan',
                'title' => '扫描 /actuator/env',
                'description' => 'Spring Actuator 环境端点扫描。应拦截。',
                'method' => 'GET',
                'path' => '/actuator/env',
                'expect_status' => [403],
                'severity' => 'high',
            ],
            [
                'id' => 'scan_server_status',
                'group' => 'scan',
                'title' => '扫描 /server-status',
                'description' => 'Apache/Nginx 状态页扫描。应拦截。',
                'method' => 'GET',
                'path' => '/server-status',
                'expect_status' => [403],
                'severity' => 'medium',
            ],
            [
                'id' => 'ua_sqlmap',
                'group' => 'scanner_ua',
                'title' => '扫描器 UA：sqlmap',
                'description' => 'sqlmap 默认 User-Agent。应识别为恶意扫描器并拦截。',
                'method' => 'GET',
                'path' => '/',
                'headers' => [
                    'User-Agent' => 'sqlmap/1.7#weline-probe',
                    self::PROBE_UA_HEADER => 'sqlmap/1.7#weline-probe',
                ],
                'expect_status' => [403],
                'severity' => 'high',
            ],
            [
                'id' => 'ua_nikto',
                'group' => 'scanner_ua',
                'title' => '扫描器 UA：Nikto',
                'description' => 'Nikto 扫描器 User-Agent。应拦截。',
                'method' => 'GET',
                'path' => '/',
                'headers' => [
                    'User-Agent' => 'Mozilla/5.0 (compatible; Nikto/2.1.6)',
                    self::PROBE_UA_HEADER => 'Mozilla/5.0 (compatible; Nikto/2.1.6)',
                ],
                'expect_status' => [403],
                'severity' => 'high',
            ],
            [
                'id' => 'ua_nmap',
                'group' => 'scanner_ua',
                'title' => '扫描器 UA：Nmap',
                'description' => 'Nmap Scripting Engine User-Agent。应拦截。',
                'method' => 'GET',
                'path' => '/',
                'headers' => [
                    'User-Agent' => 'Mozilla/5.0 (compatible; Nmap Scripting Engine; https://nmap.org/book/nse.html)',
                    self::PROBE_UA_HEADER => 'Mozilla/5.0 (compatible; Nmap Scripting Engine; https://nmap.org/book/nse.html)',
                ],
                'expect_status' => [403],
                'severity' => 'medium',
            ],
            [
                'id' => 'crawler_gptbot',
                'group' => 'crawler_block',
                'title' => '寄生爬虫：GPTBot',
                'description' => 'OpenAI GPTBot。crawler_block 默认应拦截。',
                'method' => 'GET',
                'path' => '/',
                'headers' => [
                    'User-Agent' => 'Mozilla/5.0 (compatible; GPTBot/1.0; +https://openai.com/gptbot)',
                    self::PROBE_UA_HEADER => 'Mozilla/5.0 (compatible; GPTBot/1.0; +https://openai.com/gptbot)',
                ],
                'expect_status' => [403],
                'severity' => 'medium',
            ],
            [
                'id' => 'crawler_bytespider',
                'group' => 'crawler_block',
                'title' => '寄生爬虫：Bytespider',
                'description' => '字节跳动 Bytespider。crawler_block 默认应拦截。',
                'method' => 'GET',
                'path' => '/',
                'headers' => [
                    'User-Agent' => 'Mozilla/5.0 (compatible; Bytespider; https://zhanzhang.toutiao.com/)',
                    self::PROBE_UA_HEADER => 'Mozilla/5.0 (compatible; Bytespider)',
                ],
                'expect_status' => [403],
                'severity' => 'medium',
            ],
            [
                'id' => 'crawler_googlebot_allow',
                'group' => 'crawler_block',
                'title' => '友好引擎：Googlebot 放行',
                'description' => 'Googlebot 必须被 crawler_block 放行（不因寄生规则误杀）。',
                'method' => 'GET',
                'path' => '/',
                'headers' => [
                    'User-Agent' => 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                    self::PROBE_UA_HEADER => 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
                ],
                'expect_status' => [200, 301, 302, 303, 307, 308],
                'severity' => 'low',
            ],
            [
                'id' => 'brute_wp_login_post',
                'group' => 'bruteforce',
                'title' => '爆破形态：POST /wp-login.php',
                'description' => '对 WordPress 登录接口发 POST（常见密码爆破）。应拦截。',
                'method' => 'POST',
                'path' => '/wp-login.php',
                'headers' => ['Content-Type' => 'application/x-www-form-urlencoded'],
                'body' => 'log=admin&pwd=admin&wp-submit=Log+In',
                'expect_status' => [403],
                'severity' => 'high',
            ],
            [
                'id' => 'control_home',
                'group' => 'control',
                'title' => '对照：首页正常',
                'description' => '带 probe token 时正常首页仍应可访问，证明 token 不会误伤业务。',
                'method' => 'GET',
                'path' => '/',
                'expect_status' => [200, 301, 302, 308],
                'severity' => 'info',
            ],
        ];
    }

    public static function groupLabel(string $group): string
    {
        return match ($group) {
            'encoding' => (string)__('编码'),
            'path' => (string)__('路径'),
            'sqli' => (string)__('SQL 注入'),
            'xss' => (string)__('跨站脚本'),
            'crawler_block' => (string)__('爬虫拦截'),
            'protocol' => (string)__('伪协议'),
            'command' => (string)__('命令注入'),
            'sensitive' => (string)__('敏感路径'),
            'scan' => (string)__('路径扫描'),
            'scanner_ua' => (string)__('扫描器指纹'),
            'bruteforce' => (string)__('爆破'),
            'control' => (string)__('对照'),
            default => $group,
        };
    }

    public static function severityLabel(string $severity): string
    {
        return match ($severity) {
            'critical' => (string)__('严重'),
            'high' => (string)__('高'),
            'medium' => (string)__('中'),
            'low' => (string)__('低'),
            'info' => (string)__('信息'),
            default => $severity,
        };
    }
}
