<notempty name="preview">
    <!-- 图片预览 -->
    @template(Weline_FileManager::image-preview/template.phtml)
</notempty>
<!-- Small modal -->
<a type="button" class="w-button waves-light" data-w-target="#{{target}}-select-modal" data-w-action="dialog.open" data-tone="primary" data-size="sm">{{title}}</a>
<if condition="ext !== '*'"><br><span>@lang{允许的文件类型：}({{ext}})</span></if>
<br>
<span>@lang{允许的文件大小：}{{size_alias}}</span>
<div class="w-dialog bs-example-modal-center bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="Elfinder" aria-hidden="true" id="{{target}}-select-modal" data-w-component="dialog" data-state="closed" hidden>
    <div class="w-dialog__frame modal-fullscreen-md-down w-80" data-size="lg">
        <div class="w-dialog__surface">
            <div class="w-dialog__header">
                <h5 class="w-dialog__title">
                    {{title}}
                    <if condition="ext !== '*'"><span class="w-text" data-tone="danger">@lang{允许的文件类型：}({{ext}})</span></if>
                    <span>@lang{允许的文件大小：}{{size_alias}}</span>
                </h5>
                <button type="button" class="w-button" id="{{target}}-close-modal" aria-label="Close" data-w-action="dialog.close" data-w-close="" data-tone="quiet" data-size="sm"></button>
            </div>
            <div class="w-dialog__body" style="padding: 0;">
                <iframe id="{{target}}-file-manager-iframe" style="min-height: 50vh" src="" scrolling="no" frameborder="0" data-w-width="full"></iframe>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script>
    var timer = null;
    $('#{{target}}-select-modal').on('weline:ui:dialog:open', () => {
        const iframe = $("#{{target}}-file-manager-iframe");
        if (iframe.attr('src') === '') {
            iframe.attr('src', '{{connector}}');
        }

        function checkIframeLoaded() {
            const iframe = $("#{{target}}-file-manager-iframe");
            let iframeDoc = iframe[0].contentDocument || undefined;
            if (iframeDoc === undefined && iframe[0].contentWindow) {
                iframeDoc = iframe[0].contentWindow.document;
            }
            if (iframeDoc !== undefined && iframeDoc.readyState === 'complete') {
                const filemanager = $(iframeDoc).find('#{{code}}');
                if (filemanager.length > 0) {
                    const style = filemanager.attr('style')
                    if (style) {
                        iframe.css({height: filemanager.height() + 10 + 'px'})
                        clearInterval(timer)
                    }
                }
            }
        }

        timer = window.setInterval(() => {
            checkIframeLoaded()
        }, 100);
        // 超过10秒则断开
        setTimeout(function () {
            clearInterval(timer)
        }, 10000)
    })
</script>
<notempty name="preview">
    <script>
        // 点击预览
        if ($('#{{target}}-preview')) {
            $('#{{target}}-preview').on('click', '.img', function () {
                let url = $(this).data('url')
                let iframe = $("#{{target}}-file-manager-iframe");
                iframe.attr('src', url)
            })
        }
    </script>
</notempty>