<?php

declare(strict_types=1);

namespace Weline\Geo\Service\Protocol;

use Weline\Geo\Model\Feed;
use Weline\Geo\Model\FeedItem;
use Weline\Geo\Model\WebsiteProtocolConfig;
use Weline\Geo\Service\FeedGeneratorService;
use Weline\Geo\Service\FeedScheduleService;
use Weline\Seo\Api\Protocol\WebsiteProtocolResolverInterface;

class GeoProtocolRenderer
{
    public function __construct(
        private readonly WebsiteProtocolResolverInterface $websiteResolver,
        private readonly Feed $feed,
        private readonly FeedItem $feedItem,
        private readonly FeedGeneratorService $feedGenerator,
        private readonly WebsiteProtocolConfig $protocolConfig,
        private readonly ?FeedScheduleService $feedSchedule = null,
    ) {
    }

    public function renderLlms(bool $full = false): string
    {
        $website = $this->websiteResolver->currentWebsite();
        $config = $this->loadWebsiteConfig($website->id);
        $baseUrl = $this->resolvePublicBaseUrl($website);
        $siteName = $this->resolvePublicSiteName($website);

        if (!$config->isLlmsEnabled()) {
            return '# ' . $siteName . "\n\n> AI discovery is disabled for this website.\n";
        }

        $lines = [
            '# ' . $siteName,
            '',
            '> ' . ($config->getLlmsIntro() ?: 'AI discovery file generated by Weline_Geo.'),
            '',
            '## Discovery',
        ];

        if ($baseUrl !== '') {
            $lines[] = '- Sitemap: ' . $baseUrl . '/sitemap.xml';
            if ($config->isFeedEnabled()) {
                $lines[] = '- JSON Feed: ' . $baseUrl . '/geo-feed.json';
                $lines[] = '- RSS Feed: ' . $baseUrl . '/geo-feed.xml';
            }
        }

        $items = $config->isFeedEnabled() ? $this->collectItems($full ? 500 : 80, $config->getFeedId()) : [];
        if ($items !== []) {
            $productItems = array_values(array_filter($items, fn (array $item): bool => $this->isProductItem($item)));
            $contentItems = array_values(array_filter($items, fn (array $item): bool => !$this->isProductItem($item)));
            if ($productItems !== []) {
                $lines[] = '';
                $lines[] = '## Products';
                foreach ($productItems as $item) {
                    $line = $this->productLine($item, $full);
                    if ($line !== '') {
                        $lines[] = $line;
                    }
                }
            }

            if ($contentItems !== []) {
                $lines[] = '';
                $lines[] = '## Content';
                foreach ($contentItems as $item) {
                    $title = trim((string)($item[FeedItem::schema_fields_TITLE] ?? ''));
                    $url = $this->publicItemUrl(trim((string)($item[FeedItem::schema_fields_URL] ?? '')), $baseUrl);
                    if ($title === '' || $url === '') {
                        continue;
                    }
                    $line = '- [' . $this->plain($title) . '](' . $url . ')';
                    $summary = $this->plain((string)($item[FeedItem::schema_fields_CONTENT] ?? ''));
                    if ($summary !== '') {
                        $line .= ' - ' . mb_substr($summary, 0, $full ? 600 : 180);
                    }
                    $lines[] = $line;
                }
            }
        }

        return implode("\n", $lines) . "\n";
    }

    public function renderFeed(string $format = 'json_feed'): string
    {
        $website = $this->websiteResolver->currentWebsite();
        $config = $this->loadWebsiteConfig($website->id);
        if (!$config->isFeedEnabled()) {
            return $this->emptyFeed($format);
        }

        if ($this->feedSchedule !== null) {
            $cached = $this->feedSchedule->readSiteFeed($format);
            if ($cached !== null && $cached !== '') {
                return $cached;
            }
        }

        return $this->renderFeedLive($format);
    }

    /**
     * Build feed from current DB items (used by schedule publisher and cache miss).
     */
    public function renderFeedLive(string $format = 'json_feed'): string
    {
        $website = $this->websiteResolver->currentWebsite();
        $config = $this->loadWebsiteConfig($website->id);
        if (!$config->isFeedEnabled()) {
            return $this->emptyFeed($format);
        }

        $feeds = $this->enabledFeeds();
        if ($feeds === []) {
            return $this->emptyFeed($format);
        }

        $channel = $this->preferredFeed($config->getFeedId()) ?: $feeds[0];
        $items = [];
        $seen = [];
        foreach ($feeds as $feed) {
            foreach ($this->feedGenerator->listPublishedItems($feed) as $item) {
                $url = trim((string)($item[FeedItem::schema_fields_URL] ?? $item['url'] ?? ''));
                $type = trim((string)($item[FeedItem::schema_fields_ITEM_TYPE] ?? $item['item_type'] ?? ''));
                $id = (string)($item[FeedItem::schema_fields_ITEM_ID] ?? $item['item_id'] ?? '');
                $key = $type . ':' . $id . ':' . $url;
                if ($url === '' || isset($seen[$key])) {
                    continue;
                }
                $seen[$key] = true;
                $items[] = $item;
            }
        }

        usort($items, static function (array $a, array $b): int {
            $left = (int)($a[FeedItem::schema_fields_PUBLISHED_AT] ?? $a['published_at'] ?? 0);
            $right = (int)($b[FeedItem::schema_fields_PUBLISHED_AT] ?? $b['published_at'] ?? 0);
            return $right <=> $left;
        });

        return $this->feedGenerator->generateFeedFromItems($channel, $items, $format);
    }

    /**
     * @return list<Feed>
     */
    private function enabledFeeds(): array
    {
        try {
            $rows = $this->feed->reset()
                ->where(Feed::schema_fields_IS_ENABLED, 1)
                ->order(Feed::schema_fields_ID, 'ASC')
                ->select()
                ->fetchArray();
        } catch (\Throwable) {
            return [];
        }
        if (!is_array($rows) || $rows === []) {
            return [];
        }

        $feeds = [];
        foreach ($rows as $row) {
            $id = (int)($row[Feed::schema_fields_ID] ?? 0);
            if ($id <= 0) {
                continue;
            }
            try {
                $model = clone $this->feed;
                $model->clearData()->reset()->load($id);
                if ($model instanceof Feed && (int)$model->getId() === $id) {
                    $feeds[] = $model;
                }
            } catch (\Throwable) {
            }
        }

        return $feeds;
    }

    private function emptyFeed(string $format): string
    {
        if ($format === 'rss' || $format === 'xml') {
            return '<?xml version="1.0" encoding="UTF-8"?>' . "\n"
                . '<rss version="2.0"><channel><title>GEO Feed</title></channel></rss>';
        }

        return json_encode([
            'version' => 'https://jsonfeed.org/version/1.1',
            'title' => 'GEO Feed',
            'items' => [],
        ], JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT);
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function collectItems(int $limit, int $feedId = 0): array
    {
        try {
            $query = $this->feedItem->reset()
                ->where(FeedItem::schema_fields_IS_PUBLISHED, 1);
            if ($feedId > 0) {
                $query->where(FeedItem::schema_fields_FEED_ID, $feedId);
            }

            return $query->order(FeedItem::schema_fields_PUBLISHED_AT, 'DESC')
                    ->limit($limit)
                    ->select()
                    ->fetchArray();
        } catch (\Throwable) {
            return [];
        }
    }

    private function preferredFeed(int $feedId): ?Feed
    {
        if ($feedId <= 0) {
            return null;
        }

        try {
            $row = $this->feed->reset()->load($feedId);
            return $row instanceof Feed && $row->getId() ? $row : null;
        } catch (\Throwable) {
            return null;
        }
    }

    private function firstEnabledFeed(): ?Feed
    {
        try {
            $row = $this->feed->reset()
                ->where(Feed::schema_fields_IS_ENABLED, 1)
                ->order(Feed::schema_fields_ID, 'ASC')
                ->find()
                ->fetch();

            return $row instanceof Feed && $row->getId() ? $row : null;
        } catch (\Throwable) {
            return null;
        }
    }

    private function plain(string $value): string
    {
        $value = html_entity_decode(strip_tags($value), ENT_QUOTES | ENT_HTML5, 'UTF-8');
        $value = preg_replace('/\s+/u', ' ', $value) ?: $value;
        return trim(str_replace(["\r", "\n"], ' ', $value));
    }

    /**
     * @param array<string, mixed> $item
     */
    private function isProductItem(array $item): bool
    {
        $metadata = $this->metadata($item);
        $type = strtolower(trim((string)($metadata['type'] ?? $metadata['item_type'] ?? $item[FeedItem::schema_fields_ITEM_TYPE] ?? '')));
        return $type === 'product';
    }

    /**
     * @param array<string, mixed> $item
     */
    private function productLine(array $item, bool $full): string
    {
        $title = trim((string)($item[FeedItem::schema_fields_TITLE] ?? ''));
        $url = $this->publicItemUrl(trim((string)($item[FeedItem::schema_fields_URL] ?? '')), $this->resolvePublicBaseUrl($this->websiteResolver->currentWebsite()));
        if ($title === '' || $url === '') {
            return '';
        }

        $metadata = $this->metadata($item);
        $details = [];
        foreach ([
            'Brand' => ['brand', 'brand_name'],
            'SKU' => ['sku'],
            'SPU' => ['spu', 'product_group_id'],
            'Category' => ['category_path', 'category'],
        ] as $label => $keys) {
            $value = $this->firstMetadataValue($metadata, $keys);
            if ($value !== '') {
                $details[] = $label . ': ' . $this->plain($value);
            }
        }

        $price = $this->firstMetadataValue($metadata, ['price', 'final_price']);
        if ($price !== '') {
            $currency = $this->firstMetadataValue($metadata, ['currency', 'price_currency']) ?: 'USD';
            $details[] = 'Price: ' . $this->plain($price . ' ' . strtoupper($currency));
        }

        $availability = $this->firstMetadataValue($metadata, ['availability', 'stock_status']);
        if ($availability !== '') {
            $details[] = 'Availability: ' . $this->plain($this->availabilityLabel($availability));
        }

        $rating = $this->firstMetadataValue($metadata, ['rating', 'rating_value']);
        $reviewCount = $this->firstMetadataValue($metadata, ['review_count', 'reviewCount']);
        if ($rating !== '') {
            $ratingText = 'Rating: ' . $this->plain($rating);
            if ($reviewCount !== '') {
                $ratingText .= ' (' . $this->plain($reviewCount) . ' reviews)';
            }
            $details[] = $ratingText;
        }

        $line = '- [' . $this->plain($title) . '](' . $url . ')';
        if ($details !== []) {
            $line .= ' - ' . implode('; ', $details);
        }
        $summary = $this->plain((string)($item[FeedItem::schema_fields_CONTENT] ?? ''));
        if ($summary !== '') {
            $line .= ' - ' . mb_substr($summary, 0, $full ? 600 : 180);
        }
        return $line;
    }

    /**
     * @param array<string, mixed> $item
     * @return array<string, mixed>
     */
    private function metadata(array $item): array
    {
        $metadata = $item[FeedItem::schema_fields_METADATA] ?? [];
        if (is_array($metadata)) {
            return $metadata;
        }
        if (!is_string($metadata) || trim($metadata) === '') {
            return [];
        }
        $decoded = json_decode($metadata, true);
        return is_array($decoded) ? $decoded : [];
    }

    /**
     * @param array<string, mixed> $metadata
     * @param string[] $keys
     */
    private function firstMetadataValue(array $metadata, array $keys): string
    {
        foreach ($keys as $key) {
            $value = $metadata[$key] ?? null;
            if ($value === null && isset($metadata['product']) && is_array($metadata['product'])) {
                $value = $metadata['product'][$key] ?? null;
            }
            if (is_array($value)) {
                $value = implode(' > ', array_filter(array_map('strval', $value)));
            }
            $value = trim((string)$value);
            if ($value !== '') {
                return $value;
            }
        }
        return '';
    }

    private function availabilityLabel(string $availability): string
    {
        $value = strtolower(trim($availability));
        if (str_contains($value, 'instock') || str_contains($value, 'in_stock')) {
            return 'InStock';
        }
        if (str_contains($value, 'outofstock') || str_contains($value, 'out_of_stock') || str_contains($value, 'sold')) {
            return 'OutOfStock';
        }
        if (str_contains($value, 'preorder')) {
            return 'PreOrder';
        }
        if (str_contains($value, 'backorder')) {
            return 'BackOrder';
        }
        return $availability;
    }

    private function loadWebsiteConfig(int $websiteId): WebsiteProtocolConfig
    {
        try {
            if ($websiteId > 0) {
                return $this->protocolConfig->loadByWebsiteId($websiteId);
            }
        } catch (\Throwable) {
        }

        return $this->protocolConfig->reset();
    }

    /**
     * Prefer the live request origin over stored website.url when the catalog
     * still holds localhost / loopback placeholders from seeding.
     */
    private function resolvePublicBaseUrl(object $website): string
    {
        $candidates = [];
        $fullUrl = (string) \Weline\Framework\Env\WelineEnv::server('WELINE_FULL_REQUEST_URI', '');
        if ($fullUrl !== '' && preg_match('#^https?://#i', $fullUrl) === 1) {
            $parts = parse_url($fullUrl);
            if (is_array($parts) && !empty($parts['host'])) {
                $port = isset($parts['port']) ? ':' . $parts['port'] : '';
                $candidates[] = (string) ($parts['scheme'] ?? 'https') . '://' . (string) $parts['host'] . $port;
            }
        }
        $host = (string) \Weline\Framework\Env\WelineEnv::server('HTTP_HOST', '');
        if ($host !== '') {
            $https = (string) \Weline\Framework\Env\WelineEnv::server('HTTPS', '');
            $scheme = $https !== '' && strtolower($https) !== 'off' ? 'https' : 'https';
            $requestScheme = (string) \Weline\Framework\Env\WelineEnv::server('REQUEST_SCHEME', '');
            if ($requestScheme !== '') {
                $scheme = $requestScheme;
            }
            $candidates[] = $scheme . '://' . $host;
        }
        $candidates[] = rtrim(trim((string)($website->url ?? '')), '/');

        foreach ($candidates as $candidate) {
            if ($candidate === '' || !$this->isHttpUrl($candidate) || $this->isLoopbackHost($candidate)) {
                continue;
            }

            return rtrim($candidate, '/');
        }

        foreach ($candidates as $candidate) {
            if ($candidate !== '' && $this->isHttpUrl($candidate)) {
                return rtrim($candidate, '/');
            }
        }

        return '';
    }

    private function publicItemUrl(string $url, string $baseUrl): string
    {
        $url = trim($url);
        $baseUrl = rtrim($baseUrl, '/');
        if ($url === '') {
            return '';
        }
        if (preg_match('#^https?://#i', $url) === 1) {
            if ($baseUrl !== '' && $this->isLoopbackHost($url)) {
                $path = (string) (parse_url($url, PHP_URL_PATH) ?: '/');
                $query = parse_url($url, PHP_URL_QUERY);
                $fragment = parse_url($url, PHP_URL_FRAGMENT);

                return $baseUrl
                    . ($path === '' ? '/' : $path)
                    . (is_string($query) && $query !== '' ? '?' . $query : '')
                    . (is_string($fragment) && $fragment !== '' ? '#' . $fragment : '');
            }

            return $url;
        }
        if ($baseUrl === '') {
            return $url;
        }

        return $baseUrl . '/' . ltrim($url, '/');
    }

    private function isHttpUrl(string $url): bool
    {
        $scheme = strtolower((string) (parse_url($url, PHP_URL_SCHEME) ?? ''));

        return in_array($scheme, ['http', 'https'], true) && (string) (parse_url($url, PHP_URL_HOST) ?? '') !== '';
    }

    private function isLoopbackHost(string $url): bool
    {
        $host = strtolower((string) (parse_url($url, PHP_URL_HOST) ?? ''));
        if ($host === '') {
            return false;
        }

        return $host === 'localhost'
            || $host === '127.0.0.1'
            || $host === '::1'
            || str_ends_with($host, '.localhost')
            || str_ends_with($host, '.local');
    }

    /**
     * Prefer SEO-resolved public brand over framework placeholder website names.
     */
    private function resolvePublicSiteName(object $website): string
    {
        $fallback = trim((string)($website->name ?? ''));
        if ($fallback === '') {
            $fallback = 'Weline';
        }

        try {
            $context = \Weline\Framework\Manager\ObjectManager::getInstance(
                \Weline\Seo\Api\Head\PageContextResolverInterface::class
            )->resolve(null, [
                'slot' => 'head',
                'canonical_url' => rtrim((string)($website->url ?? ''), '/') . '/',
                'url' => rtrim((string)($website->url ?? ''), '/') . '/',
            ]);
            $resolved = trim((string)($context->siteName ?? ''));
            if ($resolved !== '') {
                return $resolved;
            }
        } catch (\Throwable) {
        }

        if ($this->isFrameworkPlaceholderSiteName($fallback)) {
            return 'Weline';
        }

        return $fallback;
    }

    private function isFrameworkPlaceholderSiteName(string $siteName): bool
    {
        $normalized = trim(preg_replace('/\s+/u', ' ', $siteName) ?? $siteName);

        return (bool) preg_match(
            '/^(默认网站|默认店铺|Default Website|Default Store|Weline|Weline Framework)(?:\s+(默认网站|默认店铺|Default Website|Default Store))*$/iu',
            $normalized
        );
    }
}
