<?php

declare(strict_types=1);

namespace Weline\Geo\Service\Protocol;

use Weline\Geo\Model\Feed;
use Weline\Geo\Model\FeedItem;
use Weline\Geo\Model\WebsiteProtocolConfig;
use Weline\Geo\Service\FeedGeneratorService;
use Weline\Seo\Service\Protocol\WebsiteProtocolResolver;

class GeoProtocolRenderer
{
    public function __construct(
        private readonly WebsiteProtocolResolver $websiteResolver,
        private readonly Feed $feed,
        private readonly FeedItem $feedItem,
        private readonly FeedGeneratorService $feedGenerator,
        private readonly WebsiteProtocolConfig $protocolConfig
    ) {
    }

    public function renderLlms(bool $full = false): string
    {
        $website = $this->websiteResolver->currentWebsite();
        $config = $this->loadWebsiteConfig((int)($website['website_id'] ?? 0));
        $baseUrl = rtrim((string)($website['url'] ?? ''), '/');
        $siteName = (string)($website['name'] ?? 'Weline');

        if (!$config->isLlmsEnabled()) {
            return '# ' . $siteName . "\n\n> AI discovery is disabled for this website.\n";
        }

        $lines = [
            '# ' . $siteName,
            '',
            '> ' . ($config->getLlmsIntro() ?: 'AI discovery file generated by Weline_Geo.'),
            '',
            '## Discovery',
        ];

        if ($baseUrl !== '') {
            $lines[] = '- Sitemap: ' . $baseUrl . '/sitemap.xml';
            if ($config->isFeedEnabled()) {
                $lines[] = '- JSON Feed: ' . $baseUrl . '/geo-feed.json';
                $lines[] = '- RSS Feed: ' . $baseUrl . '/geo-feed.xml';
            }
        }

        $items = $config->isFeedEnabled() ? $this->collectItems($full ? 500 : 80, $config->getFeedId()) : [];
        if ($items !== []) {
            $productItems = array_values(array_filter($items, fn (array $item): bool => $this->isProductItem($item)));
            $contentItems = array_values(array_filter($items, fn (array $item): bool => !$this->isProductItem($item)));
            if ($productItems !== []) {
                $lines[] = '';
                $lines[] = '## Products';
                foreach ($productItems as $item) {
                    $line = $this->productLine($item, $full);
                    if ($line !== '') {
                        $lines[] = $line;
                    }
                }
            }

            if ($contentItems !== []) {
                $lines[] = '';
                $lines[] = '## Content';
                foreach ($contentItems as $item) {
                    $title = trim((string)($item[FeedItem::schema_fields_TITLE] ?? ''));
                    $url = trim((string)($item[FeedItem::schema_fields_URL] ?? ''));
                    if ($title === '' || $url === '') {
                        continue;
                    }
                    $line = '- [' . $this->plain($title) . '](' . $url . ')';
                    $summary = $this->plain((string)($item[FeedItem::schema_fields_CONTENT] ?? ''));
                    if ($summary !== '') {
                        $line .= ' - ' . mb_substr($summary, 0, $full ? 600 : 180);
                    }
                    $lines[] = $line;
                }
            }
        }

        return implode("\n", $lines) . "\n";
    }

    public function renderFeed(string $format = 'json_feed'): string
    {
        $website = $this->websiteResolver->currentWebsite();
        $config = $this->loadWebsiteConfig((int)($website['website_id'] ?? 0));
        if (!$config->isFeedEnabled()) {
            return $this->emptyFeed($format);
        }

        $feed = $this->preferredFeed($config->getFeedId()) ?: $this->firstEnabledFeed();
        if ($feed) {
            return $this->feedGenerator->generateFeed($feed, $format);
        }

        return $this->emptyFeed($format);
    }

    private function emptyFeed(string $format): string
    {
        if ($format === 'rss' || $format === 'xml') {
            return '<?xml version="1.0" encoding="UTF-8"?>' . "\n"
                . '<rss version="2.0"><channel><title>GEO Feed</title></channel></rss>';
        }

        return json_encode([
            'version' => 'https://jsonfeed.org/version/1.1',
            'title' => 'GEO Feed',
            'items' => [],
        ], JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT);
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function collectItems(int $limit, int $feedId = 0): array
    {
        try {
            $query = $this->feedItem->reset()
                ->where(FeedItem::schema_fields_IS_PUBLISHED, 1);
            if ($feedId > 0) {
                $query->where(FeedItem::schema_fields_FEED_ID, $feedId);
            }

            return $query->order(FeedItem::schema_fields_PUBLISHED_AT, 'DESC')
                    ->limit($limit)
                    ->select()
                    ->fetchArray();
        } catch (\Throwable) {
            return [];
        }
    }

    private function preferredFeed(int $feedId): ?Feed
    {
        if ($feedId <= 0) {
            return null;
        }

        try {
            $row = $this->feed->reset()->load($feedId);
            return $row instanceof Feed && $row->getId() ? $row : null;
        } catch (\Throwable) {
            return null;
        }
    }

    private function firstEnabledFeed(): ?Feed
    {
        try {
            $row = $this->feed->reset()
                ->where(Feed::schema_fields_IS_ENABLED, 1)
                ->order(Feed::schema_fields_ID, 'ASC')
                ->find()
                ->fetch();

            return $row instanceof Feed && $row->getId() ? $row : null;
        } catch (\Throwable) {
            return null;
        }
    }

    private function plain(string $value): string
    {
        $value = html_entity_decode(strip_tags($value), ENT_QUOTES | ENT_HTML5, 'UTF-8');
        $value = preg_replace('/\s+/u', ' ', $value) ?: $value;
        return trim(str_replace(["\r", "\n"], ' ', $value));
    }

    /**
     * @param array<string, mixed> $item
     */
    private function isProductItem(array $item): bool
    {
        $metadata = $this->metadata($item);
        $type = strtolower(trim((string)($metadata['type'] ?? $metadata['item_type'] ?? $item[FeedItem::schema_fields_ITEM_TYPE] ?? '')));
        return $type === 'product';
    }

    /**
     * @param array<string, mixed> $item
     */
    private function productLine(array $item, bool $full): string
    {
        $title = trim((string)($item[FeedItem::schema_fields_TITLE] ?? ''));
        $url = trim((string)($item[FeedItem::schema_fields_URL] ?? ''));
        if ($title === '' || $url === '') {
            return '';
        }

        $metadata = $this->metadata($item);
        $details = [];
        foreach ([
            'Brand' => ['brand', 'brand_name'],
            'SKU' => ['sku'],
            'SPU' => ['spu', 'product_group_id'],
            'Category' => ['category_path', 'category'],
        ] as $label => $keys) {
            $value = $this->firstMetadataValue($metadata, $keys);
            if ($value !== '') {
                $details[] = $label . ': ' . $this->plain($value);
            }
        }

        $price = $this->firstMetadataValue($metadata, ['price', 'final_price']);
        if ($price !== '') {
            $currency = $this->firstMetadataValue($metadata, ['currency', 'price_currency']) ?: 'USD';
            $details[] = 'Price: ' . $this->plain($price . ' ' . strtoupper($currency));
        }

        $availability = $this->firstMetadataValue($metadata, ['availability', 'stock_status']);
        if ($availability !== '') {
            $details[] = 'Availability: ' . $this->plain($this->availabilityLabel($availability));
        }

        $rating = $this->firstMetadataValue($metadata, ['rating', 'rating_value']);
        $reviewCount = $this->firstMetadataValue($metadata, ['review_count', 'reviewCount']);
        if ($rating !== '') {
            $ratingText = 'Rating: ' . $this->plain($rating);
            if ($reviewCount !== '') {
                $ratingText .= ' (' . $this->plain($reviewCount) . ' reviews)';
            }
            $details[] = $ratingText;
        }

        $line = '- [' . $this->plain($title) . '](' . $url . ')';
        if ($details !== []) {
            $line .= ' - ' . implode('; ', $details);
        }
        $summary = $this->plain((string)($item[FeedItem::schema_fields_CONTENT] ?? ''));
        if ($summary !== '') {
            $line .= ' - ' . mb_substr($summary, 0, $full ? 600 : 180);
        }
        return $line;
    }

    /**
     * @param array<string, mixed> $item
     * @return array<string, mixed>
     */
    private function metadata(array $item): array
    {
        $metadata = $item[FeedItem::schema_fields_METADATA] ?? [];
        if (is_array($metadata)) {
            return $metadata;
        }
        if (!is_string($metadata) || trim($metadata) === '') {
            return [];
        }
        $decoded = json_decode($metadata, true);
        return is_array($decoded) ? $decoded : [];
    }

    /**
     * @param array<string, mixed> $metadata
     * @param string[] $keys
     */
    private function firstMetadataValue(array $metadata, array $keys): string
    {
        foreach ($keys as $key) {
            $value = $metadata[$key] ?? null;
            if ($value === null && isset($metadata['product']) && is_array($metadata['product'])) {
                $value = $metadata['product'][$key] ?? null;
            }
            if (is_array($value)) {
                $value = implode(' > ', array_filter(array_map('strval', $value)));
            }
            $value = trim((string)$value);
            if ($value !== '') {
                return $value;
            }
        }
        return '';
    }

    private function availabilityLabel(string $availability): string
    {
        $value = strtolower(trim($availability));
        if (str_contains($value, 'instock') || str_contains($value, 'in_stock')) {
            return 'InStock';
        }
        if (str_contains($value, 'outofstock') || str_contains($value, 'out_of_stock') || str_contains($value, 'sold')) {
            return 'OutOfStock';
        }
        if (str_contains($value, 'preorder')) {
            return 'PreOrder';
        }
        if (str_contains($value, 'backorder')) {
            return 'BackOrder';
        }
        return $availability;
    }

    private function loadWebsiteConfig(int $websiteId): WebsiteProtocolConfig
    {
        try {
            if ($websiteId > 0) {
                return $this->protocolConfig->loadByWebsiteId($websiteId);
            }
        } catch (\Throwable) {
        }

        return $this->protocolConfig->reset();
    }
}
