<?php

declare(strict_types=1);

namespace Weline\Seo\Service\Protocol;

use Weline\Framework\App\Env;
use Weline\Seo\Model\WebsiteProtocolConfig;

class RobotsTxtRenderer
{
    public function __construct(
        private readonly WebsiteProtocolResolver $websiteResolver,
        private readonly WebsiteProtocolConfig $protocolConfig,
        private readonly \Weline\Seo\Service\StoreModeSeoHardGate $storeModeGate = new \Weline\Seo\Service\StoreModeSeoHardGate(),
    ) {
    }

    public function render(): string
    {
        if ($this->storeModeGate->isHardNoIndexMode()) {
            return $this->storeModeGate->forceRobotsTxt();
        }

        $website = $this->websiteResolver->currentWebsite();
        $config = $this->loadWebsiteConfig((int)($website['website_id'] ?? 0));
        $lines = [
            '# Generated by Weline_Seo',
            'User-agent: *',
        ];

        if ($config->isRobotsEnabled()) {
            $lines[] = 'Allow: /';
            foreach ($this->defaultDisallowPaths() as $path) {
                $lines[] = 'Disallow: ' . $path;
            }
            foreach ($this->extraDirectives($config->getRobotsExtra()) as $directive) {
                $lines[] = $directive;
            }
        } else {
            $lines[] = 'Disallow: /';
        }

        if ($this->shouldDisallowGoogleExtended($config)) {
            $lines[] = '';
            $lines[] = 'User-agent: Google-Extended';
            $lines[] = 'Disallow: /';
        }

        if ($config->isSitemapEnabled()) {
            $sitemapUrls = $this->sitemapDeclarationUrls($website);
            if ($sitemapUrls !== []) {
                $lines[] = '';
                foreach ($sitemapUrls as $sitemapUrl) {
                    $lines[] = 'Sitemap: ' . $sitemapUrl;
                }
            }
        }

        return implode("\n", $lines) . "\n";
    }

    /**
     * Declare one Sitemap line per public origin (Website.url + WebsiteDomain).
     *
     * @param array<string, mixed> $website
     * @return list<string>
     */
    private function sitemapDeclarationUrls(array $website): array
    {
        $urls = [];
        $seen = [];
        foreach ($this->websiteResolver->listPublicOrigins($website) as $origin) {
            if (!is_array($origin)) {
                continue;
            }
            $sitemapUrl = trim((string)($origin['sitemap_url'] ?? ''));
            if ($sitemapUrl === '' || isset($seen[$sitemapUrl])) {
                continue;
            }
            $seen[$sitemapUrl] = true;
            $urls[] = $sitemapUrl;
        }
        if ($urls !== []) {
            return $urls;
        }

        $baseUrl = rtrim((string)($website['url'] ?? $this->websiteResolver->currentBaseUrl()), '/');
        return $baseUrl !== '' ? [$baseUrl . '/sitemap.xml'] : [];
    }

    /**
     * @return string[]
     */
    private function defaultDisallowPaths(): array
    {
        $paths = [
            '/rest/',
            '/backend/',
            '/location/rest/',
        ];

        $backendPrefix = (string)Env::getAreaRoutePrefix('backend');
        if ($backendPrefix !== '') {
            $paths[] = '/' . trim($backendPrefix, '/') . '/';
        }

        return array_values(array_unique(array_filter($paths)));
    }

    private function shouldDisallowGoogleExtended(WebsiteProtocolConfig $config): bool
    {
        if ($config->getGoogleExtendedPolicy() === 'disallow') {
            return true;
        }

        $value = strtolower((string)w_env('seo.robots.google_extended', 'allow'));
        return in_array($value, ['disallow', 'deny', 'block', '0', 'false'], true);
    }

    private function loadWebsiteConfig(int $websiteId): WebsiteProtocolConfig
    {
        try {
            if ($websiteId >= 0) {
                return $this->protocolConfig->loadByWebsiteId($websiteId);
            }
        } catch (\Throwable) {
        }

        return $this->protocolConfig->reset();
    }

    /**
     * @return string[]
     */
    private function extraDirectives(string $value): array
    {
        $lines = preg_split('/\r\n|\r|\n/', $value) ?: [];
        $directives = [];
        foreach ($lines as $line) {
            $line = trim((string)$line);
            if ($line === '') {
                continue;
            }
            $directives[] = str_replace(["\r", "\n"], '', $line);
        }

        return $directives;
    }
}
