<?php

declare(strict_types=1);

namespace Weline\Seo\Service\Protocol;

use Weline\Framework\App\Env;
use Weline\Seo\Model\WebsiteProtocolConfig;

class RobotsTxtRenderer
{
    public function __construct(
        private readonly WebsiteProtocolResolver $websiteResolver,
        private readonly WebsiteProtocolConfig $protocolConfig
    ) {
    }

    public function render(): string
    {
        $website = $this->websiteResolver->currentWebsite();
        $baseUrl = rtrim((string)($website['url'] ?? $this->websiteResolver->currentBaseUrl()), '/');
        $config = $this->loadWebsiteConfig((int)($website['website_id'] ?? 0));
        $lines = [
            '# Generated by Weline_Seo',
            'User-agent: *',
        ];

        if ($config->isRobotsEnabled()) {
            $lines[] = 'Allow: /';
            foreach ($this->defaultDisallowPaths() as $path) {
                $lines[] = 'Disallow: ' . $path;
            }
            foreach ($this->extraDirectives($config->getRobotsExtra()) as $directive) {
                $lines[] = $directive;
            }
        } else {
            $lines[] = 'Disallow: /';
        }

        if ($this->shouldDisallowGoogleExtended($config)) {
            $lines[] = '';
            $lines[] = 'User-agent: Google-Extended';
            $lines[] = 'Disallow: /';
        }

        if ($baseUrl !== '' && $config->isSitemapEnabled()) {
            $lines[] = '';
            $lines[] = 'Sitemap: ' . $baseUrl . '/sitemap.xml';
        }

        return implode("\n", $lines) . "\n";
    }

    /**
     * @return string[]
     */
    private function defaultDisallowPaths(): array
    {
        $paths = [
            '/rest/',
            '/backend/',
            '/location/rest/',
        ];

        $backendPrefix = (string)Env::getAreaRoutePrefix('backend');
        if ($backendPrefix !== '') {
            $paths[] = '/' . trim($backendPrefix, '/') . '/';
        }

        return array_values(array_unique(array_filter($paths)));
    }

    private function shouldDisallowGoogleExtended(WebsiteProtocolConfig $config): bool
    {
        if ($config->getGoogleExtendedPolicy() === 'disallow') {
            return true;
        }

        $value = strtolower((string)w_env('seo.robots.google_extended', 'allow'));
        return in_array($value, ['disallow', 'deny', 'block', '0', 'false'], true);
    }

    private function loadWebsiteConfig(int $websiteId): WebsiteProtocolConfig
    {
        try {
            if ($websiteId > 0) {
                return $this->protocolConfig->loadByWebsiteId($websiteId);
            }
        } catch (\Throwable) {
        }

        return $this->protocolConfig->reset();
    }

    /**
     * @return string[]
     */
    private function extraDirectives(string $value): array
    {
        $lines = preg_split('/\r\n|\r|\n/', $value) ?: [];
        $directives = [];
        foreach ($lines as $line) {
            $line = trim((string)$line);
            if ($line === '') {
                continue;
            }
            $directives[] = str_replace(["\r", "\n"], '', $line);
        }

        return $directives;
    }
}
