<?php
/**@var \Weline\Framework\View\Template $this */
?>
<!-- start page title -->
<div class='row'>
    <div class='col-12'>
        <div class='page-title-box d-sm-flex align-items-center justify-content-between'>
            <h4 class='mb-sm-0'><lang>i18n国际化词典</lang></h4>

            <div class='page-title-right'>
                <ol class='breadcrumb m-0'>
                    <li class='breadcrumb-item'><a href='javascript: void(0);'><lang>系统配置</lang></a></li>
                    <li class='breadcrumb-item active'><lang>i18n国际化词典</lang></li>
                </ol>
            </div>

        </div>
    </div>
</div>
<!-- end page title -->

<div class='row'>
    <div class='col-12'>
        <div class='card'>
            <div class='card-body'>

                <h4 class='card-title'><lang>i18n国际化词典</lang></h4>
                <p class='card-title-desc'><lang>国际化支持：翻译管理多种语言词典</lang></p>
                <div class='table-rep-plugin'>
                    <div class='table-responsive mb-0' data-pattern='priority-columns'>
                        <table id='tech-companies-1' class='table table-striped table-bordered'>
                            <thead>
                            <tr>
                                <th data-priority='1'><?= __('排序') ?></th>
                                <th data-priority='1'><?= __('语言代码') ?></th>
                                <th data-priority='3'><?= __('语言名') ?></th>
                                <th data-priority='1'><?= __('是否禁用') ?></th>
                                <th data-priority='3'><?= __('是否安装') ?></th>
                                <th data-priority='3'><?= __('操作') ?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            foreach ($events as $file => $event) :
                                ?>
                                <tr>
                                    <td></td>
                                    <th colspan="4" class='co-name'><?= $file ?></th>
                                </tr>
                                <?php
                                foreach ($event as $name => $instances) {
                                    ?>
                                    <tr>
                                        <td></td>
                                        <th colspan="4" class='co-name'><?= $name ?></th>
                                    </tr>
                                    <?php
                                    foreach ($instances as $key => $instance) {
                                        ?>
                                        <tr>
                                            <th class="co-name"><?= $key ?></th>
                                            <td><?= $instance['name'] ?></td>
                                            <td><?= $instance['instance'] ?></td>
                                            <td><?= $instance['disabled'] ?></td>
                                            <td><?= $instance['shared'] ?></td>
                                        </tr>
                                        <?php
                                    }
                                    ?>
                                    <?php
                                }
                                ?>
                            <?php
                            endforeach;
                            ?>
                            </tbody>
                        </table>
                    </div>

                </div>

            </div>
        </div>
    </div> <!-- end col -->
</div> <!-- end row -->

<!-- jquery.mCustomScrollbar 插件 -->
<link href="@static(Weline_Admin::/libs/jquery.mCustomScrollbar/jquery.mCustomScrollbar.css)" rel="stylesheet"/>
<!-- Responsive Table css -->
<link href='@static(Weline_Admin::assets/libs/admin-resources/rwd-table/rwd-table.min.css)' rel='stylesheet' type='text/css'/>

<!-- Table Editable plugin -->
<script src="@static(Weline_Admin::assets/libs/table-edits/build/table-edits.min.js)"></script>
<script src="@static(Weline_Admin::assets/js/pages/menus/table-editable.init.js)"></script>
<script src='@static(Weline_Admin::/libs/jquery.mCustomScrollbar/jquery.mCustomScrollbar.concat.min.js)'></script>
<!-- Responsive Table js -->
<script src='@static(Weline_Admin::assets/libs/admin-resources/rwd-table/rwd-table.min.js)'></script>

<!-- Init js -->
<script src='@static(Weline_Admin::assets/js/pages/table-responsive.init.js)'></script>
