<?php

declare(strict_types=1);

// Generated by StaticErrorPagePublisher — do not edit.
return array (
  'e2e-test-1783791034.weline.test' => 'e2e-theme-default-e2e_default_injection_mso3wfcu_1',
  'e2e-theme-default-e2e_default_injection_mso3wvvv_2.test' => 'e2e-theme-default-e2e_default_injection_mso3wvvv_2',
  'p05113ef3.test.weline.com' => 'default',
  '127.0.0.1' => 'default',
  'localhost' => 'default',
);
