<?php

declare(strict_types=1);

namespace GuoLaiRen\PageBuilder\Extends\Module\Weline_Ai\Style;

use Weline\Ai\Interface\StyleProviderInterface;
use Weline\Ai\Model\AiStyle;

final class PageBuilderStyleProvider implements StyleProviderInterface
{
    public const CARD_GAME_STYLE_CODE = 'india-card-game-apk-dark-neon';

    /**
     * @return array<int, array<string, mixed>>
     */
    public function listStyles(): array
    {
        return [
            [
                'id' => 0,
                'admin_user_id' => 0,
                'code' => self::CARD_GAME_STYLE_CODE,
                'name' => '霓虹棋牌暗色娱乐页',
                'description' => '用于霓虹棋牌、扑克、麻将、Rummy、Teen Patti 等线上娱乐站。强调暗色牌桌氛围、中心强视觉、金橙 CTA、卡牌/筹码/奖励氛围、深棕/墨蓝/霓虹分区、横向滚动玩家评价，以及游戏官网式 FAQ、评论、游戏列表、攻略和法务页面。',
                'source_type' => AiStyle::SOURCE_BUILTIN,
                'source_module' => 'GuoLaiRen_PageBuilder',
                'industry_tags' => ['霓虹棋牌', '棋牌游戏', '线上娱乐', '扑克麻将', '奖励游戏'],
                'match_keywords' => [
                    '霓虹棋牌',
                    '霓虹棋牌官网',
                    '线上棋牌',
                    '棋牌游戏',
                    '牌桌',
                    '牌局',
                    'Teen Patti',
                    'TeenPatti',
                    'Rummy',
                    'Andar Bahar',
                    'Casino',
                    'Poker',
                    'Ludo',
                    'Neon Card Room',
                    'Card Game Lobby',
                    'teen patti master',
                    'teen patti room',
                    'teen patti lobby',
                    'mahjong',
                    'chaal',
                    'boot value',
                    'blind',
                    'seen',
                    'sideshow',
                    'muflis',
                    'AK47',
                    'private teen patti',
                    'classic teen patti',
                    'player reviews',
                    'FAQ',
                    'privacy policy',
                    'terms',
                    'cookies',
                ],
                'visual_keywords' => [
                    'dark gaming launch page',
                    'floating black rounded navigation bar with compact play CTA',
                    'center-stage card table or game lobby visual',
                    'large localized headline with editorial badge above it',
                    'gold/orange conversion CTA',
                    'cards, chips, rupee-token atmosphere, jackpot-like celebration visuals, and reward/bonus cues when they fit the brief and plan',
                    'deep brown and ink-blue section bands',
                    'neon teal/purple edge light used sparingly',
                    'premium mobile-game campaign density',
                    'Teen Patti Octane reference language: oct-nav shell, hero-crown stage, command cards, route chips, review rail, journal sidebar, legal document shell',
                    'side command cards around a hero poster',
                    'step and signal micro-cards: pick variant, set boot, play blind/chaal, low-lag dealing, live pot clarity, fast rejoin loop',
                    'floating play/support pill fixed near the bottom edge',
                    'horizontal player review rail with edge fade, avatars, location, and rating',
                    'duplicated quote-card track for seamless marquee-like scrolling reviews',
                    'high-atmosphere casino-game scene language: ember haze, chip sparks, neon rim light, spotlight cones, layered smoke, glossy poster glass, and table-felt depth',
                    'arcade-like button energy: gold bevels, inner shine, warm outer glow, press depth, hover lift, sweep highlight, pulse ring, and coin/chip icon accents',
                    'conversion copy should be punchy and cinematic: short target-locale promises, reward urgency, safety proof, and action verbs that feel like a game campaign rather than a corporate brochure',
                    'CTA buttons should feel alive: shine sweep across the surface, soft pulsing glow, tiny chip/coin spark, hover lift, active press, and optional animated arrow/bolt drawn with CSS',
                    'image-text choreography: major body sections should pair copy with a visual companion, not run as text-only grids',
                    'home launch stage must feel like a neon game-room page: floating black dock header, oversized local headline, center poster/table/game board, side command cards, route chips, and bottom play/support pill',
                    'home information architecture requires separate blocks for launch hero, game room entry, game showcase, trust/security, horizontal player review rail, FAQ/rules accordion, and final CTA',
                    'standard full-width photo hero is not enough for the home opening; the image or CSS visual must be composed into a poster/device stage with supporting gameplay cards',
                    'FAQ accordion rows with numbered capsules and plus/minus affordance',
                    'legal/policy pages as centered dark document panels with gold headings',
                    'blog/journal cards with recent-post sidebar and dark editorial surfaces',
                    'about page KPI stat cards, value cards, and initial-based team cards inside a dark gaming shell',
                    'contact page support-channel cards, dark form panel, and map/support block',
                    'subtle animated halos, card-token floats, glow rings, and particle dots',
                    'controlled motion details: slow review marquee, drifting chips/cards, CTA glow pulse, button shine sweep, and hover parallax on game cards',
                    'motion density should be visible but disciplined: 2-4 small CSS animations per major landing page are encouraged, especially hero particles, CTA glow, review rail movement, and game-card hover tilt',
                    'button and nearby description copy must be campaign-grade: short target-locale hooks, concrete room/reward/safety promises from the brief, urgent verbs, and no bland corporate filler',
                    'primary CTA clusters need a visual payoff: button shine, pulse halo, hover lift, active press, tiny chip/coin/arrow accent, and a one-line reassurance or reward hook beside the action',
                    'CSS motion should be visible in the first screen and conversion blocks: glowing CTA, drifting token particles, card tilt, review rail movement, or jackpot meter shimmer, with prefers-reduced-motion fallback',
                    'description blocks should feel like game trailer copy: vivid, compact, benefit-led, and paired with a table/card/chip visual so the page never reads like plain documentation',
                    'magnetic conversion clusters: CTA button, adjacent proof line, reward/safety chip, and tiny moving visual accent should read as one clickable campaign moment',
                    'button-adjacent descriptions must be eye-catching microcopy, not explanatory prose: one promise, one urgency cue, one confidence cue, all rewritten into the target locale',
                    'motion should sell the action: shine sweep, pulse halo, animated arrow nudge, coin/chip spark, review marquee, jackpot shimmer, or card tilt should be visible on landing/conversion sections',
                ],
                'color_system' => [
                    'base' => '#120807 deep casino brown / near-black',
                    'page_black' => '#08090f almost-black app shell',
                    'section_dark' => '#041923 ink blue-green',
                    'section_brown' => '#261108 warm casino brown band',
                    'surface' => '#0b1f28 translucent glass card',
                    'surface_black' => '#050505 high-contrast testimonial/legal card',
                    'accent_gold' => '#ffbf42 jackpot gold',
                    'cta_orange' => '#ff7a2f warm play CTA',
                    'neon_teal' => '#00d5c5 thin active line and FAQ focus',
                    'purple_header' => '#24115f policy/legal header accent used only on document pages',
                    'text' => '#fff4dc warm high-contrast text',
                ],
                'layout_patterns' => [
                    'Home hero: full-bleed dark stage, huge target-locale headline, dominant central table/game visual, compact side benefit cards, one primary play CTA.',
                    'Atmosphere baseline: each non-legal page should feel staged like a premium game launch screen, with layered dark backgrounds, glow fields, chip/card particles, rim-lit cards, and at least one strong visual focal surface.',
                    'Home contract: keep player_reviews and faq_or_rules as independent sections when present; do not collapse them into brand promise, generic trust, or final CTA sections.',
                    'Home opening must not be only a background photo with a floating copy card. Compose a center-stage poster, table lobby, or game board focal surface, then place compact step/signal cards around it.',
                    'Header: use a floating black rounded dock with brand mark, compact nav links, shadow, and one gold/orange play CTA; do not render a plain full-width corporate navbar for this style.',
                    'Hero support cards: use step/signal cards around the central poster for game actions such as pick variant, set boot, play blind/chaal, low-lag dealing, pot clarity, and fast rejoin.',
                    'Hero route band: add compact chips for game variants such as Classic Teen Patti, AK47 Table, Joker Teen Patti, Muflis Table, or Private Teen Patti when the plan includes variants.',
                    'Benefits: angled or staggered glass cards over ink-blue band, each with game/room proof rather than generic service claims.',
                    'Benefits and trust sections should pair text cards with CSS media panels, room miniatures, card-table illustrations, chip stacks, jackpot meters, or verified screenshots; avoid long text-only rows.',
                    'Benefits may use desktop fan-card or mobile orbit-card/constellation treatments, but the content must stay about clear rules, room guidance, fair play, support, game variety, or plan-provided reward facts.',
                    'KPI proof band: compact black stat cards may show active players, rating, uptime, or loading speed when the plan uses those proof points.',
                    'Games: editorial game grid with image-led route-card or bento-card compositions, jackpots/cards/chips, varied card sizes and dark surfaces.',
                    'Games section may combine a large board-title panel with one lead game card and two smaller side cards, or a mobile bento stack with one main card and mini cards.',
                    'Reviews: use a horizontal scrolling or carousel-like player review rail when the section has 4+ reviews; include edge fades, black quote cards, neon-teal left border, avatar/initial, location, rating, and gaming-specific comment.',
                    'Reviews should feel like a player quote track: duplicate enough quote cards for seamless CSS marquee only when the static first set remains readable without motion.',
                    'FAQ: dark accordion with gold/teal dividers and questions about room entry, safety, gameplay, support categories, and planned rewards.',
                    'Blog/news: dark octane-journal layout with post cards, post meta, author/date line, read-more footer, recent posts sidebar, and strategy/update language.',
                    'About: mission/proof page should use a different banner from home: orbit badge, KPI chips, story panel, value cards, and team/operations cards rather than another app-poster hero.',
                    'About page can show proof stats such as active users, rating, uptime, and loading speed when the plan uses those proof points; otherwise use qualitative proof chips.',
                    'Contact/CTA: player support identity, not a plain corporate contact form; separate help, room, account-safety, and issue-category actions.',
                    'Contact: use support-channel cards, help-category chips, a dark form panel, and a support visual such as headset badge, support console, message stack, or room-help card; channel values may come from the plan, but placeholders, malformed emails, fake numbers, and raw prompt labels must never be visible.',
                    'Legal/policy/cookie pages: use a legal-content document-card composition with dark wrapper, gold/purple header, numbered sections, readable paragraphs, and retained gaming shell.',
                    'Persistent conversion: a small floating play/support pill may appear near the bottom-right when the page is long, provided it does not block content on mobile.',
                    'CTA animation pattern: primary buttons may use CSS-only shine sweep, glow pulse, layered shadow, coin/chip icon dot, and press translateY states. Keep motion subtle, non-blocking, and disabled under prefers-reduced-motion.',
                    'CTA copy pattern: button labels and nearby microcopy must be direct and high-energy in the target locale, for example start playing, enter room, claim bonus, review rules, or equivalent localized phrases when the brief supports them. Avoid neutral corporate labels such as learn more, submit, details, or service unless the page role truly needs them.',
                    'Interaction rhythm: hero CTA, floating play/support pill, game cards, and review cards should expose hover/focus states with transform, shadow, border glow, or background shift. Use @keyframes for CTA shine/pulse and review marquee when relevant.',
                    'Conversion-copy stack: every play/support/final CTA block should include a sharp headline, one compact proof or reward line, one high-energy primary button, and one micro reassurance chip. Rewrite all of these into the target locale; never expose plan wording.',
                    'Dynamic emphasis: conversion blocks should prefer at least one scoped CSS animation such as shine sweep, pulse halo, review-track scroll, chip drift, jackpot shimmer, or button arrow nudge. The animation must decorate the message, not replace readable content.',
                    'Magnetic CTA cluster: pair every primary CTA with a short nearby hook line and one tiny visual cue such as a chip dot, arrow, badge, or reward pill; make the cluster feel active through scoped CSS motion and hover/focus/press states.',
                    'Descriptions near buttons must be written like launch-page copy, not documentation. Use urgent target-locale verbs, specific app/game benefit, and a trust/reward cue from the brief or frozen plan.',
                    'Primary conversion sections should expose visible default-state motion through one scoped keyframes animation when CSS is available; hover-only polish is not enough for a neon game landing page.',
                    'Image-text rhythm: every major non-legal body section should compose text with a visual companion. If no verified image is available, build a CSS-only table screen, game board, card fan, chip stack, avatar rail, support-message stack, or rulebook panel.',
                ],
                'image_strategy' => [
                    'Prefer verified lobby scene, card table, chips, mahjong/poker props, room UI, or game tile assets when available.',
                    'If no verified image exists, create CSS-only gaming visuals from cards, chips, jackpot panels, glow rings, and phone/poster frames; never render broken images or generic placeholders.',
                    'The main visual should reveal game room/table state, not a blurred stock atmosphere.',
                    'Every major body section except dense legal text should include a visual companion: verified image, CSS table frame, card-table panel, chip stack, jackpot meter, avatar rail, rulebook document, support-message stack, or game-tile art.',
                    'Text-only card grids are a fallback of last resort. When no image asset exists, use CSS-only illustrated media blocks beside or above the copy so the page keeps game atmosphere.',
                    'Each page opening visual must fit page identity: about uses mission/proof stage, contact uses support channel stage, policy uses calm rulebook/support visual.',
                    'Player-review rails may use avatar photos or safe initials; do not invent real personal identities beyond the plan.',
                    'Blog cards should not show broken thumbnails or literal placeholder values such as cover_image_value; if no article image exists, use dark card-table/card-token art direction instead of an empty image box.',
                    'Legal/contact/about pages do not need big game screenshots; they may use CSS-only badges, icons, rings, initials, stat panels, and document surfaces while keeping the same gaming shell.',
                ],
                'cta_style' => 'Primary CTA is a compact gold/orange play button with high-energy target-locale copy, heavy weight, glossy bevel, inner highlight, warm outer glow, hover lift, press depth, and direct play/support wording. Add CSS-only button effects such as shine sweep, pulse ring, chip/coin spark, animated arrow/bolt accent, or soft neon halo; include :hover, :focus-visible, and :active states. When CSS budget allows, primary conversion buttons should include a scoped pseudo-element shine plus one component-prefixed @keyframes animation and a prefers-reduced-motion fallback. The words around the CTA must also sell: use a short proof/reward/safety hook and urgent localized action verbs instead of bland labels. For long pages, use a fixed bottom-right play/support pill with icon/tiny avatar, two-line copy, glow pulse, and mobile-safe positioning. Secondary actions may be dark outlined chips, read-more links, or support links, but they still need hover glow and a clear active state.',
                'forbidden_patterns' => [
                    'cream/light corporate layout as the dominant page system',
                    'same banner shell reused across home/about/contact/policy pages',
                    'home opening rendered as a normal rectangular photo cover plus text card, without center poster/device focal staging or side command cards',
                    'flat buttons with no depth, glow, hover/press affordance, or conversion energy',
                    'weak CTA wording such as generic Learn More / Details / Submit when the block is meant to claim, enter a room, play, or contact support',
                    'motionless game launch pages when the style direction asks for particles, review rail, CTA glow, or card hover energy',
                    'body sections that are only paragraphs and equal cards with no visual companion or gaming atmosphere',
                    'plain full-width corporate navbar for the neon gaming style',
                    'generic three green-outline cards repeated across sections',
                    'static corporate testimonial grid when the plan calls for player reviews; prefer game-specific review rail or staggered cards',
                    'SaaS feature-grid look, lawyer/consulting/corporate trust-block look, or coffee/editorial calm look',
                    'placeholder phone/email/WhatsApp values, malformed contact fragments, or raw prompt/source labels',
                    'service-time, response-speed, or handling-time wording copied as blueprint text instead of final visitor copy',
                    'placeholder image boxes, fake asset URLs, or broken img tags',
                    'blog cards with empty/broken thumbnails',
                    'literal asset placeholders such as cover_image_value',
                    'review sections rendered as static equal-width corporate testimonial grids when a rail/marquee composition is feasible',
                    'contact forms or legal pages that look disconnected from the gaming visual system',
                    'emoji-heavy headings or generic AI gradient orbs',
                ],
                'block_rules' => [
                    'header' => 'Use a floating black rounded navigation dock with brand mark, compact links, active/hover depth, and a strong gold/orange play CTA. Keep it premium and dense like a neon game-room site, not a flat corporate bar.',
                    'opening_banner' => 'Use page identity first. Home can be central game poster; about should show mission/fair-play proof; contact should show support channels; FAQ/policy should feel like game rules/help, not a copied hero. Add atmosphere with rim light, card/chip particles, glow rings, and one page-specific focal visual.',
                    'home_opening' => 'For the home page opening, prefer an Octane launch-stage composition: oversized localized headline, center poster/table/game-lobby focal, side step/signal cards, route chips, particle/halo texture, compact gold play CTA with shine/glow states, and optional bottom floating play/support pill. Do not output only a photo-cover banner plus a generic text panel.',
                    'download_cta' => 'Mention app/download only when the brief asks for it. Mention bonus/reward/free chips when the plan or brief includes that offer; rewrite it naturally instead of exposing blueprint text. Button copy should be urgent, concrete, and localized; style the button with shine/pulse/press states and a small chip/coin/arrow accent.',
                    'conversion_copy' => 'Descriptions near CTAs must be short, vivid, and benefit-led: combine one room/game promise, one trust or speed cue from the plan, and one immediate next step. Avoid long corporate paragraphs, generic learn-more language, and repeated wording across blocks.',
                    'benefits' => 'Benefits must include clear rules, room variety, fair play, support facts, player proof, or planned reward facts. Pair the copy with visual panels such as table UI, chip stacks, card-table fragments, guide cards, or jackpot meters.',
                    'games' => 'Use game names and image-led or CSS-illustrated visual cards/tiles, not generic service categories.',
                    'faq' => 'Questions should cover room entry, safety, gameplay, support, and planned rewards; use accordion-like rows with strong dark contrast.',
                    'reviews' => 'Player comments must sound like real table/game experience, not generic company testimonials. For 4+ reviews, prefer a horizontal scrolling rail, marquee, or carousel composition with edge fade, black quote cards, neon-teal left border, avatar/initial, city/region, star/rating, and one concrete room/game detail. Use CSS-only motion where possible and keep all cards readable without relying on motion.',
                    'blog' => 'Use an Octane Journal/newsroom feel: strategy tips, patch/update stories, post-card grid, post meta/date/author, read-more footer, recent-post sidebar, dark surfaces and gold/teal links. Avoid a generic corporate blog grid. Never output broken thumbnails or cover_image_value.',
                    'about' => 'Use brand story, KPI proof, orbit/ring badge, value cards, initial/team cards, and operational credibility. The about page must not reuse the home poster hero.',
                    'contact' => 'Use support-channel info cards, help categories, dark form panel, and map/support block when the plan needs them. Never output placeholders or malformed values such as support@ .com; if exact channel values are absent, use polished player support and room-help categories.',
                    'legal_policy' => 'Terms/privacy/cookie pages should look like a premium rulebook: legal-content wrapper, dark centered document card, gold numbered sections, purple or ink header, high contrast text, and footer/legal age disclaimer when relevant.',
                    'floating_download' => 'A floating play/support pill can reinforce conversion on long pages. It must be compact, bottom-edge aligned, non-overlapping on mobile, and secondary to the page content.',
                    'button_motion' => 'For primary CTAs, include CSS-only animation hooks such as `@keyframes pb-c-shine`, `@keyframes pb-c-pulse`, `@keyframes pb-c-arrow-nudge`, or scoped equivalent names. Use pseudo-elements for shine/halo when possible, add default-state glow or shine, :hover lift, :active press, and prefers-reduced-motion fallback. Keep all selectors scoped to the component id/prefix.',
                    'cta_description_motion' => 'Treat button labels and nearby descriptions as one design object: vivid target-locale promise line, reward/trust chip, animated arrow or coin accent, and compact layout that draws the eye without hiding content.',
                    'visual_pairing' => 'Major body blocks should not be text-only. Pair copy with a verified image or a CSS-only table/game visual; for reviews use avatar rail/marquee, for support use message stack/help console, for legal use rulebook/document shell.',
                    'motion_system' => 'Use a small motion system, not random decoration: CTA shine/pulse, review rail scroll, chip/card drift, jackpot shimmer, and game-card hover tilt. Keep animations scoped, balanced, and readable when motion is disabled.',
                ],
                'qa_rules' => [
                    '首屏必须有暗色游戏质感、强视觉焦点、直接进入牌桌或开始游戏 CTA。',
                    '页面之间的 opening banner 构图必须不同，并能看出页面身份。',
                    '至少核心页面要出现游戏房间、玩法规则、奖励、筹码/卡牌、FAQ/评论/游戏列表等语义。',
                    '评论区如果存在多条玩家评价，优先检查是否具备横向滚动/轮播感、边缘淡出、头像、评分/地区和游戏体验细节。',
                    '评论滚动可以使用重复 quote-card 轨道制造无缝 marquee，但静态状态下第一组评论也必须可读。',
                    '长页面允许悬浮开始游戏或客服按钮，但不得遮挡正文、FAQ、表单或移动端底部内容。',
                    '博客必须具备 Octane Journal 感：post-card、日期作者、Recent Posts 侧栏或等价结构，且不得出现 cover_image_value 或破图。',
                    '关于页必须具备价值/团队或运营可信度结构，联系页必须具备支持渠道/表单/帮助分类结构，法务页必须具备 legal document shell；不得输出占位联系方式、破碎邮箱或提示词式说明。',
                    '博客、关于、联系、条款、隐私、Cookie 页面必须继承棋牌发行站的暗色游戏外壳，同时拥有各自页面身份。',
                    '不得把棋牌方向污染到非棋牌会话。',
                    '不得用占位图、假图片 URL 或重复 shell 通过验收。',
                    'Header should read as a premium floating black game dock with compact play CTA, not a generic full-width corporate nav.',
                    'Home opening should show game-publisher launch staging: central poster/device/game board focal surface plus side command/proof cards. A plain background-photo hero with a copy card is insufficient.',
                ],
                'example_refs' => [
                    [
                        'type' => 'url',
                        'label' => 'Neon card-game reference site',
                        'url' => 'https://www.example.com/',
                        'note' => '用于提炼方向词：悬浮黑色导航、中心海报、步骤/信号小卡、横向玩家评价、FAQ 手风琴、博客资讯、关于页 KPI、联系支持卡、法务文档卡和固定行动胶囊。',
                    ],
                ],
                'supplemental_prompt' => 'This style is not a hardcoded page. Treat it as a vertical art-direction contract and recombine it with the actual user brief, selected pages, theme, assets, and block identity. Reference-site details are vocabulary and composition guidance only; never copy exact content, fake contact data, placeholder values, malformed email/phone fragments, raw blueprint sentences, or a fixed page shell. Marketing/support/reward copy should follow the brief and frozen plan, then be rewritten as final visitor copy. For this neon card-game style, button labels and descriptions are part of the visual design: make them punchy, localized, conversion-led, and supported by visible CSS motion rather than plain static text. Primary conversion clusters should feel alive in the default state through scoped shine, pulse, arrow/coin nudge, review rail motion, or jackpot shimmer while staying readable with reduced motion.',
                'version' => 13,
                'status' => AiStyle::STATUS_ACTIVE,
                'readonly' => true,
                'selectable' => true,
                'exists' => true,
            ],
        ];
    }
}
