<?php

return [
    "name" => 'Weline_Theme',
    "version" => '1.0.6',
    "requires" => [
        'Weline_Backend' => '*',
        'Weline_Framework' => '*',
        'Weline_I18n' => '*',
        'Weline_Meta' => '*',
        'Weline_SystemConfig' => '*',
        'Weline_Widget' => '*',
    ],
    "optional" => [
        'Weline_Ai' => '*',
        'Weline_Cdn' => '*',
        'Weline_Eav' => '*',
        'Weline_FileManager' => '*',
        'Weline_ModuleRouter' => '*',
        'Weline_Seo' => '*',
        'Weline_Server' => '*',
        'Weline_Websites' => '*',
    ],
    "provides" => [
        \Weline\Widget\Api\WidgetLibraryProviderInterface::class => \Weline\Theme\Integration\Widget\ThemeWidgetLibraryProvider::class,
        'theme.target_type.website' => \Weline\Theme\Integration\Websites\WebsiteTargetTypeProvider::class,
        \Weline\Websites\Api\AiWorkbench\VirtualThemeStoreInterface::class => \Weline\Theme\Integration\Websites\VirtualThemeStore::class,
        \Weline\Backend\Api\View\ThemePreviewModeProviderInterface::class => \Weline\Theme\Integration\Backend\ThemePreviewModeProvider::class,
        \Weline\Framework\Runtime\ThemeContextProviderInterface::class => \Weline\Theme\Service\ThemeContextService::class,
        \Weline\Framework\Runtime\FpcWarmupProviderInterface::class => \Weline\Theme\Api\Runtime\FpcWarmupProvider::class,
        \Weline\Framework\View\FrontendLayoutProviderInterface::class => \Weline\Theme\Api\View\FrontendLayoutProvider::class,
        \Weline\Framework\View\BackendLayoutProviderInterface::class => \Weline\Theme\Api\View\BackendLayoutProvider::class,
        \Weline\Theme\Api\Asset\StaticAssetPublisherInterface::class => \Weline\Theme\Api\Asset\StaticAssetPublisher::class,
        \Weline\Theme\Api\Layout\LayoutWorkspaceInterface::class => \Weline\Theme\Service\LayoutWorkspace::class,
        \Weline\Theme\Api\View\PreviewThemeModeResolverInterface::class => \Weline\Theme\Service\PreviewThemeModeResolver::class,
        \Weline\Theme\Api\View\ComponentMetaReaderInterface::class => \Weline\Theme\Service\ComponentMetaReader::class,
        \Weline\Framework\View\CompileStateResetterInterface::class => \Weline\Theme\Api\Runtime\CompileStateResetter::class,
        'request_resetter.Weline_Theme' => \Weline\Theme\Api\Runtime\RequestResetter::class,
        'process_cache_resetter.Weline_Theme' => \Weline\Theme\Api\Runtime\ProcessCacheResetter::class,
        'resource_compiler.less' => \Weline\Theme\Console\Resource\Compiler\Less::class,
        'resource_compiler.welineModules' => \Weline\Theme\Console\Resource\Compiler\WelineModules::class,
        'template_cache_policy.Weline_Theme' => \Weline\Theme\Api\View\TemplateCachePolicyProvider::class,
        'i18n.javascript_module_config.Weline_Theme' => \Weline\Theme\Api\I18n\ThemeJavascriptModuleConfigProvider::class,
    ],
];
