<?php
declare(strict_types=1);

/**
 * Weline Framework
 * 
 * @DESC         | PHP 类文件生成器
 * @Author       | Weline Framework
 * @Package      | Weline\Framework\View\Taglib\Generator
 */

namespace Weline\Framework\View\Taglib\Generator;

use Weline\Framework\View\Taglib\Ast\ProgramNode;

/**
 * PHP 类文件生成器
 * 
 * 将编译后的模板生成为独立 PHP 类文件
 * 便于 OPcache 缓存字节码
 */
final class ClassGenerator
{
    /**
     * 代码生成器
     */
    private readonly CodeGenerator $codeGenerator;

    public function __construct(?CodeGenerator $codeGenerator = null)
    {
        $this->codeGenerator = $codeGenerator ?? new CodeGenerator();
    }

    /**
     * 生成 PHP 类文件内容
     * 
     * @param ProgramNode $ast 编译后的 AST
     * @param string $className 类名
     * @param string $namespace 命名空间（可选）
     * @return string PHP 类文件内容
     */
    public function generate(ProgramNode $ast, string $className, string $namespace = ''): string
    {
        $body = $this->codeGenerator->generate($ast);
        
        // 转义特殊字符
        $safeBody = $this->escapeForOutput($body);
        
        $namespaceDecl = $namespace !== '' 
            ? "namespace {$namespace};\n\n" 
            : '';

        $php = '<' . '?php';
        $close = '?' . '>';

        return <<<PHP
{$php}
declare(strict_types=1);

/**
 * Generated by Weline Taglib Compiler
 * DO NOT EDIT - This file is auto-generated
 * 
 * Source: {$ast->fileName}
 * Generated: {$this->getTimestamp()}
 */

{$namespaceDecl}final class {$className}
{
    /**
     * 渲染模板
     * 
     * @param array \$__vars 模板变量
     * @return string 渲染结果
     */
    public static function render(array \$__vars): string
    {
        extract(\$__vars, EXTR_SKIP);
        ob_start();
        {$close}{$safeBody}{$php}
        return ob_get_clean();
    }
    
    /**
     * 渲染并直接输出
     * 
     * @param array \$__vars 模板变量
     */
    public static function display(array \$__vars): void
    {
        echo static::render(\$__vars);
    }
}

PHP;
    }

    /**
     * 从模板路径生成类名
     */
    public function generateClassName(string $templatePath): string
    {
        // 移除扩展名
        $name = pathinfo($templatePath, PATHINFO_FILENAME);
        
        // 移除路径中的特殊字符
        $name = preg_replace('/[^a-zA-Z0-9_]/', '_', $name);
        
        // 确保以字母开头
        if (!ctype_alpha($name[0] ?? '')) {
            $name = 'Template_' . $name;
        }
        
        // 添加哈希以确保唯一性
        $hash = substr(hash('xxh3', $templatePath), 0, 8);
        
        return "Compiled_{$name}_{$hash}";
    }

    /**
     * 生成完整的类文件并写入
     * 
     * @return string 生成的文件路径
     */
    public function generateAndSave(
        ProgramNode $ast,
        string $templatePath,
        string $outputDir
    ): string {
        $className = $this->generateClassName($templatePath);
        $content = $this->generate($ast, $className);
        
        // 确保目录存在
        if (!is_dir($outputDir)) {
            mkdir($outputDir, 0755, true);
        }
        
        $filePath = $outputDir . DIRECTORY_SEPARATOR . $className . '.php';
        
        // 原子写入
        $tmpFile = $filePath . '.tmp.' . getmypid();
        file_put_contents($tmpFile, $content, LOCK_EX);
        
        if (file_exists($filePath)) {
            unlink($filePath);
        }
        rename($tmpFile, $filePath);
        
        return $filePath;
    }

    /**
     * 转义输出内容
     */
    private function escapeForOutput(string $body): string
    {
        // 确保不会意外关闭 PHP 块
        // 这里不需要特殊处理，因为 $body 已经是有效的 PHP/HTML 混合内容
        return $body;
    }

    /**
     * 获取时间戳
     */
    private function getTimestamp(): string
    {
        return date('Y-m-d H:i:s');
    }
}
