<?php
/**
 * 系统事件页面（内容模板）
 *
 * @var \Weline\Framework\View\Template $this
 */
?>

<div class='row'>
    <div class='col-12'>
        <div class='page-title-box d-sm-flex align-items-center justify-content-between'>
            <h4 class='mb-sm-0'><?= __('系统事件') ?></h4>
            <div class='page-title-right'>
                <ol class='breadcrumb m-0'>
                    <li class='breadcrumb-item'><a href='javascript: void(0);'><?= __('系统') ?></a></li>
                    <li class='breadcrumb-item active'><?= __('系统事件') ?></li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class='row'>
    <template>Weline_Component::message.phtml</template>
</div>

<div class='row'>
    <div class='col-12'>
        <div class='card'>
            <div class='card-body'>
                <h4 class='card-title'><?= __('观察事件') ?></h4>
                <p class='card-title-desc'><?= __('此列表是系统中可监听的事件列表，方便开发者使用观察者模式查阅并订阅系统事件消息。') ?></p>
                <?php
                $events = $this->getData('events');
                ?>
                <div class='table-rep-plugin'>
                    <div class='table-responsive mb-0' data-pattern='priority-columns'>
                        <table id='tech-companies-1' class='table table-striped table-bordered'>
                            <thead>
                            <tr>
                                <th data-priority='1'><?= __('ID') ?></th>
                                <th data-priority='1'><?= __('事件名') ?></th>
                                <th data-priority='3'><?= __('示例类') ?></th>
                                <th data-priority='1'><?= __('是否禁用') ?></th>
                                <th data-priority='3'><?= __('是否共享') ?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            foreach ($events as $file => $event) :
                                ?>
                                <tr>
                                    <td></td>
                                    <th colspan="4" class='co-name'><?= $file ?></th>
                                </tr>
                                <?php
                                foreach ($event as $name => $instances) {
                                    ?>
                                    <tr>
                                        <td></td>
                                        <th colspan="4" class='co-name'><?= $name ?></th>
                                    </tr>
                                    <?php
                                    foreach ($instances as $key => $instance) {
                                        ?>
                                        <tr>
                                            <th class="co-name"><?= $key ?></th>
                                            <td><?= $instance['name'] ?></td>
                                            <td><?= $instance['instance'] ?></td>
                                            <td><?= $instance['disabled'] ?></td>
                                            <td><?= $instance['shared'] ?></td>
                                        </tr>
                                        <?php
                                    }
                                    ?>
                                    <?php
                                }
                                ?>
                            <?php
                            endforeach;
                            ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
