<?php

declare(strict_types=1);

namespace LearningMcp;

/**
 * MCP-owned Cursor hooks.json that feeds Agent lifecycle into learningctl.
 * Regenerated by ensure-project-guidance; do not hand-edit as authority.
 */
final class HostCursorHooksGenerator
{
    public const HOOKS_BASENAME = 'hooks.json';

    public const GENERATOR_MARKER = 'weline-mcp-cursor-hooks-generator';

    /**
     * @return array{
     *   schema_version: string,
     *   ready: bool,
     *   changed: bool,
     *   written: list<string>,
     *   paths: array<string, string>,
     *   reason: string
     * }
     */
    public static function sync(string $repoRoot, string $mcpRoot, string $configPath = ''): array
    {
        $repoRoot = rtrim($repoRoot, "/\\");
        $mcpRoot = rtrim($mcpRoot, "/\\");
        $cursorDir = $repoRoot . DIRECTORY_SEPARATOR . '.cursor';
        $hooksPath = $cursorDir . DIRECTORY_SEPARATOR . self::HOOKS_BASENAME;
        $php = PHP_BINARY;
        $adapter = $mcpRoot . DIRECTORY_SEPARATOR . 'bin' . DIRECTORY_SEPARATOR . 'cursor-learning-hook';
        $config = $configPath !== '' ? $configPath : Config::defaultPath();
        $dataDir = self::projectDataDir($repoRoot, $config);
        $command = self::shellCommand([
            $php,
            $adapter,
            '--config',
            $config,
            '--data-dir',
            $dataDir,
            '--event',
        ]);

        $document = [
            'version' => 1,
            'hooks' => [
                'sessionStart' => [[
                    'command' => $command . ' sessionStart',
                    'timeout' => 8,
                ]],
                'sessionEnd' => [[
                    'command' => $command . ' sessionEnd',
                    'timeout' => 8,
                ]],
                'stop' => [[
                    'command' => $command . ' stop',
                    'timeout' => 8,
                ]],
                'beforeSubmitPrompt' => [[
                    'command' => $command . ' beforeSubmitPrompt',
                    'timeout' => 5,
                ]],
                'preToolUse' => [[
                    'command' => $command . ' preToolUse',
                    'timeout' => 5,
                ]],
                'postToolUse' => [[
                    'command' => $command . ' postToolUse',
                    'timeout' => 5,
                ]],
                'afterFileEdit' => [[
                    'command' => $command . ' afterFileEdit',
                    'timeout' => 5,
                ]],
                'preCompact' => [[
                    'command' => $command . ' preCompact',
                    'timeout' => 5,
                ]],
            ],
        ];
        // Marker kept as trailing newline comment is invalid JSON; path is MCP-generated only.
        $content = Json::encode($document) . "\n";

        if (!is_dir($cursorDir) && !mkdir($cursorDir, 0775, true) && !is_dir($cursorDir)) {
            return [
                'schema_version' => 'host-cursor-hooks-sync.v1',
                'ready' => false,
                'changed' => false,
                'written' => [],
                'paths' => ['hooks' => $hooksPath],
                'reason' => 'mkdir_failed',
            ];
        }

        $previous = is_file($hooksPath) ? (string) file_get_contents($hooksPath) : null;
        $changed = $previous !== $content;
        if ($changed) {
            if (file_put_contents($hooksPath, $content) === false) {
                return [
                    'schema_version' => 'host-cursor-hooks-sync.v1',
                    'ready' => false,
                    'changed' => false,
                    'written' => [],
                    'paths' => ['hooks' => $hooksPath],
                    'reason' => 'write_failed',
                ];
            }
        }

        return [
            'schema_version' => 'host-cursor-hooks-sync.v1',
            'ready' => true,
            'changed' => $changed,
            'written' => $changed ? [self::HOOKS_BASENAME] : [],
            'paths' => ['hooks' => $hooksPath],
            'reason' => $changed ? 'updated' : 'unchanged',
        ];
    }

    /** @param list<string> $parts */
    private static function shellCommand(array $parts): string
    {
        $quoted = [];
        foreach ($parts as $part) {
            $quoted[] = "'" . str_replace("'", "'\\''", $part) . "'";
        }

        return implode(' ', $quoted);
    }

    private static function projectDataDir(string $repoRoot, string $configPath): string
    {
        $config = Config::load($configPath);
        $resolved = ProjectResolver::resolve($repoRoot);
        $fingerprint = (string) ($resolved['project']['root_fingerprint'] ?? '');
        $hash = str_starts_with($fingerprint, 'sha256:') ? substr($fingerprint, 7) : $fingerprint;
        $configured = rtrim($config->dataDir(), "/\\");
        if ($hash !== '' && str_ends_with($configured, $hash)) {
            return $configured;
        }
        if ($hash === '') {
            return $configured;
        }

        return $configured . DIRECTORY_SEPARATOR . 'projects' . DIRECTORY_SEPARATOR . $hash;
    }
}
