<?php

declare(strict_types=1);

return [
    'pixel_overview' => [
        'name' => '像素概览',
        'description' => '展示像素事件、独立访客、事件类型和处理率。',
        'type' => 'stats',
        'code' => 'pixel_overview',
        'area' => 'backend',
        'template' => 'Weline_Visitor::templates/dashboard/widgets/pixel-overview.phtml',
        'page_layouts' => ['dashboard'],
        'position' => ['dashboard-summary'],
        'slot' => 'dashboard-summary',
        'supports' => ['dashboard-widget', 'dashboard-slot-summary', 'dashboard-stat', 'dashboard-kpi'],
        'default_injections' => [[
            'layout_type' => 'dashboard',
            'layout_option' => 'default',
            'default_view' => 'weline_visitor_event_statistics',
            'target_type' => 'website',
            'slot' => 'dashboard-summary',
            'area' => 'content',
            'sort_order' => 50,
            'required' => true,
            'reason' => '安装访客统计后自动展示像素概览',
            'config' => [
                'dashboard_layout' => [
                    'colSpan' => 4,
                    'rowSpan' => 1,
                    'sortOrder' => 50,
                ],
            ],
        ]],
        'params' => [
            'range' => [
                'default' => '7d',
                'type' => 'select',
                'label' => '统计范围',
                'options' => [
                    'today' => '今日',
                    'yesterday' => '昨日',
                    '7d' => '近 7 天',
                    '30d' => '近 30 天',
                    '90d' => '近 90 天',
                ],
            ],
            'website_id' => [
                'default' => '',
                'type' => 'string',
                'label' => '站点 ID',
                'description' => '留空时跟随当前 Dashboard 站点。',
            ],
        ],
    ],
    'pixel_event_trend' => [
        'name' => '像素事件趋势',
        'description' => '展示像素事件近几日变化趋势。',
        'type' => 'chart',
        'code' => 'pixel_event_trend',
        'area' => 'backend',
        'template' => 'Weline_Visitor::templates/dashboard/widgets/pixel-event-trend.phtml',
        'page_layouts' => ['dashboard'],
        'position' => ['dashboard-analysis'],
        'slot' => 'dashboard-analysis',
        'supports' => ['dashboard-widget', 'dashboard-slot-analysis', 'dashboard-chart', 'dashboard-trend'],
        'default_injections' => [[
            'layout_type' => 'dashboard',
            'layout_option' => 'default',
            'default_view' => 'weline_visitor_event_statistics',
            'target_type' => 'website',
            'slot' => 'dashboard-analysis',
            'area' => 'content',
            'sort_order' => 60,
            'required' => true,
            'reason' => '安装访客统计后自动展示像素事件趋势',
            'config' => [
                'dashboard_layout' => [
                    'colSpan' => 5,
                    'rowSpan' => 2,
                    'sortOrder' => 60,
                ],
            ],
        ]],
        'params' => [
            'range' => [
                'default' => '7d',
                'type' => 'select',
                'label' => '统计范围',
                'options' => [
                    '7d' => '近 7 天',
                    '30d' => '近 30 天',
                    '90d' => '近 90 天',
                ],
            ],
            'website_id' => [
                'default' => '',
                'type' => 'string',
                'label' => '站点 ID',
                'description' => '留空时跟随当前 Dashboard 站点。',
            ],
        ],
    ],
    'pixel_top_events' => [
        'name' => '热门像素事件',
        'description' => '展示当前范围内触发最多的像素事件。',
        'type' => 'table',
        'code' => 'pixel_top_events',
        'area' => 'backend',
        'template' => 'Weline_Visitor::templates/dashboard/widgets/pixel-top-events.phtml',
        'page_layouts' => ['dashboard'],
        'position' => ['dashboard-detail'],
        'slot' => 'dashboard-detail',
        'supports' => ['dashboard-widget', 'dashboard-slot-detail', 'dashboard-table', 'dashboard-list'],
        'default_injections' => [[
            'layout_type' => 'dashboard',
            'layout_option' => 'default',
            'default_view' => 'weline_visitor_event_statistics',
            'target_type' => 'website',
            'slot' => 'dashboard-detail',
            'area' => 'content',
            'sort_order' => 70,
            'required' => true,
            'reason' => '安装访客统计后自动展示热门像素事件',
            'config' => [
                'dashboard_layout' => [
                    'colSpan' => 9,
                    'rowSpan' => 1,
                    'sortOrder' => 70,
                ],
            ],
        ]],
        'params' => [
            'range' => [
                'default' => '7d',
                'type' => 'select',
                'label' => '统计范围',
                'options' => [
                    'today' => '今日',
                    '7d' => '近 7 天',
                    '30d' => '近 30 天',
                    '90d' => '近 90 天',
                ],
            ],
            'website_id' => [
                'default' => '',
                'type' => 'string',
                'label' => '站点 ID',
                'description' => '留空时跟随当前 Dashboard 站点。',
            ],
        ],
    ],
    'pixel_realtime' => [
        'name' => '像素实时动向',
        'description' => '展示最近一小时像素事件触发情况。',
        'type' => 'list',
        'code' => 'pixel_realtime',
        'area' => 'backend',
        'template' => 'Weline_Visitor::templates/dashboard/widgets/pixel-realtime.phtml',
        'page_layouts' => ['dashboard'],
        'position' => ['dashboard-side', 'dashboard-detail'],
        'slot' => 'dashboard-side',
        'supports' => ['dashboard-widget', 'dashboard-slot-side', 'dashboard-list', 'dashboard-status', 'dashboard-stat'],
        'default_injections' => [[
            'layout_type' => 'dashboard',
            'layout_option' => 'default',
            'default_view' => 'weline_visitor_event_statistics',
            'target_type' => 'website',
            'slot' => 'dashboard-side',
            'area' => 'content',
            'sort_order' => 80,
            'required' => true,
            'reason' => '安装访客统计后自动展示像素实时动向',
            'config' => [
                'dashboard_layout' => [
                    'colSpan' => 3,
                    'rowSpan' => 2,
                    'sortOrder' => 80,
                ],
            ],
        ]],
        'params' => [
            'website_id' => [
                'default' => '',
                'type' => 'string',
                'label' => '站点 ID',
                'description' => '留空时跟随当前 Dashboard 站点。',
            ],
        ],
    ],
    'pixel_engagement' => [
        'name' => '像素参与度',
        'description' => '会话、参与率、跳出率与平均停留，对齐 GA4 参与指标。',
        'type' => 'stats',
        'code' => 'pixel_engagement',
        'area' => 'backend',
        'template' => 'Weline_Visitor::templates/dashboard/widgets/pixel-engagement.phtml',
        'page_layouts' => ['dashboard'],
        'position' => ['dashboard-summary'],
        'slot' => 'dashboard-summary',
        'supports' => ['dashboard-widget', 'dashboard-slot-summary', 'dashboard-stat', 'dashboard-kpi'],
        'default_injections' => [[
            'layout_type' => 'dashboard',
            'layout_option' => 'default',
            'default_view' => 'weline_visitor_event_statistics',
            'target_type' => 'website',
            'slot' => 'dashboard-summary',
            'area' => 'content',
            'sort_order' => 55,
            'required' => true,
            'reason' => '安装访客统计后自动展示参与度 KPI',
            'config' => [
                'dashboard_layout' => [
                    'colSpan' => 4,
                    'rowSpan' => 1,
                    'sortOrder' => 55,
                ],
            ],
        ]],
        'params' => [
            'range' => [
                'default' => '7d',
                'type' => 'select',
                'label' => '统计范围',
                'options' => [
                    'today' => '今日',
                    '7d' => '近 7 天',
                    '30d' => '近 30 天',
                    '90d' => '近 90 天',
                ],
            ],
            'website_id' => [
                'default' => '',
                'type' => 'string',
                'label' => '站点 ID',
                'description' => '留空时跟随当前 Dashboard 站点。',
            ],
        ],
    ],
    'pixel_pages' => [
        'name' => '热门页面',
        'description' => '按路径汇总浏览量、访客与平均停留。',
        'type' => 'table',
        'code' => 'pixel_pages',
        'area' => 'backend',
        'template' => 'Weline_Visitor::templates/dashboard/widgets/pixel-pages.phtml',
        'page_layouts' => ['dashboard'],
        'position' => ['dashboard-detail'],
        'slot' => 'dashboard-detail',
        'supports' => ['dashboard-widget', 'dashboard-slot-detail', 'dashboard-table', 'dashboard-list'],
        'default_injections' => [[
            'layout_type' => 'dashboard',
            'layout_option' => 'default',
            'default_view' => 'weline_visitor_event_statistics',
            'target_type' => 'website',
            'slot' => 'dashboard-detail',
            'area' => 'content',
            'sort_order' => 75,
            'required' => true,
            'reason' => '安装访客统计后自动展示热门页面',
            'config' => [
                'dashboard_layout' => [
                    'colSpan' => 4,
                    'rowSpan' => 1,
                    'sortOrder' => 75,
                ],
            ],
        ]],
        'params' => [
            'range' => [
                'default' => '7d',
                'type' => 'select',
                'label' => '统计范围',
                'options' => [
                    'today' => '今日',
                    '7d' => '近 7 天',
                    '30d' => '近 30 天',
                    '90d' => '近 90 天',
                ],
            ],
            'website_id' => [
                'default' => '',
                'type' => 'string',
                'label' => '站点 ID',
                'description' => '留空时跟随当前 Dashboard 站点。',
            ],
        ],
    ],
    // E01：流量渠道部件（走报表引擎 catalog pixel_channels；E05 已写入 Installer 种子）
    'pixel_channels' => [
        'name' => '流量渠道',
        'description' => '按 channel_code 聚合事件与价值，可下钻事件列表。',
        'type' => 'table',
        'code' => 'pixel_channels',
        'area' => 'backend',
        'template' => 'Weline_Visitor::templates/dashboard/widgets/pixel-channels.phtml',
        'page_layouts' => ['dashboard'],
        'position' => ['dashboard-detail'],
        'slot' => 'dashboard-detail',
        'supports' => ['dashboard-widget', 'dashboard-slot-detail', 'dashboard-table', 'dashboard-list'],
        'default_injections' => [[
            'layout_type' => 'dashboard',
            'layout_option' => 'default',
            'default_view' => 'weline_visitor_event_statistics',
            'target_type' => 'website',
            'slot' => 'dashboard-detail',
            'area' => 'content',
            'sort_order' => 78,
            'required' => false,
            'reason' => '流量渠道报表部件（E01）；Installer 种子已含本 code（E05）',
            'config' => [
                'dashboard_layout' => [
                    'colSpan' => 4,
                    'rowSpan' => 1,
                    'sortOrder' => 78,
                ],
            ],
        ]],
        'params' => [
            'range' => [
                'default' => '7d',
                'type' => 'select',
                'label' => '统计范围',
                'options' => [
                    'today' => '今日',
                    '7d' => '近 7 天',
                    '30d' => '近 30 天',
                ],
            ],
            'website_id' => [
                'default' => '',
                'type' => 'string',
                'label' => '站点 ID',
                'description' => '留空时跟随当前 Dashboard 站点。',
            ],
        ],
    ],
    // E02：流量类型部件（走报表引擎 catalog pixel_traffic_type；E05 已写入 Installer 种子）
    'pixel_traffic_type' => [
        'name' => '流量类型',
        'description' => '按 traffic_type 聚合事件与价值，可下钻事件列表。',
        'type' => 'table',
        'code' => 'pixel_traffic_type',
        'area' => 'backend',
        'template' => 'Weline_Visitor::templates/dashboard/widgets/pixel-traffic-type.phtml',
        'page_layouts' => ['dashboard'],
        'position' => ['dashboard-detail'],
        'slot' => 'dashboard-detail',
        'supports' => ['dashboard-widget', 'dashboard-slot-detail', 'dashboard-table', 'dashboard-list'],
        'default_injections' => [[
            'layout_type' => 'dashboard',
            'layout_option' => 'default',
            'default_view' => 'weline_visitor_event_statistics',
            'target_type' => 'website',
            'slot' => 'dashboard-detail',
            'area' => 'content',
            'sort_order' => 79,
            'required' => false,
            'reason' => '流量类型报表部件（E02）；Installer 种子已含本 code（E05）',
            'config' => [
                'dashboard_layout' => [
                    'colSpan' => 4,
                    'rowSpan' => 1,
                    'sortOrder' => 79,
                ],
            ],
        ]],
        'params' => [
            'range' => [
                'default' => '7d',
                'type' => 'select',
                'label' => '统计范围',
                'options' => [
                    'today' => '今日',
                    '7d' => '近 7 天',
                    '30d' => '近 30 天',
                ],
            ],
            'website_id' => [
                'default' => '',
                'type' => 'string',
                'label' => '站点 ID',
                'description' => '留空时跟随当前 Dashboard 站点。',
            ],
        ],
    ],
    // E03a：付费广告部件（catalog pixel_paid；E05 已写入 Installer 种子）
    'pixel_paid' => [
        'name' => '付费广告',
        'description' => 'traffic_type=paid，按 utm_campaign 聚合事件与价值，可下钻事件列表。',
        'type' => 'table',
        'code' => 'pixel_paid',
        'area' => 'backend',
        'template' => 'Weline_Visitor::templates/dashboard/widgets/pixel-paid.phtml',
        'page_layouts' => ['dashboard'],
        'position' => ['dashboard-detail'],
        'slot' => 'dashboard-detail',
        'supports' => ['dashboard-widget', 'dashboard-slot-detail', 'dashboard-table', 'dashboard-list'],
        'default_injections' => [[
            'layout_type' => 'dashboard',
            'layout_option' => 'default',
            'default_view' => 'weline_visitor_event_statistics',
            'target_type' => 'website',
            'slot' => 'dashboard-detail',
            'area' => 'content',
            'sort_order' => 80,
            'required' => false,
            'reason' => '付费广告报表部件（E03a）；Installer 种子已含本 code（E05）',
            'config' => [
                'dashboard_layout' => [
                    'colSpan' => 4,
                    'rowSpan' => 1,
                    'sortOrder' => 80,
                ],
            ],
        ]],
        'params' => [
            'range' => [
                'default' => '7d',
                'type' => 'select',
                'label' => '统计范围',
                'options' => [
                    'today' => '今日',
                    '7d' => '近 7 天',
                    '30d' => '近 30 天',
                ],
            ],
            'website_id' => [
                'default' => '',
                'type' => 'string',
                'label' => '站点 ID',
                'description' => '留空时跟随当前 Dashboard 站点。',
            ],
        ],
    ],
    // E03b：社媒流量部件（catalog pixel_social；E05 已写入 Installer 种子）
    'pixel_social' => [
        'name' => '社媒流量',
        'description' => 'traffic_type=social，按 channel_code 聚合事件与价值，可下钻事件列表。',
        'type' => 'table',
        'code' => 'pixel_social',
        'area' => 'backend',
        'template' => 'Weline_Visitor::templates/dashboard/widgets/pixel-social.phtml',
        'page_layouts' => ['dashboard'],
        'position' => ['dashboard-detail'],
        'slot' => 'dashboard-detail',
        'supports' => ['dashboard-widget', 'dashboard-slot-detail', 'dashboard-table', 'dashboard-list'],
        'default_injections' => [[
            'layout_type' => 'dashboard',
            'layout_option' => 'default',
            'default_view' => 'weline_visitor_event_statistics',
            'target_type' => 'website',
            'slot' => 'dashboard-detail',
            'area' => 'content',
            'sort_order' => 81,
            'required' => false,
            'reason' => '社媒流量报表部件（E03b）；Installer 种子已含本 code（E05）',
            'config' => [
                'dashboard_layout' => [
                    'colSpan' => 4,
                    'rowSpan' => 1,
                    'sortOrder' => 81,
                ],
            ],
        ]],
        'params' => [
            'range' => [
                'default' => '7d',
                'type' => 'select',
                'label' => '统计范围',
                'options' => [
                    'today' => '今日',
                    '7d' => '近 7 天',
                    '30d' => '近 30 天',
                ],
            ],
            'website_id' => [
                'default' => '',
                'type' => 'string',
                'label' => '站点 ID',
                'description' => '留空时跟随当前 Dashboard 站点。',
            ],
        ],
    ],
    // E04a：事件价值部件（catalog pixel_event_value；E05 已写入 Installer 种子）
    'pixel_event_value' => [
        'name' => '事件价值',
        'description' => '按 event_name 聚合次数与价值，可下钻事件列表。',
        'type' => 'table',
        'code' => 'pixel_event_value',
        'area' => 'backend',
        'template' => 'Weline_Visitor::templates/dashboard/widgets/pixel-event-value.phtml',
        'page_layouts' => ['dashboard'],
        'position' => ['dashboard-detail'],
        'slot' => 'dashboard-detail',
        'supports' => ['dashboard-widget', 'dashboard-slot-detail', 'dashboard-table', 'dashboard-list'],
        'default_injections' => [[
            'layout_type' => 'dashboard',
            'layout_option' => 'default',
            'default_view' => 'weline_visitor_event_statistics',
            'target_type' => 'website',
            'slot' => 'dashboard-detail',
            'area' => 'content',
            'sort_order' => 82,
            'required' => false,
            'reason' => '事件价值报表部件（E04a）；Installer 种子已含本 code（E05）',
            'config' => [
                'dashboard_layout' => [
                    'colSpan' => 4,
                    'rowSpan' => 1,
                    'sortOrder' => 82,
                ],
            ],
        ]],
        'params' => [
            'range' => [
                'default' => '7d',
                'type' => 'select',
                'label' => '统计范围',
                'options' => [
                    'today' => '今日',
                    '7d' => '近 7 天',
                    '30d' => '近 30 天',
                ],
            ],
            'website_id' => [
                'default' => '',
                'type' => 'string',
                'label' => '站点 ID',
                'description' => '留空时跟随当前 Dashboard 站点。',
            ],
        ],
    ],
    // E04b：渠道价值部件（catalog pixel_value_by_channel；E05 已写入 Installer 种子）
    'pixel_value_by_channel' => [
        'name' => '渠道价值',
        'description' => '按 channel_code 聚合事件价值，可下钻事件列表。',
        'type' => 'table',
        'code' => 'pixel_value_by_channel',
        'area' => 'backend',
        'template' => 'Weline_Visitor::templates/dashboard/widgets/pixel-value-by-channel.phtml',
        'page_layouts' => ['dashboard'],
        'position' => ['dashboard-detail'],
        'slot' => 'dashboard-detail',
        'supports' => ['dashboard-widget', 'dashboard-slot-detail', 'dashboard-table', 'dashboard-list'],
        'default_injections' => [[
            'layout_type' => 'dashboard',
            'layout_option' => 'default',
            'default_view' => 'weline_visitor_event_statistics',
            'target_type' => 'website',
            'slot' => 'dashboard-detail',
            'area' => 'content',
            'sort_order' => 83,
            'required' => false,
            'reason' => '渠道价值报表部件（E04b）；Installer 种子已含本 code（E05）',
            'config' => [
                'dashboard_layout' => [
                    'colSpan' => 4,
                    'rowSpan' => 1,
                    'sortOrder' => 83,
                ],
            ],
        ]],
        'params' => [
            'range' => [
                'default' => '7d',
                'type' => 'select',
                'label' => '统计范围',
                'options' => [
                    'today' => '今日',
                    '7d' => '近 7 天',
                    '30d' => '近 30 天',
                ],
            ],
            'website_id' => [
                'default' => '',
                'type' => 'string',
                'label' => '站点 ID',
                'description' => '留空时跟随当前 Dashboard 站点。',
            ],
        ],
    ],
    // F05a：电商漏斗部件（F01 字典四步；Installer 种子已含）
    'pixel_ecommerce_funnel' => [
        'name' => '电商漏斗',
        'description' => '字典四步电商漏斗：浏览商品 → 加购 → 结账 → 购买。',
        'type' => 'table',
        'code' => 'pixel_ecommerce_funnel',
        'area' => 'backend',
        'template' => 'Weline_Visitor::templates/dashboard/widgets/pixel-ecommerce-funnel.phtml',
        'page_layouts' => ['dashboard'],
        'position' => ['dashboard-detail'],
        'slot' => 'dashboard-detail',
        'supports' => ['dashboard-widget', 'dashboard-slot-detail', 'dashboard-table', 'dashboard-funnel'],
        'default_injections' => [[
            'layout_type' => 'dashboard',
            'layout_option' => 'default',
            'default_view' => 'weline_visitor_event_statistics',
            'target_type' => 'website',
            'slot' => 'dashboard-detail',
            'area' => 'content',
            'sort_order' => 84,
            'required' => false,
            'reason' => '电商漏斗部件（F05a）；Installer 种子已含本 code',
            'config' => [
                'dashboard_layout' => [
                    'colSpan' => 4,
                    'rowSpan' => 1,
                    'sortOrder' => 84,
                ],
            ],
        ]],
        'params' => [
            'range' => [
                'default' => '7d',
                'type' => 'select',
                'label' => '统计范围',
                'options' => [
                    'today' => '今日',
                    '7d' => '近 7 天',
                    '30d' => '近 30 天',
                ],
            ],
            'website_id' => [
                'default' => '',
                'type' => 'string',
                'label' => '站点 ID',
                'description' => '留空时跟随当前 Dashboard 站点；电商报表需站点作用域。',
            ],
        ],
    ],
    // F05a：购成与收入部件（F02）
    'pixel_ecommerce_revenue' => [
        'name' => '购成与收入',
        'description' => '购买次数、购买收入、客单价与相对浏览商品的购成率。',
        'type' => 'stats',
        'code' => 'pixel_ecommerce_revenue',
        'area' => 'backend',
        'template' => 'Weline_Visitor::templates/dashboard/widgets/pixel-ecommerce-revenue.phtml',
        'page_layouts' => ['dashboard'],
        'position' => ['dashboard-detail'],
        'slot' => 'dashboard-detail',
        'supports' => ['dashboard-widget', 'dashboard-slot-detail', 'dashboard-stat', 'dashboard-kpi'],
        'default_injections' => [[
            'layout_type' => 'dashboard',
            'layout_option' => 'default',
            'default_view' => 'weline_visitor_event_statistics',
            'target_type' => 'website',
            'slot' => 'dashboard-detail',
            'area' => 'content',
            'sort_order' => 85,
            'required' => false,
            'reason' => '购成与收入部件（F05a）；Installer 种子已含本 code',
            'config' => [
                'dashboard_layout' => [
                    'colSpan' => 4,
                    'rowSpan' => 1,
                    'sortOrder' => 85,
                ],
            ],
        ]],
        'params' => [
            'range' => [
                'default' => '7d',
                'type' => 'select',
                'label' => '统计范围',
                'options' => [
                    'today' => '今日',
                    '7d' => '近 7 天',
                    '30d' => '近 30 天',
                ],
            ],
            'website_id' => [
                'default' => '',
                'type' => 'string',
                'label' => '站点 ID',
                'description' => '留空时跟随当前 Dashboard 站点；电商报表需站点作用域。',
            ],
        ],
    ],
    // F05a：商品表现部件（F03）
    'pixel_ecommerce_items' => [
        'name' => '商品表现',
        'description' => '按 item_id 展示曝光、加购、购买与商品收入。',
        'type' => 'table',
        'code' => 'pixel_ecommerce_items',
        'area' => 'backend',
        'template' => 'Weline_Visitor::templates/dashboard/widgets/pixel-ecommerce-items.phtml',
        'page_layouts' => ['dashboard'],
        'position' => ['dashboard-detail'],
        'slot' => 'dashboard-detail',
        'supports' => ['dashboard-widget', 'dashboard-slot-detail', 'dashboard-table', 'dashboard-list'],
        'default_injections' => [[
            'layout_type' => 'dashboard',
            'layout_option' => 'default',
            'default_view' => 'weline_visitor_event_statistics',
            'target_type' => 'website',
            'slot' => 'dashboard-detail',
            'area' => 'content',
            'sort_order' => 86,
            'required' => false,
            'reason' => '商品表现部件（F05a）；Installer 种子已含本 code',
            'config' => [
                'dashboard_layout' => [
                    'colSpan' => 4,
                    'rowSpan' => 1,
                    'sortOrder' => 86,
                ],
            ],
        ]],
        'params' => [
            'range' => [
                'default' => '7d',
                'type' => 'select',
                'label' => '统计范围',
                'options' => [
                    'today' => '今日',
                    '7d' => '近 7 天',
                    '30d' => '近 30 天',
                ],
            ],
            'website_id' => [
                'default' => '',
                'type' => 'string',
                'label' => '站点 ID',
                'description' => '留空时跟随当前 Dashboard 站点；电商报表需站点作用域。',
            ],
        ],
    ],
];
